//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 11:43:48 AM CEST 
//


package org.gestoresmadrid.oegam2comun.trafico.solInfoVehiculoApp.view.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Solicitud complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Solicitud">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estado" type="{}alfa2"/>
 *         &lt;element name="motivo" type="{}alfa2"/>
 *         &lt;element name="tipoInforme" type="{}alfa2"/>
 *         &lt;element name="matricula" type="{}tipoMatricula"/>
 *         &lt;element name="bastidor" type="{}tipoBastidor"/>
 *         &lt;element name="nive" type="{}tipoNive"/>
 *         &lt;element name="codigoTasa" type="{}tipoTasa"/>
 *         &lt;element name="informe" type="{}tipoB64"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Solicitud", propOrder = {
	"id",
    "estado",
    "motivo",
    "tipoInforme",
    "matricula",
    "bastidor",
    "nive",
    "codigoTasa",
    "informe"
})
public class Solicitud {

	
	@XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String estado;
    @XmlElement(required = true)
    protected String motivo;
    @XmlElement(required = true)
    protected String tipoInforme;
    @XmlElement(required = true)
    protected String matricula;
    @XmlElement(required = true)
    protected String bastidor;
    @XmlElement(required = true)
    protected String nive;
    @XmlElement(required = true)
    protected String codigoTasa;
    @XmlElement(required = true)
    protected byte[] informe;

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstado(String value) {
        this.estado = value;
    }

    /**
     * Gets the value of the motivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivo() {
        return motivo;
    }

    /**
     * Sets the value of the motivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivo(String value) {
        this.motivo = value;
    }

    /**
     * Gets the value of the tipoInforme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoInforme() {
        return tipoInforme;
    }

    /**
     * Sets the value of the tipoInforme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoInforme(String value) {
        this.tipoInforme = value;
    }

    /**
     * Gets the value of the matricula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatricula() {
        return matricula;
    }

    /**
     * Sets the value of the matricula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatricula(String value) {
        this.matricula = value;
    }

    /**
     * Gets the value of the bastidor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBastidor() {
        return bastidor;
    }

    /**
     * Sets the value of the bastidor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBastidor(String value) {
        this.bastidor = value;
    }

    /**
     * Gets the value of the nive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNive() {
        return nive;
    }

    /**
     * Sets the value of the nive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNive(String value) {
        this.nive = value;
    }

    /**
     * Gets the value of the codigoTasa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTasa() {
        return codigoTasa;
    }

    /**
     * Sets the value of the codigoTasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTasa(String value) {
        this.codigoTasa = value;
    }

    /**
     * Gets the value of the informe property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getInforme() {
        return informe;
    }

    /**
     * Sets the value of the informe property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setInforme(byte[] value) {
        this.informe = value;
    }

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
