//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 05:01:41 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.corpme;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Identificacion_Documento_NotarialType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identificacion_Documento_NotarialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Codigo_Notaria" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Codigo_Notario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Anyo_Protocolo" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Protocolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identificacion_Documento_NotarialType", propOrder = {
    "codigoNotaria",
    "codigoNotario",
    "anyoProtocolo",
    "protocolo"
})
public class IdentificacionDocumentoNotarialType {

    @XmlElement(name = "Codigo_Notaria", required = true)
    protected String codigoNotaria;
    @XmlElement(name = "Codigo_Notario", required = true)
    protected String codigoNotario;
    @XmlElement(name = "Anyo_Protocolo", required = true)
    protected BigInteger anyoProtocolo;
    @XmlElement(name = "Protocolo", required = true)
    protected String protocolo;

    /**
     * Gets the value of the codigoNotaria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoNotaria() {
        return codigoNotaria;
    }

    /**
     * Sets the value of the codigoNotaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoNotaria(String value) {
        this.codigoNotaria = value;
    }

    /**
     * Gets the value of the codigoNotario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoNotario() {
        return codigoNotario;
    }

    /**
     * Sets the value of the codigoNotario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoNotario(String value) {
        this.codigoNotario = value;
    }

    /**
     * Gets the value of the anyoProtocolo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnyoProtocolo() {
        return anyoProtocolo;
    }

    /**
     * Sets the value of the anyoProtocolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnyoProtocolo(BigInteger value) {
        this.anyoProtocolo = value;
    }

    /**
     * Gets the value of the protocolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolo() {
        return protocolo;
    }

    /**
     * Sets the value of the protocolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolo(String value) {
        this.protocolo = value;
    }

}
