//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 05:01:41 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.corpme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Identificacion_MinutaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identificacion_MinutaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Numero_Minuta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fecha_Minuta">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{2}/\d{2}/\d{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identificacion_MinutaType", propOrder = {
    "numeroMinuta",
    "fechaMinuta"
})
public class IdentificacionMinutaType {

    @XmlElement(name = "Numero_Minuta", required = true)
    protected String numeroMinuta;
    @XmlElement(name = "Fecha_Minuta", required = true)
    protected String fechaMinuta;

    /**
     * Gets the value of the numeroMinuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroMinuta() {
        return numeroMinuta;
    }

    /**
     * Sets the value of the numeroMinuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroMinuta(String value) {
        this.numeroMinuta = value;
    }

    /**
     * Gets the value of the fechaMinuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaMinuta() {
        return fechaMinuta;
    }

    /**
     * Sets the value of the fechaMinuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaMinuta(String value) {
        this.fechaMinuta = value;
    }

}
