//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 05:01:41 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.corpme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Obras_Grabaciones_AudiovisualesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Obras_Grabaciones_AudiovisualesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Isan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Num_Deposito_Legal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ambito_Territorial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ambito_Geografico" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tipo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Obra" type="{}ObraType"/>
 *                   &lt;element name="Grabacion" type="{}GrabacionType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Obras_Grabaciones_AudiovisualesType", propOrder = {

})
public class ObrasGrabacionesAudiovisualesType {

    @XmlElement(name = "Isan", required = true)
    protected String isan;
    @XmlElement(name = "Num_Deposito_Legal")
    protected String numDepositoLegal;
    @XmlElement(name = "Ambito_Territorial")
    protected String ambitoTerritorial;
    @XmlElement(name = "Ambito_Geografico")
    protected String ambitoGeografico;
    @XmlElement(name = "Tipo", required = true)
    protected ObrasGrabacionesAudiovisualesType.Tipo tipo;

    /**
     * Gets the value of the isan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsan() {
        return isan;
    }

    /**
     * Sets the value of the isan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsan(String value) {
        this.isan = value;
    }

    /**
     * Gets the value of the numDepositoLegal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumDepositoLegal() {
        return numDepositoLegal;
    }

    /**
     * Sets the value of the numDepositoLegal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumDepositoLegal(String value) {
        this.numDepositoLegal = value;
    }

    /**
     * Gets the value of the ambitoTerritorial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmbitoTerritorial() {
        return ambitoTerritorial;
    }

    /**
     * Sets the value of the ambitoTerritorial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmbitoTerritorial(String value) {
        this.ambitoTerritorial = value;
    }

    /**
     * Gets the value of the ambitoGeografico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmbitoGeografico() {
        return ambitoGeografico;
    }

    /**
     * Sets the value of the ambitoGeografico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmbitoGeografico(String value) {
        this.ambitoGeografico = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link ObrasGrabacionesAudiovisualesType.Tipo }
     *     
     */
    public ObrasGrabacionesAudiovisualesType.Tipo getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObrasGrabacionesAudiovisualesType.Tipo }
     *     
     */
    public void setTipo(ObrasGrabacionesAudiovisualesType.Tipo value) {
        this.tipo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Obra" type="{}ObraType"/>
     *         &lt;element name="Grabacion" type="{}GrabacionType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "obra",
        "grabacion"
    })
    public static class Tipo {

        @XmlElement(name = "Obra")
        protected ObraType obra;
        @XmlElement(name = "Grabacion")
        protected GrabacionType grabacion;

        /**
         * Gets the value of the obra property.
         * 
         * @return
         *     possible object is
         *     {@link ObraType }
         *     
         */
        public ObraType getObra() {
            return obra;
        }

        /**
         * Sets the value of the obra property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObraType }
         *     
         */
        public void setObra(ObraType value) {
            this.obra = value;
        }

        /**
         * Gets the value of the grabacion property.
         * 
         * @return
         *     possible object is
         *     {@link GrabacionType }
         *     
         */
        public GrabacionType getGrabacion() {
            return grabacion;
        }

        /**
         * Sets the value of the grabacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link GrabacionType }
         *     
         */
        public void setGrabacion(GrabacionType value) {
            this.grabacion = value;
        }

    }

}
