//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 05:01:41 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.corpme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Otros_BienesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Otros_BienesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Des_Otros_Bienes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Marca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Modelo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Num_Serie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Registro_Administrativo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tipo_Reg_Adm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Num_Reg_Adm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Ubicacion" type="{}UbicacionType" minOccurs="0"/>
 *         &lt;element name="Sociedad" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Nombre_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cif_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CNAE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Ins_Reg_Mercantil" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Cod_Reg_Mercantil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Seccion_Mercantil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Num_Hoja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Num_Hoja_Dup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Num_Sub_Hoja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Tomo_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Folio_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Ins_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Otra_Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Otros_BienesType", propOrder = {
    "desOtrosBienes",
    "registroAdministrativo",
    "ubicacion",
    "sociedad",
    "otraDescripcion"
})
public class OtrosBienesType {

    @XmlElement(name = "Des_Otros_Bienes")
    protected OtrosBienesType.DesOtrosBienes desOtrosBienes;
    @XmlElement(name = "Registro_Administrativo")
    protected OtrosBienesType.RegistroAdministrativo registroAdministrativo;
    @XmlElement(name = "Ubicacion")
    protected UbicacionType ubicacion;
    @XmlElement(name = "Sociedad")
    protected OtrosBienesType.Sociedad sociedad;
    @XmlElement(name = "Otra_Descripcion")
    protected Object otraDescripcion;

    /**
     * Gets the value of the desOtrosBienes property.
     * 
     * @return
     *     possible object is
     *     {@link OtrosBienesType.DesOtrosBienes }
     *     
     */
    public OtrosBienesType.DesOtrosBienes getDesOtrosBienes() {
        return desOtrosBienes;
    }

    /**
     * Sets the value of the desOtrosBienes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtrosBienesType.DesOtrosBienes }
     *     
     */
    public void setDesOtrosBienes(OtrosBienesType.DesOtrosBienes value) {
        this.desOtrosBienes = value;
    }

    /**
     * Gets the value of the registroAdministrativo property.
     * 
     * @return
     *     possible object is
     *     {@link OtrosBienesType.RegistroAdministrativo }
     *     
     */
    public OtrosBienesType.RegistroAdministrativo getRegistroAdministrativo() {
        return registroAdministrativo;
    }

    /**
     * Sets the value of the registroAdministrativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtrosBienesType.RegistroAdministrativo }
     *     
     */
    public void setRegistroAdministrativo(OtrosBienesType.RegistroAdministrativo value) {
        this.registroAdministrativo = value;
    }

    /**
     * Gets the value of the ubicacion property.
     * 
     * @return
     *     possible object is
     *     {@link UbicacionType }
     *     
     */
    public UbicacionType getUbicacion() {
        return ubicacion;
    }

    /**
     * Sets the value of the ubicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link UbicacionType }
     *     
     */
    public void setUbicacion(UbicacionType value) {
        this.ubicacion = value;
    }

    /**
     * Gets the value of the sociedad property.
     * 
     * @return
     *     possible object is
     *     {@link OtrosBienesType.Sociedad }
     *     
     */
    public OtrosBienesType.Sociedad getSociedad() {
        return sociedad;
    }

    /**
     * Sets the value of the sociedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtrosBienesType.Sociedad }
     *     
     */
    public void setSociedad(OtrosBienesType.Sociedad value) {
        this.sociedad = value;
    }

    /**
     * Gets the value of the otraDescripcion property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOtraDescripcion() {
        return otraDescripcion;
    }

    /**
     * Sets the value of the otraDescripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOtraDescripcion(Object value) {
        this.otraDescripcion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Marca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Modelo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Num_Serie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipo",
        "marca",
        "modelo",
        "numSerie"
    })
    public static class DesOtrosBienes {

        @XmlElement(name = "Tipo")
        protected String tipo;
        @XmlElement(name = "Marca")
        protected String marca;
        @XmlElement(name = "Modelo")
        protected String modelo;
        @XmlElement(name = "Num_Serie")
        protected String numSerie;

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the marca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMarca() {
            return marca;
        }

        /**
         * Sets the value of the marca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMarca(String value) {
            this.marca = value;
        }

        /**
         * Gets the value of the modelo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModelo() {
            return modelo;
        }

        /**
         * Sets the value of the modelo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModelo(String value) {
            this.modelo = value;
        }

        /**
         * Gets the value of the numSerie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumSerie() {
            return numSerie;
        }

        /**
         * Sets the value of the numSerie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumSerie(String value) {
            this.numSerie = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tipo_Reg_Adm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Num_Reg_Adm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoRegAdm",
        "numRegAdm"
    })
    public static class RegistroAdministrativo {

        @XmlElement(name = "Tipo_Reg_Adm", required = true)
        protected String tipoRegAdm;
        @XmlElement(name = "Num_Reg_Adm", required = true)
        protected String numRegAdm;

        /**
         * Gets the value of the tipoRegAdm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoRegAdm() {
            return tipoRegAdm;
        }

        /**
         * Sets the value of the tipoRegAdm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoRegAdm(String value) {
            this.tipoRegAdm = value;
        }

        /**
         * Gets the value of the numRegAdm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumRegAdm() {
            return numRegAdm;
        }

        /**
         * Sets the value of the numRegAdm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumRegAdm(String value) {
            this.numRegAdm = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Nombre_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cif_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CNAE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Ins_Reg_Mercantil" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Cod_Reg_Mercantil" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Seccion_Mercantil" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Num_Hoja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Num_Hoja_Dup" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Num_Sub_Hoja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Tomo_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Folio_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Ins_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nombreSociedad",
        "cifSociedad",
        "cnae",
        "insRegMercantil"
    })
    public static class Sociedad {

        @XmlElement(name = "Nombre_Sociedad", required = true)
        protected String nombreSociedad;
        @XmlElement(name = "Cif_Sociedad", required = true)
        protected String cifSociedad;
        @XmlElement(name = "CNAE")
        protected String cnae;
        @XmlElement(name = "Ins_Reg_Mercantil")
        protected OtrosBienesType.Sociedad.InsRegMercantil insRegMercantil;

        /**
         * Gets the value of the nombreSociedad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreSociedad() {
            return nombreSociedad;
        }

        /**
         * Sets the value of the nombreSociedad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreSociedad(String value) {
            this.nombreSociedad = value;
        }

        /**
         * Gets the value of the cifSociedad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCifSociedad() {
            return cifSociedad;
        }

        /**
         * Sets the value of the cifSociedad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCifSociedad(String value) {
            this.cifSociedad = value;
        }

        /**
         * Gets the value of the cnae property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCNAE() {
            return cnae;
        }

        /**
         * Sets the value of the cnae property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCNAE(String value) {
            this.cnae = value;
        }

        /**
         * Gets the value of the insRegMercantil property.
         * 
         * @return
         *     possible object is
         *     {@link OtrosBienesType.Sociedad.InsRegMercantil }
         *     
         */
        public OtrosBienesType.Sociedad.InsRegMercantil getInsRegMercantil() {
            return insRegMercantil;
        }

        /**
         * Sets the value of the insRegMercantil property.
         * 
         * @param value
         *     allowed object is
         *     {@link OtrosBienesType.Sociedad.InsRegMercantil }
         *     
         */
        public void setInsRegMercantil(OtrosBienesType.Sociedad.InsRegMercantil value) {
            this.insRegMercantil = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Cod_Reg_Mercantil" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Seccion_Mercantil" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Num_Hoja" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Num_Hoja_Dup" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Num_Sub_Hoja" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Tomo_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Folio_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Ins_Sociedad" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "codRegMercantil",
            "seccionMercantil",
            "numHoja",
            "numHojaDup",
            "numSubHoja",
            "tomoSociedad",
            "folioSociedad",
            "insSociedad"
        })
        public static class InsRegMercantil {

            @XmlElement(name = "Cod_Reg_Mercantil", required = true)
            protected String codRegMercantil;
            @XmlElement(name = "Seccion_Mercantil", required = true)
            protected String seccionMercantil;
            @XmlElement(name = "Num_Hoja", required = true)
            protected String numHoja;
            @XmlElement(name = "Num_Hoja_Dup", required = true)
            protected String numHojaDup;
            @XmlElement(name = "Num_Sub_Hoja", required = true)
            protected String numSubHoja;
            @XmlElement(name = "Tomo_Sociedad", required = true)
            protected String tomoSociedad;
            @XmlElement(name = "Folio_Sociedad", required = true)
            protected String folioSociedad;
            @XmlElement(name = "Ins_Sociedad", required = true)
            protected String insSociedad;

            /**
             * Gets the value of the codRegMercantil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodRegMercantil() {
                return codRegMercantil;
            }

            /**
             * Sets the value of the codRegMercantil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodRegMercantil(String value) {
                this.codRegMercantil = value;
            }

            /**
             * Gets the value of the seccionMercantil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeccionMercantil() {
                return seccionMercantil;
            }

            /**
             * Sets the value of the seccionMercantil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeccionMercantil(String value) {
                this.seccionMercantil = value;
            }

            /**
             * Gets the value of the numHoja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumHoja() {
                return numHoja;
            }

            /**
             * Sets the value of the numHoja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumHoja(String value) {
                this.numHoja = value;
            }

            /**
             * Gets the value of the numHojaDup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumHojaDup() {
                return numHojaDup;
            }

            /**
             * Sets the value of the numHojaDup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumHojaDup(String value) {
                this.numHojaDup = value;
            }

            /**
             * Gets the value of the numSubHoja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumSubHoja() {
                return numSubHoja;
            }

            /**
             * Sets the value of the numSubHoja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumSubHoja(String value) {
                this.numSubHoja = value;
            }

            /**
             * Gets the value of the tomoSociedad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTomoSociedad() {
                return tomoSociedad;
            }

            /**
             * Sets the value of the tomoSociedad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTomoSociedad(String value) {
                this.tomoSociedad = value;
            }

            /**
             * Gets the value of the folioSociedad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFolioSociedad() {
                return folioSociedad;
            }

            /**
             * Sets the value of the folioSociedad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFolioSociedad(String value) {
                this.folioSociedad = value;
            }

            /**
             * Gets the value of the insSociedad property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInsSociedad() {
                return insSociedad;
            }

            /**
             * Sets the value of the insSociedad property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInsSociedad(String value) {
                this.insSociedad = value;
            }

        }

    }

}
