//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 05:01:41 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.corpme;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tipo_OperacionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tipo_OperacionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Mercantil">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Operacion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                         &lt;enumeration value="7"/>
 *                         &lt;enumeration value="8"/>
 *                         &lt;enumeration value="9"/>
 *                         &lt;enumeration value="10"/>
 *                         &lt;enumeration value="11"/>
 *                         &lt;enumeration value="12"/>
 *                         &lt;enumeration value="13"/>
 *                         &lt;enumeration value="14"/>
 *                         &lt;enumeration value="15"/>
 *                         &lt;enumeration value="16"/>
 *                         &lt;enumeration value="17"/>
 *                         &lt;enumeration value="18"/>
 *                         &lt;enumeration value="19"/>
 *                         &lt;enumeration value="20"/>
 *                         &lt;enumeration value="21"/>
 *                         &lt;enumeration value="22"/>
 *                         &lt;enumeration value="23"/>
 *                         &lt;enumeration value="24"/>
 *                         &lt;enumeration value="25"/>
 *                         &lt;enumeration value="26"/>
 *                         &lt;enumeration value="27"/>
 *                         &lt;enumeration value="28"/>
 *                         &lt;enumeration value="29"/>
 *                         &lt;enumeration value="30"/>
 *                         &lt;enumeration value="31"/>
 *                         &lt;enumeration value="32"/>
 *                         &lt;enumeration value="33"/>
 *                         &lt;enumeration value="34"/>
 *                         &lt;enumeration value="35"/>
 *                         &lt;enumeration value="36"/>
 *                         &lt;enumeration value="37"/>
 *                         &lt;enumeration value="38"/>
 *                         &lt;enumeration value="39"/>
 *                         &lt;enumeration value="40"/>
 *                         &lt;enumeration value="41"/>
 *                         &lt;enumeration value="42"/>
 *                         &lt;enumeration value="43"/>
 *                         &lt;enumeration value="44"/>
 *                         &lt;enumeration value="45"/>
 *                         &lt;enumeration value="46"/>
 *                         &lt;enumeration value="47"/>
 *                         &lt;enumeration value="48"/>
 *                         &lt;enumeration value="49"/>
 *                         &lt;enumeration value="50"/>
 *                         &lt;enumeration value="51"/>
 *                         &lt;enumeration value="52"/>
 *                         &lt;enumeration value="53"/>
 *                         &lt;enumeration value="54"/>
 *                         &lt;enumeration value="55"/>
 *                         &lt;enumeration value="56"/>
 *                         &lt;enumeration value="57"/>
 *                         &lt;enumeration value="58"/>
 *                         &lt;enumeration value="59"/>
 *                         &lt;enumeration value="60"/>
 *                         &lt;enumeration value="61"/>
 *                         &lt;enumeration value="62"/>
 *                         &lt;enumeration value="63"/>
 *                         &lt;enumeration value="64"/>
 *                         &lt;enumeration value="65"/>
 *                         &lt;enumeration value="66"/>
 *                         &lt;enumeration value="67"/>
 *                         &lt;enumeration value="68"/>
 *                         &lt;enumeration value="69"/>
 *                         &lt;enumeration value="70"/>
 *                         &lt;enumeration value="71"/>
 *                         &lt;enumeration value="72"/>
 *                         &lt;enumeration value="73"/>
 *                         &lt;enumeration value="74"/>
 *                         &lt;enumeration value="75"/>
 *                         &lt;enumeration value="76"/>
 *                         &lt;enumeration value="77"/>
 *                         &lt;enumeration value="78"/>
 *                         &lt;enumeration value="79"/>
 *                         &lt;enumeration value="80"/>
 *                         &lt;enumeration value="81"/>
 *                         &lt;enumeration value="82"/>
 *                         &lt;enumeration value="83"/>
 *                         &lt;enumeration value="84"/>
 *                         &lt;enumeration value="85"/>
 *                         &lt;enumeration value="86"/>
 *                         &lt;enumeration value="87"/>
 *                         &lt;enumeration value="88"/>
 *                         &lt;enumeration value="89"/>
 *                         &lt;enumeration value="90"/>
 *                         &lt;enumeration value="91"/>
 *                         &lt;enumeration value="92"/>
 *                         &lt;enumeration value="93"/>
 *                         &lt;enumeration value="94"/>
 *                         &lt;enumeration value="95"/>
 *                         &lt;enumeration value="100"/>
 *                         &lt;enumeration value="101"/>
 *                         &lt;enumeration value="102"/>
 *                         &lt;enumeration value="104"/>
 *                         &lt;enumeration value="105"/>
 *                         &lt;enumeration value="106"/>
 *                         &lt;enumeration value="107"/>
 *                         &lt;enumeration value="108"/>
 *                         &lt;enumeration value="109"/>
 *                         &lt;enumeration value="110"/>
 *                         &lt;enumeration value="111"/>
 *                         &lt;enumeration value="112"/>
 *                         &lt;enumeration value="113"/>
 *                         &lt;enumeration value="114"/>
 *                         &lt;enumeration value="115"/>
 *                         &lt;enumeration value="116"/>
 *                         &lt;enumeration value="117"/>
 *                         &lt;enumeration value="118"/>
 *                         &lt;enumeration value="119"/>
 *                         &lt;enumeration value="120"/>
 *                         &lt;enumeration value="121"/>
 *                         &lt;enumeration value="122"/>
 *                         &lt;enumeration value="123"/>
 *                         &lt;enumeration value="124"/>
 *                         &lt;enumeration value="125"/>
 *                         &lt;enumeration value="126"/>
 *                         &lt;enumeration value="129"/>
 *                         &lt;enumeration value="130"/>
 *                         &lt;enumeration value="131"/>
 *                         &lt;enumeration value="138"/>
 *                         &lt;enumeration value="139"/>
 *                         &lt;enumeration value="140"/>
 *                         &lt;enumeration value="142"/>
 *                         &lt;enumeration value="145"/>
 *                         &lt;enumeration value="147"/>
 *                         &lt;enumeration value="148"/>
 *                         &lt;enumeration value="149"/>
 *                         &lt;enumeration value="150"/>
 *                         &lt;enumeration value="151"/>
 *                         &lt;enumeration value="153"/>
 *                         &lt;enumeration value="154"/>
 *                         &lt;enumeration value="155"/>
 *                         &lt;enumeration value="156"/>
 *                         &lt;enumeration value="157"/>
 *                         &lt;enumeration value="158"/>
 *                         &lt;enumeration value="160"/>
 *                         &lt;enumeration value="161"/>
 *                         &lt;enumeration value="162"/>
 *                         &lt;enumeration value="163"/>
 *                         &lt;enumeration value="164"/>
 *                         &lt;enumeration value="165"/>
 *                         &lt;enumeration value="168"/>
 *                         &lt;enumeration value="170"/>
 *                         &lt;enumeration value="171"/>
 *                         &lt;enumeration value="173"/>
 *                         &lt;enumeration value="174"/>
 *                         &lt;enumeration value="175"/>
 *                         &lt;enumeration value="176"/>
 *                         &lt;enumeration value="177"/>
 *                         &lt;enumeration value="180"/>
 *                         &lt;enumeration value="181"/>
 *                         &lt;enumeration value="183"/>
 *                         &lt;enumeration value="184"/>
 *                         &lt;enumeration value="187"/>
 *                         &lt;enumeration value="188"/>
 *                         &lt;enumeration value="300"/>
 *                         &lt;enumeration value="301"/>
 *                         &lt;enumeration value="302"/>
 *                         &lt;enumeration value="303"/>
 *                         &lt;enumeration value="401"/>
 *                         &lt;enumeration value="402"/>
 *                         &lt;enumeration value="403"/>
 *                         &lt;enumeration value="500"/>
 *                         &lt;enumeration value="501"/>
 *                         &lt;enumeration value="502"/>
 *                         &lt;enumeration value="503"/>
 *                         &lt;enumeration value="504"/>
 *                         &lt;enumeration value="505"/>
 *                         &lt;enumeration value="506"/>
 *                         &lt;enumeration value="507"/>
 *                         &lt;enumeration value="508"/>
 *                         &lt;enumeration value="509"/>
 *                         &lt;enumeration value="510"/>
 *                         &lt;enumeration value="511"/>
 *                         &lt;enumeration value="512"/>
 *                         &lt;enumeration value="513"/>
 *                         &lt;enumeration value="514"/>
 *                         &lt;enumeration value="515"/>
 *                         &lt;enumeration value="1000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Datos_Operacion" type="{}Datos_Operacion_MercantilType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Propiedad">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Operacion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                         &lt;enumeration value="7"/>
 *                         &lt;enumeration value="8"/>
 *                         &lt;enumeration value="9"/>
 *                         &lt;enumeration value="10"/>
 *                         &lt;enumeration value="11"/>
 *                         &lt;enumeration value="12"/>
 *                         &lt;enumeration value="13"/>
 *                         &lt;enumeration value="14"/>
 *                         &lt;enumeration value="15"/>
 *                         &lt;enumeration value="16"/>
 *                         &lt;enumeration value="17"/>
 *                         &lt;enumeration value="18"/>
 *                         &lt;enumeration value="19"/>
 *                         &lt;enumeration value="20"/>
 *                         &lt;enumeration value="21"/>
 *                         &lt;enumeration value="22"/>
 *                         &lt;enumeration value="23"/>
 *                         &lt;enumeration value="24"/>
 *                         &lt;enumeration value="25"/>
 *                         &lt;enumeration value="26"/>
 *                         &lt;enumeration value="27"/>
 *                         &lt;enumeration value="28"/>
 *                         &lt;enumeration value="29"/>
 *                         &lt;enumeration value="30"/>
 *                         &lt;enumeration value="31"/>
 *                         &lt;enumeration value="32"/>
 *                         &lt;enumeration value="33"/>
 *                         &lt;enumeration value="34"/>
 *                         &lt;enumeration value="35"/>
 *                         &lt;enumeration value="36"/>
 *                         &lt;enumeration value="37"/>
 *                         &lt;enumeration value="38"/>
 *                         &lt;enumeration value="39"/>
 *                         &lt;enumeration value="40"/>
 *                         &lt;enumeration value="41"/>
 *                         &lt;enumeration value="42"/>
 *                         &lt;enumeration value="43"/>
 *                         &lt;enumeration value="44"/>
 *                         &lt;enumeration value="45"/>
 *                         &lt;enumeration value="46"/>
 *                         &lt;enumeration value="47"/>
 *                         &lt;enumeration value="48"/>
 *                         &lt;enumeration value="49"/>
 *                         &lt;enumeration value="50"/>
 *                         &lt;enumeration value="51"/>
 *                         &lt;enumeration value="52"/>
 *                         &lt;enumeration value="53"/>
 *                         &lt;enumeration value="54"/>
 *                         &lt;enumeration value="55"/>
 *                         &lt;enumeration value="56"/>
 *                         &lt;enumeration value="57"/>
 *                         &lt;enumeration value="58"/>
 *                         &lt;enumeration value="59"/>
 *                         &lt;enumeration value="60"/>
 *                         &lt;enumeration value="61"/>
 *                         &lt;enumeration value="62"/>
 *                         &lt;enumeration value="63"/>
 *                         &lt;enumeration value="64"/>
 *                         &lt;enumeration value="65"/>
 *                         &lt;enumeration value="66"/>
 *                         &lt;enumeration value="67"/>
 *                         &lt;enumeration value="68"/>
 *                         &lt;enumeration value="69"/>
 *                         &lt;enumeration value="70"/>
 *                         &lt;enumeration value="71"/>
 *                         &lt;enumeration value="72"/>
 *                         &lt;enumeration value="73"/>
 *                         &lt;enumeration value="74"/>
 *                         &lt;enumeration value="75"/>
 *                         &lt;enumeration value="76"/>
 *                         &lt;enumeration value="77"/>
 *                         &lt;enumeration value="78"/>
 *                         &lt;enumeration value="79"/>
 *                         &lt;enumeration value="80"/>
 *                         &lt;enumeration value="81"/>
 *                         &lt;enumeration value="82"/>
 *                         &lt;enumeration value="83"/>
 *                         &lt;enumeration value="84"/>
 *                         &lt;enumeration value="85"/>
 *                         &lt;enumeration value="86"/>
 *                         &lt;enumeration value="87"/>
 *                         &lt;enumeration value="88"/>
 *                         &lt;enumeration value="89"/>
 *                         &lt;enumeration value="90"/>
 *                         &lt;enumeration value="91"/>
 *                         &lt;enumeration value="92"/>
 *                         &lt;enumeration value="93"/>
 *                         &lt;enumeration value="94"/>
 *                         &lt;enumeration value="95"/>
 *                         &lt;enumeration value="96"/>
 *                         &lt;enumeration value="97"/>
 *                         &lt;enumeration value="98"/>
 *                         &lt;enumeration value="99"/>
 *                         &lt;enumeration value="100"/>
 *                         &lt;enumeration value="101"/>
 *                         &lt;enumeration value="102"/>
 *                         &lt;enumeration value="103"/>
 *                         &lt;enumeration value="104"/>
 *                         &lt;enumeration value="105"/>
 *                         &lt;enumeration value="106"/>
 *                         &lt;enumeration value="107"/>
 *                         &lt;enumeration value="108"/>
 *                         &lt;enumeration value="109"/>
 *                         &lt;enumeration value="110"/>
 *                         &lt;enumeration value="111"/>
 *                         &lt;enumeration value="112"/>
 *                         &lt;enumeration value="113"/>
 *                         &lt;enumeration value="114"/>
 *                         &lt;enumeration value="115"/>
 *                         &lt;enumeration value="116"/>
 *                         &lt;enumeration value="117"/>
 *                         &lt;enumeration value="118"/>
 *                         &lt;enumeration value="119"/>
 *                         &lt;enumeration value="120"/>
 *                         &lt;enumeration value="121"/>
 *                         &lt;enumeration value="122"/>
 *                         &lt;enumeration value="123"/>
 *                         &lt;enumeration value="1000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bienes_Muebles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Operacion">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="AET"/>
 *                         &lt;enumeration value="AFE"/>
 *                         &lt;enumeration value="AJ"/>
 *                         &lt;enumeration value="AP"/>
 *                         &lt;enumeration value="AT"/>
 *                         &lt;enumeration value="C"/>
 *                         &lt;enumeration value="CA"/>
 *                         &lt;enumeration value="CAE"/>
 *                         &lt;enumeration value="CAT"/>
 *                         &lt;enumeration value="CCI"/>
 *                         &lt;enumeration value="CD"/>
 *                         &lt;enumeration value="CET"/>
 *                         &lt;enumeration value="CJI"/>
 *                         &lt;enumeration value="D"/>
 *                         &lt;enumeration value="DB"/>
 *                         &lt;enumeration value="DE"/>
 *                         &lt;enumeration value="E"/>
 *                         &lt;enumeration value="EF"/>
 *                         &lt;enumeration value="EM"/>
 *                         &lt;enumeration value="FD"/>
 *                         &lt;enumeration value="MC"/>
 *                         &lt;enumeration value="MET"/>
 *                         &lt;enumeration value="NC"/>
 *                         &lt;enumeration value="O"/>
 *                         &lt;enumeration value="RA"/>
 *                         &lt;enumeration value="RCC"/>
 *                         &lt;enumeration value="RI"/>
 *                         &lt;enumeration value="RJ"/>
 *                         &lt;enumeration value="RJC"/>
 *                         &lt;enumeration value="RP"/>
 *                         &lt;enumeration value="RT"/>
 *                         &lt;enumeration value="SC"/>
 *                         &lt;enumeration value="SN"/>
 *                         &lt;enumeration value="ADJ"/>
 *                         &lt;enumeration value="AME"/>
 *                         &lt;enumeration value="APD"/>
 *                         &lt;enumeration value="APE"/>
 *                         &lt;enumeration value="APO"/>
 *                         &lt;enumeration value="APR"/>
 *                         &lt;enumeration value="BA"/>
 *                         &lt;enumeration value="CC"/>
 *                         &lt;enumeration value="CCD"/>
 *                         &lt;enumeration value="CEM"/>
 *                         &lt;enumeration value="CMC"/>
 *                         &lt;enumeration value="CR"/>
 *                         &lt;enumeration value="DAP"/>
 *                         &lt;enumeration value="DCO"/>
 *                         &lt;enumeration value="DN"/>
 *                         &lt;enumeration value="DP"/>
 *                         &lt;enumeration value="EMC"/>
 *                         &lt;enumeration value="MEM"/>
 *                         &lt;enumeration value="PRE"/>
 *                         &lt;enumeration value="CAH"/>
 *                         &lt;enumeration value="CAP"/>
 *                         &lt;enumeration value="CAF"/>
 *                         &lt;enumeration value="1000"/>
 *                         &lt;enumeration value="SPA"/>
 *                         &lt;enumeration value="GDC"/>
 *                         &lt;enumeration value="GPU"/>
 *                         &lt;enumeration value="GRM"/>
 *                         &lt;enumeration value="GRJ"/>
 *                         &lt;enumeration value="GRN"/>
 *                         &lt;enumeration value="GRC"/>
 *                         &lt;enumeration value="GRR"/>
 *                         &lt;enumeration value="GRD"/>
 *                         &lt;enumeration value="GPR"/>
 *                         &lt;enumeration value="GAI"/>
 *                         &lt;enumeration value="GAY"/>
 *                         &lt;enumeration value="GAC"/>
 *                         &lt;enumeration value="GAA"/>
 *                         &lt;enumeration value="GAL"/>
 *                         &lt;enumeration value="GRS"/>
 *                         &lt;enumeration value="GCP"/>
 *                         &lt;enumeration value="GCI"/>
 *                         &lt;enumeration value="GCC"/>
 *                         &lt;enumeration value="GCJ"/>
 *                         &lt;enumeration value="GCF"/>
 *                         &lt;enumeration value="GCD"/>
 *                         &lt;enumeration value="GCA"/>
 *                         &lt;enumeration value="IDE"/>
 *                         &lt;enumeration value="PAC"/>
 *                         &lt;enumeration value="ODR"/>
 *                         &lt;enumeration value="IDE"/>
 *                         &lt;enumeration value="PAC"/>
 *                         &lt;enumeration value="ODR"/>
 *                         &lt;enumeration value="LDI"/>
 *                         &lt;enumeration value="CDI"/>
 *                         &lt;enumeration value="LDA"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Tipo_Contrato" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="A1"/>
 *                         &lt;enumeration value="A2"/>
 *                         &lt;enumeration value="AH"/>
 *                         &lt;enumeration value="B1"/>
 *                         &lt;enumeration value="B2"/>
 *                         &lt;enumeration value="C1"/>
 *                         &lt;enumeration value="C2"/>
 *                         &lt;enumeration value="H"/>
 *                         &lt;enumeration value="HM"/>
 *                         &lt;enumeration value="L1"/>
 *                         &lt;enumeration value="L2"/>
 *                         &lt;enumeration value="PD"/>
 *                         &lt;enumeration value="R1"/>
 *                         &lt;enumeration value="R2"/>
 *                         &lt;enumeration value="EN"/>
 *                         &lt;enumeration value="CV"/>
 *                         &lt;enumeration value="PE"/>
 *                         &lt;enumeration value="SUA"/>
 *                         &lt;enumeration value="MSF"/>
 *                         &lt;enumeration value="B3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tipo_OperacionType", propOrder = {
    "mercantil",
    "propiedad",
    "bienesMuebles"
})
public class TipoOperacionType {

    @XmlElement(name = "Mercantil")
    protected TipoOperacionType.Mercantil mercantil;
    @XmlElement(name = "Propiedad")
    protected TipoOperacionType.Propiedad propiedad;
    @XmlElement(name = "Bienes_Muebles")
    protected TipoOperacionType.BienesMuebles bienesMuebles;

    /**
     * Gets the value of the mercantil property.
     * 
     * @return
     *     possible object is
     *     {@link TipoOperacionType.Mercantil }
     *     
     */
    public TipoOperacionType.Mercantil getMercantil() {
        return mercantil;
    }

    /**
     * Sets the value of the mercantil property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoOperacionType.Mercantil }
     *     
     */
    public void setMercantil(TipoOperacionType.Mercantil value) {
        this.mercantil = value;
    }

    /**
     * Gets the value of the propiedad property.
     * 
     * @return
     *     possible object is
     *     {@link TipoOperacionType.Propiedad }
     *     
     */
    public TipoOperacionType.Propiedad getPropiedad() {
        return propiedad;
    }

    /**
     * Sets the value of the propiedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoOperacionType.Propiedad }
     *     
     */
    public void setPropiedad(TipoOperacionType.Propiedad value) {
        this.propiedad = value;
    }

    /**
     * Gets the value of the bienesMuebles property.
     * 
     * @return
     *     possible object is
     *     {@link TipoOperacionType.BienesMuebles }
     *     
     */
    public TipoOperacionType.BienesMuebles getBienesMuebles() {
        return bienesMuebles;
    }

    /**
     * Sets the value of the bienesMuebles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoOperacionType.BienesMuebles }
     *     
     */
    public void setBienesMuebles(TipoOperacionType.BienesMuebles value) {
        this.bienesMuebles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Operacion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="AET"/>
     *               &lt;enumeration value="AFE"/>
     *               &lt;enumeration value="AJ"/>
     *               &lt;enumeration value="AP"/>
     *               &lt;enumeration value="AT"/>
     *               &lt;enumeration value="C"/>
     *               &lt;enumeration value="CA"/>
     *               &lt;enumeration value="CAE"/>
     *               &lt;enumeration value="CAT"/>
     *               &lt;enumeration value="CCI"/>
     *               &lt;enumeration value="CD"/>
     *               &lt;enumeration value="CET"/>
     *               &lt;enumeration value="CJI"/>
     *               &lt;enumeration value="D"/>
     *               &lt;enumeration value="DB"/>
     *               &lt;enumeration value="DE"/>
     *               &lt;enumeration value="E"/>
     *               &lt;enumeration value="EF"/>
     *               &lt;enumeration value="EM"/>
     *               &lt;enumeration value="FD"/>
     *               &lt;enumeration value="MC"/>
     *               &lt;enumeration value="MET"/>
     *               &lt;enumeration value="NC"/>
     *               &lt;enumeration value="O"/>
     *               &lt;enumeration value="RA"/>
     *               &lt;enumeration value="RCC"/>
     *               &lt;enumeration value="RI"/>
     *               &lt;enumeration value="RJ"/>
     *               &lt;enumeration value="RJC"/>
     *               &lt;enumeration value="RP"/>
     *               &lt;enumeration value="RT"/>
     *               &lt;enumeration value="SC"/>
     *               &lt;enumeration value="SN"/>
     *               &lt;enumeration value="ADJ"/>
     *               &lt;enumeration value="AME"/>
     *               &lt;enumeration value="APD"/>
     *               &lt;enumeration value="APE"/>
     *               &lt;enumeration value="APO"/>
     *               &lt;enumeration value="APR"/>
     *               &lt;enumeration value="BA"/>
     *               &lt;enumeration value="CC"/>
     *               &lt;enumeration value="CCD"/>
     *               &lt;enumeration value="CEM"/>
     *               &lt;enumeration value="CMC"/>
     *               &lt;enumeration value="CR"/>
     *               &lt;enumeration value="DAP"/>
     *               &lt;enumeration value="DCO"/>
     *               &lt;enumeration value="DN"/>
     *               &lt;enumeration value="DP"/>
     *               &lt;enumeration value="EMC"/>
     *               &lt;enumeration value="MEM"/>
     *               &lt;enumeration value="PRE"/>
     *               &lt;enumeration value="CAH"/>
     *               &lt;enumeration value="CAP"/>
     *               &lt;enumeration value="CAF"/>
     *               &lt;enumeration value="1000"/>
     *               &lt;enumeration value="SPA"/>
     *               &lt;enumeration value="GDC"/>
     *               &lt;enumeration value="GPU"/>
     *               &lt;enumeration value="GRM"/>
     *               &lt;enumeration value="GRJ"/>
     *               &lt;enumeration value="GRN"/>
     *               &lt;enumeration value="GRC"/>
     *               &lt;enumeration value="GRR"/>
     *               &lt;enumeration value="GRD"/>
     *               &lt;enumeration value="GPR"/>
     *               &lt;enumeration value="GAI"/>
     *               &lt;enumeration value="GAY"/>
     *               &lt;enumeration value="GAC"/>
     *               &lt;enumeration value="GAA"/>
     *               &lt;enumeration value="GAL"/>
     *               &lt;enumeration value="GRS"/>
     *               &lt;enumeration value="GCP"/>
     *               &lt;enumeration value="GCI"/>
     *               &lt;enumeration value="GCC"/>
     *               &lt;enumeration value="GCJ"/>
     *               &lt;enumeration value="GCF"/>
     *               &lt;enumeration value="GCD"/>
     *               &lt;enumeration value="GCA"/>
     *               &lt;enumeration value="IDE"/>
     *               &lt;enumeration value="PAC"/>
     *               &lt;enumeration value="ODR"/>
     *               &lt;enumeration value="IDE"/>
     *               &lt;enumeration value="PAC"/>
     *               &lt;enumeration value="ODR"/>
     *               &lt;enumeration value="LDI"/>
     *               &lt;enumeration value="CDI"/>
     *               &lt;enumeration value="LDA"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Tipo_Contrato" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="A1"/>
     *               &lt;enumeration value="A2"/>
     *               &lt;enumeration value="AH"/>
     *               &lt;enumeration value="B1"/>
     *               &lt;enumeration value="B2"/>
     *               &lt;enumeration value="C1"/>
     *               &lt;enumeration value="C2"/>
     *               &lt;enumeration value="H"/>
     *               &lt;enumeration value="HM"/>
     *               &lt;enumeration value="L1"/>
     *               &lt;enumeration value="L2"/>
     *               &lt;enumeration value="PD"/>
     *               &lt;enumeration value="R1"/>
     *               &lt;enumeration value="R2"/>
     *               &lt;enumeration value="EN"/>
     *               &lt;enumeration value="CV"/>
     *               &lt;enumeration value="PE"/>
     *               &lt;enumeration value="SUA"/>
     *               &lt;enumeration value="MSF"/>
     *               &lt;enumeration value="B3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operacion",
        "tipoContrato"
    })
    public static class BienesMuebles {

        @XmlElement(name = "Operacion", required = true)
        protected String operacion;
        @XmlElement(name = "Tipo_Contrato")
        protected String tipoContrato;

        /**
         * Gets the value of the operacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperacion() {
            return operacion;
        }

        /**
         * Sets the value of the operacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperacion(String value) {
            this.operacion = value;
        }

        /**
         * Gets the value of the tipoContrato property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoContrato() {
            return tipoContrato;
        }

        /**
         * Sets the value of the tipoContrato property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoContrato(String value) {
            this.tipoContrato = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Operacion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *               &lt;enumeration value="7"/>
     *               &lt;enumeration value="8"/>
     *               &lt;enumeration value="9"/>
     *               &lt;enumeration value="10"/>
     *               &lt;enumeration value="11"/>
     *               &lt;enumeration value="12"/>
     *               &lt;enumeration value="13"/>
     *               &lt;enumeration value="14"/>
     *               &lt;enumeration value="15"/>
     *               &lt;enumeration value="16"/>
     *               &lt;enumeration value="17"/>
     *               &lt;enumeration value="18"/>
     *               &lt;enumeration value="19"/>
     *               &lt;enumeration value="20"/>
     *               &lt;enumeration value="21"/>
     *               &lt;enumeration value="22"/>
     *               &lt;enumeration value="23"/>
     *               &lt;enumeration value="24"/>
     *               &lt;enumeration value="25"/>
     *               &lt;enumeration value="26"/>
     *               &lt;enumeration value="27"/>
     *               &lt;enumeration value="28"/>
     *               &lt;enumeration value="29"/>
     *               &lt;enumeration value="30"/>
     *               &lt;enumeration value="31"/>
     *               &lt;enumeration value="32"/>
     *               &lt;enumeration value="33"/>
     *               &lt;enumeration value="34"/>
     *               &lt;enumeration value="35"/>
     *               &lt;enumeration value="36"/>
     *               &lt;enumeration value="37"/>
     *               &lt;enumeration value="38"/>
     *               &lt;enumeration value="39"/>
     *               &lt;enumeration value="40"/>
     *               &lt;enumeration value="41"/>
     *               &lt;enumeration value="42"/>
     *               &lt;enumeration value="43"/>
     *               &lt;enumeration value="44"/>
     *               &lt;enumeration value="45"/>
     *               &lt;enumeration value="46"/>
     *               &lt;enumeration value="47"/>
     *               &lt;enumeration value="48"/>
     *               &lt;enumeration value="49"/>
     *               &lt;enumeration value="50"/>
     *               &lt;enumeration value="51"/>
     *               &lt;enumeration value="52"/>
     *               &lt;enumeration value="53"/>
     *               &lt;enumeration value="54"/>
     *               &lt;enumeration value="55"/>
     *               &lt;enumeration value="56"/>
     *               &lt;enumeration value="57"/>
     *               &lt;enumeration value="58"/>
     *               &lt;enumeration value="59"/>
     *               &lt;enumeration value="60"/>
     *               &lt;enumeration value="61"/>
     *               &lt;enumeration value="62"/>
     *               &lt;enumeration value="63"/>
     *               &lt;enumeration value="64"/>
     *               &lt;enumeration value="65"/>
     *               &lt;enumeration value="66"/>
     *               &lt;enumeration value="67"/>
     *               &lt;enumeration value="68"/>
     *               &lt;enumeration value="69"/>
     *               &lt;enumeration value="70"/>
     *               &lt;enumeration value="71"/>
     *               &lt;enumeration value="72"/>
     *               &lt;enumeration value="73"/>
     *               &lt;enumeration value="74"/>
     *               &lt;enumeration value="75"/>
     *               &lt;enumeration value="76"/>
     *               &lt;enumeration value="77"/>
     *               &lt;enumeration value="78"/>
     *               &lt;enumeration value="79"/>
     *               &lt;enumeration value="80"/>
     *               &lt;enumeration value="81"/>
     *               &lt;enumeration value="82"/>
     *               &lt;enumeration value="83"/>
     *               &lt;enumeration value="84"/>
     *               &lt;enumeration value="85"/>
     *               &lt;enumeration value="86"/>
     *               &lt;enumeration value="87"/>
     *               &lt;enumeration value="88"/>
     *               &lt;enumeration value="89"/>
     *               &lt;enumeration value="90"/>
     *               &lt;enumeration value="91"/>
     *               &lt;enumeration value="92"/>
     *               &lt;enumeration value="93"/>
     *               &lt;enumeration value="94"/>
     *               &lt;enumeration value="95"/>
     *               &lt;enumeration value="100"/>
     *               &lt;enumeration value="101"/>
     *               &lt;enumeration value="102"/>
     *               &lt;enumeration value="104"/>
     *               &lt;enumeration value="105"/>
     *               &lt;enumeration value="106"/>
     *               &lt;enumeration value="107"/>
     *               &lt;enumeration value="108"/>
     *               &lt;enumeration value="109"/>
     *               &lt;enumeration value="110"/>
     *               &lt;enumeration value="111"/>
     *               &lt;enumeration value="112"/>
     *               &lt;enumeration value="113"/>
     *               &lt;enumeration value="114"/>
     *               &lt;enumeration value="115"/>
     *               &lt;enumeration value="116"/>
     *               &lt;enumeration value="117"/>
     *               &lt;enumeration value="118"/>
     *               &lt;enumeration value="119"/>
     *               &lt;enumeration value="120"/>
     *               &lt;enumeration value="121"/>
     *               &lt;enumeration value="122"/>
     *               &lt;enumeration value="123"/>
     *               &lt;enumeration value="124"/>
     *               &lt;enumeration value="125"/>
     *               &lt;enumeration value="126"/>
     *               &lt;enumeration value="129"/>
     *               &lt;enumeration value="130"/>
     *               &lt;enumeration value="131"/>
     *               &lt;enumeration value="138"/>
     *               &lt;enumeration value="139"/>
     *               &lt;enumeration value="140"/>
     *               &lt;enumeration value="142"/>
     *               &lt;enumeration value="145"/>
     *               &lt;enumeration value="147"/>
     *               &lt;enumeration value="148"/>
     *               &lt;enumeration value="149"/>
     *               &lt;enumeration value="150"/>
     *               &lt;enumeration value="151"/>
     *               &lt;enumeration value="153"/>
     *               &lt;enumeration value="154"/>
     *               &lt;enumeration value="155"/>
     *               &lt;enumeration value="156"/>
     *               &lt;enumeration value="157"/>
     *               &lt;enumeration value="158"/>
     *               &lt;enumeration value="160"/>
     *               &lt;enumeration value="161"/>
     *               &lt;enumeration value="162"/>
     *               &lt;enumeration value="163"/>
     *               &lt;enumeration value="164"/>
     *               &lt;enumeration value="165"/>
     *               &lt;enumeration value="168"/>
     *               &lt;enumeration value="170"/>
     *               &lt;enumeration value="171"/>
     *               &lt;enumeration value="173"/>
     *               &lt;enumeration value="174"/>
     *               &lt;enumeration value="175"/>
     *               &lt;enumeration value="176"/>
     *               &lt;enumeration value="177"/>
     *               &lt;enumeration value="180"/>
     *               &lt;enumeration value="181"/>
     *               &lt;enumeration value="183"/>
     *               &lt;enumeration value="184"/>
     *               &lt;enumeration value="187"/>
     *               &lt;enumeration value="188"/>
     *               &lt;enumeration value="300"/>
     *               &lt;enumeration value="301"/>
     *               &lt;enumeration value="302"/>
     *               &lt;enumeration value="303"/>
     *               &lt;enumeration value="401"/>
     *               &lt;enumeration value="402"/>
     *               &lt;enumeration value="403"/>
     *               &lt;enumeration value="500"/>
     *               &lt;enumeration value="501"/>
     *               &lt;enumeration value="502"/>
     *               &lt;enumeration value="503"/>
     *               &lt;enumeration value="504"/>
     *               &lt;enumeration value="505"/>
     *               &lt;enumeration value="506"/>
     *               &lt;enumeration value="507"/>
     *               &lt;enumeration value="508"/>
     *               &lt;enumeration value="509"/>
     *               &lt;enumeration value="510"/>
     *               &lt;enumeration value="511"/>
     *               &lt;enumeration value="512"/>
     *               &lt;enumeration value="513"/>
     *               &lt;enumeration value="514"/>
     *               &lt;enumeration value="515"/>
     *               &lt;enumeration value="1000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Datos_Operacion" type="{}Datos_Operacion_MercantilType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operacion",
        "datosOperacion"
    })
    public static class Mercantil {

        @XmlElement(name = "Operacion", required = true)
        protected String operacion;
        @XmlElement(name = "Datos_Operacion")
        protected DatosOperacionMercantilType datosOperacion;

        /**
         * Gets the value of the operacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperacion() {
            return operacion;
        }

        /**
         * Sets the value of the operacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperacion(String value) {
            this.operacion = value;
        }

        /**
         * Gets the value of the datosOperacion property.
         * 
         * @return
         *     possible object is
         *     {@link DatosOperacionMercantilType }
         *     
         */
        public DatosOperacionMercantilType getDatosOperacion() {
            return datosOperacion;
        }

        /**
         * Sets the value of the datosOperacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatosOperacionMercantilType }
         *     
         */
        public void setDatosOperacion(DatosOperacionMercantilType value) {
            this.datosOperacion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Operacion">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *               &lt;enumeration value="7"/>
     *               &lt;enumeration value="8"/>
     *               &lt;enumeration value="9"/>
     *               &lt;enumeration value="10"/>
     *               &lt;enumeration value="11"/>
     *               &lt;enumeration value="12"/>
     *               &lt;enumeration value="13"/>
     *               &lt;enumeration value="14"/>
     *               &lt;enumeration value="15"/>
     *               &lt;enumeration value="16"/>
     *               &lt;enumeration value="17"/>
     *               &lt;enumeration value="18"/>
     *               &lt;enumeration value="19"/>
     *               &lt;enumeration value="20"/>
     *               &lt;enumeration value="21"/>
     *               &lt;enumeration value="22"/>
     *               &lt;enumeration value="23"/>
     *               &lt;enumeration value="24"/>
     *               &lt;enumeration value="25"/>
     *               &lt;enumeration value="26"/>
     *               &lt;enumeration value="27"/>
     *               &lt;enumeration value="28"/>
     *               &lt;enumeration value="29"/>
     *               &lt;enumeration value="30"/>
     *               &lt;enumeration value="31"/>
     *               &lt;enumeration value="32"/>
     *               &lt;enumeration value="33"/>
     *               &lt;enumeration value="34"/>
     *               &lt;enumeration value="35"/>
     *               &lt;enumeration value="36"/>
     *               &lt;enumeration value="37"/>
     *               &lt;enumeration value="38"/>
     *               &lt;enumeration value="39"/>
     *               &lt;enumeration value="40"/>
     *               &lt;enumeration value="41"/>
     *               &lt;enumeration value="42"/>
     *               &lt;enumeration value="43"/>
     *               &lt;enumeration value="44"/>
     *               &lt;enumeration value="45"/>
     *               &lt;enumeration value="46"/>
     *               &lt;enumeration value="47"/>
     *               &lt;enumeration value="48"/>
     *               &lt;enumeration value="49"/>
     *               &lt;enumeration value="50"/>
     *               &lt;enumeration value="51"/>
     *               &lt;enumeration value="52"/>
     *               &lt;enumeration value="53"/>
     *               &lt;enumeration value="54"/>
     *               &lt;enumeration value="55"/>
     *               &lt;enumeration value="56"/>
     *               &lt;enumeration value="57"/>
     *               &lt;enumeration value="58"/>
     *               &lt;enumeration value="59"/>
     *               &lt;enumeration value="60"/>
     *               &lt;enumeration value="61"/>
     *               &lt;enumeration value="62"/>
     *               &lt;enumeration value="63"/>
     *               &lt;enumeration value="64"/>
     *               &lt;enumeration value="65"/>
     *               &lt;enumeration value="66"/>
     *               &lt;enumeration value="67"/>
     *               &lt;enumeration value="68"/>
     *               &lt;enumeration value="69"/>
     *               &lt;enumeration value="70"/>
     *               &lt;enumeration value="71"/>
     *               &lt;enumeration value="72"/>
     *               &lt;enumeration value="73"/>
     *               &lt;enumeration value="74"/>
     *               &lt;enumeration value="75"/>
     *               &lt;enumeration value="76"/>
     *               &lt;enumeration value="77"/>
     *               &lt;enumeration value="78"/>
     *               &lt;enumeration value="79"/>
     *               &lt;enumeration value="80"/>
     *               &lt;enumeration value="81"/>
     *               &lt;enumeration value="82"/>
     *               &lt;enumeration value="83"/>
     *               &lt;enumeration value="84"/>
     *               &lt;enumeration value="85"/>
     *               &lt;enumeration value="86"/>
     *               &lt;enumeration value="87"/>
     *               &lt;enumeration value="88"/>
     *               &lt;enumeration value="89"/>
     *               &lt;enumeration value="90"/>
     *               &lt;enumeration value="91"/>
     *               &lt;enumeration value="92"/>
     *               &lt;enumeration value="93"/>
     *               &lt;enumeration value="94"/>
     *               &lt;enumeration value="95"/>
     *               &lt;enumeration value="96"/>
     *               &lt;enumeration value="97"/>
     *               &lt;enumeration value="98"/>
     *               &lt;enumeration value="99"/>
     *               &lt;enumeration value="100"/>
     *               &lt;enumeration value="101"/>
     *               &lt;enumeration value="102"/>
     *               &lt;enumeration value="103"/>
     *               &lt;enumeration value="104"/>
     *               &lt;enumeration value="105"/>
     *               &lt;enumeration value="106"/>
     *               &lt;enumeration value="107"/>
     *               &lt;enumeration value="108"/>
     *               &lt;enumeration value="109"/>
     *               &lt;enumeration value="110"/>
     *               &lt;enumeration value="111"/>
     *               &lt;enumeration value="112"/>
     *               &lt;enumeration value="113"/>
     *               &lt;enumeration value="114"/>
     *               &lt;enumeration value="115"/>
     *               &lt;enumeration value="116"/>
     *               &lt;enumeration value="117"/>
     *               &lt;enumeration value="118"/>
     *               &lt;enumeration value="119"/>
     *               &lt;enumeration value="120"/>
     *               &lt;enumeration value="121"/>
     *               &lt;enumeration value="122"/>
     *               &lt;enumeration value="123"/>
     *               &lt;enumeration value="1000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operacion"
    })
    public static class Propiedad {

        @XmlElement(name = "Operacion", required = true)
        protected String operacion;

        /**
         * Gets the value of the operacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperacion() {
            return operacion;
        }

        /**
         * Sets the value of the operacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperacion(String value) {
            this.operacion = value;
        }

    }

}
