//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 01:31:28 PM CET 
//


package org.gestoresmadrid.oegamConversiones.jaxb.ctit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DATOS_SEGUNDO_COTITULAR")
public class DATOSSEGUNDOCOTITULAR {
	 @XmlElement(name = "DNI_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String dnisegundocotitulartransmitente;
	    @XmlElement(name = "SEXO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String sexosegundocotitulartransmitente;
	    @XmlElement(name = "APELLIDO1_RAZON_SOCIAL_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String apellido1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE;
	    @XmlElement(name = "APELLIDO2_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String apellido2SEGUNDOCOTITULARTRANSMITENTE;
	    @XmlElement(name = "NOMBRE_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String nombresegundocotitulartransmitente;
	    @XmlElement(name = "FECHA_NACIMIENTO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String fechanacimientosegundocotitulartransmitente;
	    @XmlElement(name = "TELEFONO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String telefonosegundocotitulartransmitente;
	    @XmlElement(name = "SIGLAS_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String siglasdireccionsegundocotitulartransmitente;
	    @XmlElement(name = "NOMBRE_VIA_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String nombreviadireccionsegundocotitulartransmitente;
	    @XmlElement(name = "NUMERO_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String numerodireccionsegundocotitulartransmitente;
	    @XmlElement(name = "LETRA_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String letradireccionsegundocotitulartransmitente;
	    @XmlElement(name = "ESCALERA_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String escaleradireccionsegundocotitulartransmitente;
	    @XmlElement(name = "PISO_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String pisodireccionsegundocotitulartransmitente;
	    @XmlElement(name = "PUERTA_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String puertadireccionsegundocotitulartransmitente;
	    @XmlElement(name = "PROVINCIA_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String provinciasegundocotitulartransmitente;
	    @XmlElement(name = "MUNICIPIO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String municipiosegundocotitulartransmitente;
	    @XmlElement(name = "PUEBLO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String pueblosegundocotitulartransmitente;
	    @XmlElement(name = "CP_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String cpsegundocotitulartransmitente;
	    @XmlElement(name = "BLOQUE_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String bloquedireccionsegundocotitulartransmitente;
	    @XmlElement(name = "KM_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String kmdireccionsegundocotitulartransmitente;
	    @XmlElement(name = "HM_DIRECCION_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String hmdireccionsegundocotitulartransmitente;
	    @XmlElement(name = "DIRECCION_ACTIVA_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String direccionactivasegundocotitulartransmitente;
	    @XmlElement(name = "FECHA_CADUCIDAD_NIF_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String fechacaducidadnifsegundocotitulartransmitente;
	    @XmlElement(name = "TIPO_DOCUMENTO_SUSTITUTIVO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String tipodocumentosustitutivosegundocotitulartransmitente;
	    @XmlElement(name = "FECHA_CADUCIDAD_DOCUMENTO_SUSTITUTIVO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String fechacaducidaddocumentosustitutivosegundocotitulartransmitente;
	    @XmlElement(name = "INDEFINIDO_SEGUNDO_COTITULAR_TRANSMITENTE")
	    protected String indefinidosegundocotitulartransmitente;
	    
	    public String getDNISEGUNDOCOTITULARTRANSMITENTE() {
	        return dnisegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the dnisegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setDNISEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.dnisegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the sexosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getSEXOSEGUNDOCOTITULARTRANSMITENTE() {
	        return sexosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the sexosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setSEXOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.sexosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the apellido1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getAPELLIDO1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE() {
	        return apellido1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE;
	    }

	    /**
	     * Sets the value of the apellido1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setAPELLIDO1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.apellido1RAZONSOCIALSEGUNDOCOTITULARTRANSMITENTE = value;
	    }

	    /**
	     * Gets the value of the apellido2SEGUNDOCOTITULARTRANSMITENTE property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getAPELLIDO2SEGUNDOCOTITULARTRANSMITENTE() {
	        return apellido2SEGUNDOCOTITULARTRANSMITENTE;
	    }

	    /**
	     * Sets the value of the apellido2SEGUNDOCOTITULARTRANSMITENTE property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setAPELLIDO2SEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.apellido2SEGUNDOCOTITULARTRANSMITENTE = value;
	    }

	    /**
	     * Gets the value of the nombresegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getNOMBRESEGUNDOCOTITULARTRANSMITENTE() {
	        return nombresegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the nombresegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setNOMBRESEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.nombresegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the fechanacimientosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getFECHANACIMIENTOSEGUNDOCOTITULARTRANSMITENTE() {
	        return fechanacimientosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the fechanacimientosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setFECHANACIMIENTOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.fechanacimientosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the telefonosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getTELEFONOSEGUNDOCOTITULARTRANSMITENTE() {
	        return telefonosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the telefonosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setTELEFONOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.telefonosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the siglasdireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getSIGLASDIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return siglasdireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the siglasdireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setSIGLASDIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.siglasdireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the nombreviadireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getNOMBREVIADIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return nombreviadireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the nombreviadireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setNOMBREVIADIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.nombreviadireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the numerodireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getNUMERODIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return numerodireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the numerodireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setNUMERODIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.numerodireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the letradireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getLETRADIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return letradireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the letradireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setLETRADIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.letradireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the escaleradireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getESCALERADIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return escaleradireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the escaleradireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setESCALERADIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.escaleradireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the pisodireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getPISODIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return pisodireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the pisodireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setPISODIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.pisodireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the puertadireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getPUERTADIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return puertadireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the puertadireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setPUERTADIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.puertadireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the provinciasegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getPROVINCIASEGUNDOCOTITULARTRANSMITENTE() {
	        return provinciasegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the provinciasegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setPROVINCIASEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.provinciasegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the municipiosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getMUNICIPIOSEGUNDOCOTITULARTRANSMITENTE() {
	        return municipiosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the municipiosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setMUNICIPIOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.municipiosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the pueblosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getPUEBLOSEGUNDOCOTITULARTRANSMITENTE() {
	        return pueblosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the pueblosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setPUEBLOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.pueblosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the cpsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getCPSEGUNDOCOTITULARTRANSMITENTE() {
	        return cpsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the cpsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setCPSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.cpsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the bloquedireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getBLOQUEDIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return bloquedireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the bloquedireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setBLOQUEDIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.bloquedireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the kmdireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getKMDIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return kmdireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the kmdireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setKMDIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.kmdireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the hmdireccionsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getHMDIRECCIONSEGUNDOCOTITULARTRANSMITENTE() {
	        return hmdireccionsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the hmdireccionsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setHMDIRECCIONSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.hmdireccionsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the direccionactivasegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getDIRECCIONACTIVASEGUNDOCOTITULARTRANSMITENTE() {
	        return direccionactivasegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the direccionactivasegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setDIRECCIONACTIVASEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.direccionactivasegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the fechacaducidadnifsegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getFECHACADUCIDADNIFSEGUNDOCOTITULARTRANSMITENTE() {
	        return fechacaducidadnifsegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the fechacaducidadnifsegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setFECHACADUCIDADNIFSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.fechacaducidadnifsegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the tipodocumentosustitutivosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getTIPODOCUMENTOSUSTITUTIVOSEGUNDOCOTITULARTRANSMITENTE() {
	        return tipodocumentosustitutivosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the tipodocumentosustitutivosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setTIPODOCUMENTOSUSTITUTIVOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.tipodocumentosustitutivosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the fechacaducidaddocumentosustitutivosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getFECHACADUCIDADDOCUMENTOSUSTITUTIVOSEGUNDOCOTITULARTRANSMITENTE() {
	        return fechacaducidaddocumentosustitutivosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the fechacaducidaddocumentosustitutivosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setFECHACADUCIDADDOCUMENTOSUSTITUTIVOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.fechacaducidaddocumentosustitutivosegundocotitulartransmitente = value;
	    }

	    /**
	     * Gets the value of the indefinidosegundocotitulartransmitente property.
	     * 
	     * @return
	     *     possible object is
	     *     {@link String }
	     *     
	     */
	    public String getINDEFINIDOSEGUNDOCOTITULARTRANSMITENTE() {
	        return indefinidosegundocotitulartransmitente;
	    }

	    /**
	     * Sets the value of the indefinidosegundocotitulartransmitente property.
	     * 
	     * @param value
	     *     allowed object is
	     *     {@link String }
	     *     
	     */
	    public void setINDEFINIDOSEGUNDOCOTITULARTRANSMITENTE(String value) {
	        this.indefinidosegundocotitulartransmitente = value;
	    }
   
}
