//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 09:29:59 AM CET 
//


package org.gestoresmadrid.oegamConversiones.jaxb.ctit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.gestoresmadrid.oegamConversiones.jaxb.matw.TipoMotivoTutela;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DATOS_REPRESENTANTE_SEGUNDO_COTITULAR")
public class DATOSREPRESENTANTETSEGUNDOCOTITULAR {


    @XmlElement(name = "DNI_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String dnirepresentantesegundocotitular;
    @XmlElement(name = "SEXO_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String sexorepresentantesegundocotitular;
    @XmlElement(name = "APELLIDO1_RAZON_SOCIAL_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String apellido1RAZONSOCIALREPRESENTANTESEGUNDOCOTITULAR;
    @XmlElement(name = "APELLIDO2_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String apellido2REPRESENTANTESEGUNDOCOTITULAR;
    @XmlElement(name = "NOMBRE_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String nombrerepresentantesegundocotitular;
    @XmlElement(name = "CONCEPTO_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String conceptorepresentantesegundocotitular;
    @XmlElement(name = "DOCUMENTOS_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String documentosrepresentantesegundocotitular;
    @XmlElement(name = "FECHA_CADUCIDAD_NIF_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String fechacaducidadnifrepresentantesegundocotitular;
    @XmlElement(name = "TIPO_DOCUMENTO_SUSTITUTIVO_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String tipodocumentosustitutivorepresentantesegundocotitular;
    @XmlElement(name = "FECHA_CADUCIDAD_DOCUMENTO_SUSTITUTIVO_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String fechacaducidaddocumentosustitutivorepresentantesegundocotitular;
    @XmlElement(name = "INDEFINIDO_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected String indefinidorepresentantesegundocotitular;
    @XmlElement(name = "MOTIVO_TUTELA_REPRESENTANTE_SEGUNDO_COTITULAR")
    protected TipoMotivoTutela motivotutelarepresentantesegundocotitular;
    @XmlElement(name = "FECHA_INICIO_TUTELA_SEGUNDO_COTITULAR")
    protected String fechainiciotutelasegundocotitular;
    @XmlElement(name = "FECHA_FIN_TUTELA_SEGUNDO_COTITULAR")
    protected String fechafintutelasegundocotitular;
    /**
     * Gets the value of the dnirepresentanteadquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNIREPRESENTANTESEGUNDOCOTITULAR() {
        return dnirepresentantesegundocotitular;
    }

    /**
     * Sets the value of the dnirepresentanteadquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNIREPRESENTANTESEGUNDOCOTITULAR(String value) {
        this.dnirepresentantesegundocotitular = value;
    }

    /**
     * Gets the value of the sexorepresentanteadquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEXOREPRESENTANTESEGUNDOCOTITULAR() {
        return sexorepresentantesegundocotitular;
    }

    /**
     * Sets the value of the sexorepresentanteadquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEXOREPRESENTANTESEGUNDOCOTITULAR(String value) {
        this.sexorepresentantesegundocotitular = value;
    }

    /**
     * Gets the value of the apellido1RAZONSOCIALREPRESENTANTEADQUIRIENTE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPELLIDO1RAZONSOCIALREPRESENTANTESEGUNDOCOTITULAR() {
        return apellido1RAZONSOCIALREPRESENTANTESEGUNDOCOTITULAR;
    }

    /**
     * Sets the value of the apellido1RAZONSOCIALREPRESENTANTEADQUIRIENTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPELLIDO1RAZONSOCIALREPRESENTANTESEGUNDOCOTITULAR(String value) {
        this.apellido1RAZONSOCIALREPRESENTANTESEGUNDOCOTITULAR = value;
    }

    /**
     * Gets the value of the apellido2REPRESENTANTEADQUIRIENTE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPELLIDO2REPRESENTANTESEGUNDOCOTITULAR() {
        return apellido2REPRESENTANTESEGUNDOCOTITULAR;
    }

    /**
     * Sets the value of the apellido2REPRESENTANTEADQUIRIENTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPELLIDO2REPRESENTANTESEGUNDOCOTITULAR(String value) {
        this.apellido2REPRESENTANTESEGUNDOCOTITULAR = value;
    }

    /**
     * Gets the value of the nombrerepresentanteadquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMBREREPRESENTANTESEGUNDOCOTITULAR() {
        return nombrerepresentantesegundocotitular;
    }

    /**
     * Sets the value of the nombrerepresentanteadquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMBREREPRESENTANTESEGUNDOCOTITULAR(String value) {
        this.nombrerepresentantesegundocotitular = value;
    }

    /**
     * Gets the value of the conceptorepresentanteadquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONCEPTOREPRESENTANTESEGUNDOCOTITULAR() {
        return conceptorepresentantesegundocotitular;
    }

    /**
     * Sets the value of the conceptorepresentanteadquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONCEPTOREPRESENTANTESEGUNDOCOTITULAR(String value) {
        this.conceptorepresentantesegundocotitular = value;
    }

  
  
   
   /**
    * Gets the value of the motivorepresentanteadquiriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public TipoMotivoTutela getMOTIVOTUTELAREPRESENTANTESEGUNDOCOTITULAR() {
       return motivotutelarepresentantesegundocotitular;
   }

   /**
    * Sets the value of the motivorepresentanteadquiriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setMOTIVOTUTELAREPRESENTANTESEGUNDOCOTITULAR(TipoMotivoTutela value) {
       this.motivotutelarepresentantesegundocotitular = value;
   }

   /**
    * Gets the value of the fechainiciotutelaadquieriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getFECHAINICIOTUTELASEGUNDOCOTITULAR() {
       return fechainiciotutelasegundocotitular;
   }

   /**
    * Sets the value of the fechainiciotutelaadquieriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setFECHAINICIOTUTELASEGUNDOCOTITULAR(String value) {
       this.fechainiciotutelasegundocotitular = value;
   }

   /**
    * Gets the value of the fechafintutelaadquieriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getFECHAFINTUTELASEGUNDOCOTITULAR() {
       return fechafintutelasegundocotitular;
   }

   /**
    * Sets the value of the fechafintutelaadquieriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setFECHAFINTUTELASEGUNDOCOTITULAR(String value) {
       this.fechafintutelasegundocotitular = value;
   }

   /**
    * Gets the value of the documentosrepresentanteadquiriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getDOCUMENTOSREPRESENTANTESEGUNDOCOTITULAR() {
       return documentosrepresentantesegundocotitular;
   }

   /**
    * Sets the value of the documentosrepresentanteadquiriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setDOCUMENTOSREPRESENTANTESEGUNDOCOTITULAR(String value) {
       this.documentosrepresentantesegundocotitular = value;
   }

   /**
    * Gets the value of the fechacaducidadnifrepresentanteadquiriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getFECHACADUCIDADNIFREPRESENTANTESEGUNDOCOTITULAR() {
       return fechacaducidadnifrepresentantesegundocotitular;
   }

   /**
    * Sets the value of the fechacaducidadnifrepresentanteadquiriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setFECHACADUCIDADNIFREPRESENTANTESEGUNDOCOTITULAR(String value) {
       this.fechacaducidadnifrepresentantesegundocotitular = value;
   }

   /**
    * Gets the value of the tipodocumentosustitutivorepresentanteadquiriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getTIPODOCUMENTOSUSTITUTIVOREPRESENTANTESEGUNDOCOTITULAR() {
       return tipodocumentosustitutivorepresentantesegundocotitular;
   }

   /**
    * Sets the value of the tipodocumentosustitutivorepresentanteadquiriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setTIPODOCUMENTOSUSTITUTIVOREPRESENTANTESEGUNDOCOTITULAR(String value) {
       this.tipodocumentosustitutivorepresentantesegundocotitular = value;
   }

   /**
    * Gets the value of the fechacaducidaddocumentosustitutivorepresentanteadquiriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getFECHACADUCIDADDOCUMENTOSUSTITUTIVOREPRESENTANTESEGUNDOCOTITULAR() {
       return fechacaducidaddocumentosustitutivorepresentantesegundocotitular;
   }

   /**
    * Sets the value of the fechacaducidaddocumentosustitutivorepresentanteadquiriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setFECHACADUCIDADDOCUMENTOSUSTITUTIVOREPRESENTANTESEGUNDOCOTITULAR(String value) {
       this.fechacaducidaddocumentosustitutivorepresentantesegundocotitular = value;
   }

   /**
    * Gets the value of the indefinidorepresentanteadquiriente property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getINDEFINIDOREPRESENTANTESEGUNDOCOTITULAR() {
       return indefinidorepresentantesegundocotitular;
   }

   /**
    * Sets the value of the indefinidorepresentanteadquiriente property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setINDEFINIDOREPRESENTANTESEGUNDOCOTITULAR(String value) {
       this.indefinidorepresentantesegundocotitular = value;
   }
    
}
