//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.14 at 09:14:20 AM CET 
//


package org.gestoresmadrid.oegam2comun.modelo601.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expAbreviadaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="expAbreviadaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AJ0"/>
 *     &lt;enumeration value="AMP"/>
 *     &lt;enumeration value="AP0"/>
 *     &lt;enumeration value="CH1"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="DN0"/>
 *     &lt;enumeration value="DN1"/>
 *     &lt;enumeration value="DN2"/>
 *     &lt;enumeration value="DN3"/>
 *     &lt;enumeration value="DN4"/>
 *     &lt;enumeration value="DN5"/>
 *     &lt;enumeration value="DN6"/>
 *     &lt;enumeration value="ECO"/>
 *     &lt;enumeration value="HUN"/>
 *     &lt;enumeration value="NBA"/>
 *     &lt;enumeration value="NOV"/>
 *     &lt;enumeration value="PH1"/>
 *     &lt;enumeration value="PH2"/>
 *     &lt;enumeration value="PH3"/>
 *     &lt;enumeration value="PH4"/>
 *     &lt;enumeration value="POS"/>
 *     &lt;enumeration value="PRO"/>
 *     &lt;enumeration value="RED"/>
 *     &lt;enumeration value="RE1"/>
 *     &lt;enumeration value="SGR"/>
 *     &lt;enumeration value="VP1"/>
 *     &lt;enumeration value="VP2"/>
 *     &lt;enumeration value="VT1"/>
 *     &lt;enumeration value="VT2"/>
 *     &lt;enumeration value="VT3"/>
 *     &lt;enumeration value="VT4"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "expAbreviadaType")
@XmlEnum
public enum ExpAbreviadaType {

    @XmlEnumValue("AJ0")
    AJ_0("AJ0"),
    AMP("AMP"),
    @XmlEnumValue("AP0")
    AP_0("AP0"),
    @XmlEnumValue("CH1")
    CH_1("CH1"),
    CON("CON"),
    @XmlEnumValue("DN0")
    DN_0("DN0"),
    @XmlEnumValue("DN1")
    DN_1("DN1"),
    @XmlEnumValue("DN2")
    DN_2("DN2"),
    @XmlEnumValue("DN3")
    DN_3("DN3"),
    @XmlEnumValue("DN4")
    DN_4("DN4"),
    @XmlEnumValue("DN5")
    DN_5("DN5"),
    @XmlEnumValue("DN6")
    DN_6("DN6"),
    ECO("ECO"),
    HUN("HUN"),
    NBA("NBA"),
    NOV("NOV"),
    @XmlEnumValue("PH1")
    PH_1("PH1"),
    @XmlEnumValue("PH2")
    PH_2("PH2"),
    @XmlEnumValue("PH3")
    PH_3("PH3"),
    @XmlEnumValue("PH4")
    PH_4("PH4"),
    POS("POS"),
    PRO("PRO"),
    RED("RED"),
    @XmlEnumValue("RE1")
    RE_1("RE1"),
    SGR("SGR"),
    @XmlEnumValue("VP1")
    VP_1("VP1"),
    @XmlEnumValue("VP2")
    VP_2("VP2"),
    @XmlEnumValue("VT1")
    VT_1("VT1"),
    @XmlEnumValue("VT2")
    VT_2("VT2"),
    @XmlEnumValue("VT3")
    VT_3("VT3"),
    @XmlEnumValue("VT4")
    VT_4("VT4");
    private final String value;

    ExpAbreviadaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExpAbreviadaType fromValue(String v) {
        for (ExpAbreviadaType c: ExpAbreviadaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
