//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 09:41:02 AM CET 
//


package es.map.scsp.esquemas.datosespecificos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import es.munimadrid.iam.ws.ErroresType;


/**
 * <p>Java class for DatosEspecificosModificacionProyectoIVTMRespuesta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosEspecificosModificacionProyectoIVTMRespuesta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}numautoliquidacion"/>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}emisor"/>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}importeanual"/>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}importe"/>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}digitos"/>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}codgestor"/>
 *         &lt;element ref="{http://ws.iam.munimadrid.es}errores"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosEspecificosModificacionProyectoIVTMRespuesta", propOrder = {
    "numautoliquidacion",
    "emisor",
    "importeanual",
    "importe",
    "digitos",
    "codgestor",
    "errores"
})
public class DatosEspecificosModificacionProyectoIVTMRespuesta {

    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected String numautoliquidacion;
    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected String emisor;
    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected String importeanual;
    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected String importe;
    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected String digitos;
    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected String codgestor;
    @XmlElement(namespace = "http://ws.iam.munimadrid.es", required = true)
    protected ErroresType errores;

    /**
     * Gets the value of the numautoliquidacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumautoliquidacion() {
        return numautoliquidacion;
    }

    /**
     * Sets the value of the numautoliquidacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumautoliquidacion(String value) {
        this.numautoliquidacion = value;
    }

    /**
     * Gets the value of the emisor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmisor() {
        return emisor;
    }

    /**
     * Sets the value of the emisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmisor(String value) {
        this.emisor = value;
    }

    /**
     * Gets the value of the importeanual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteanual() {
        return importeanual;
    }

    /**
     * Sets the value of the importeanual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteanual(String value) {
        this.importeanual = value;
    }

    /**
     * Gets the value of the importe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporte() {
        return importe;
    }

    /**
     * Sets the value of the importe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporte(String value) {
        this.importe = value;
    }

    /**
     * Gets the value of the digitos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitos() {
        return digitos;
    }

    /**
     * Sets the value of the digitos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitos(String value) {
        this.digitos = value;
    }

    /**
     * Gets the value of the codgestor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodgestor() {
        return codgestor;
    }

    /**
     * Sets the value of the codgestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodgestor(String value) {
        this.codgestor = value;
    }

    /**
     * Gets the value of the errores property.
     * 
     * @return
     *     possible object is
     *     {@link ErroresType }
     *     
     */
    public ErroresType getErrores() {
        return errores;
    }

    /**
     * Sets the value of the errores property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErroresType }
     *     
     */
    public void setErrores(ErroresType value) {
        this.errores = value;
    }

}
