function actualizarPadre(idDireccion, idProvincia, idMunicipio, idTipoVia, nombreVia, numero, pueblo, codPostal, puebloCorreos, codPostalCorreos, letra, escalera,
		bloque, puerta, planta, km, hm, idDireccion, pestania) {
	if (pestania=="TitularBaja" || pestania=="TitularDuplicado") {
		window.opener.document.formData.idDireccionTitular.value = idDireccion;
		window.opener.document.formData.idProvinciaTitular.value = idProvincia;
		window.opener.document.formData.idMunicipioTitular.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoTitular.value = idMunicipio;
		window.opener.document.formData.idPuebloTitular.value = pueblo;
		window.opener.document.formData.puebloSeleccionadoTitular.value = pueblo;
		window.opener.document.formData.cpTitular.value = codPostal;
		window.opener.document.formData.tipoViaTitular.value = idTipoVia;
		window.opener.document.formData.nombreViaTitular.value = nombreVia;
		window.opener.document.formData.numeroDireccionTitular.value = numero;
		window.opener.document.formData.letraDireccionTitular.value = letra;
		window.opener.document.formData.escaleraDireccionTitular.value = escalera;
		window.opener.document.formData.bloqueDireccionTitular.value = bloque;
		window.opener.document.formData.puertaDireccionTitular.value = puerta;
		window.opener.document.formData.pisoDireccionTitular.value = planta;
		window.opener.document.formData.kmDireccionTitular.value = km;
		window.opener.document.formData.hmDireccionTitular.value = hm;
		if (pestania=="TitularBaja") {
			window.opener.document.formData.idHiddenDireccionTitularBaja.value = idDireccion;
		} else if (pestania=="TitularDuplicado") {
			window.opener.document.formData.idHiddenDireccionTitularDuplicado.value = idDireccion;
		}
		window.opener.recargarComboMunicipios('idProvinciaTitular','idMunicipioTitular','municipioSeleccionadoTitular');
		window.opener.recargarComboPueblos('idProvinciaTitular','municipioSeleccionadoTitular','idPuebloTitular', 'puebloSeleccionadoTitular');
	} else if (pestania=="AdquirienteBaja") {
		window.opener.document.formData.idDireccionAdquiriente.value = idDireccion;
		window.opener.document.formData.idProvinciaAdquiriente.value = idProvincia;
		window.opener.document.formData.idMunicipioAdquiriente.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoAdquiriente.value = idMunicipio;
		window.opener.document.formData.puebloSeleccionadoAdquiriente.value = pueblo;
		window.opener.document.formData.idPuebloAdquiriente.value = pueblo;
		window.opener.document.formData.cpAdquiriente.value = codPostal;
		window.opener.document.formData.tipoViaAdquiriente.value = idTipoVia;
		window.opener.document.formData.nombreViaAdquiriente.value = nombreVia;
		window.opener.document.formData.numeroDireccionAdquiriente.value = numero;
		window.opener.document.formData.letraDireccionAdquiriente.value = letra;
		window.opener.document.formData.escaleraDireccionAdquiriente.value = escalera;
		window.opener.document.formData.pisoDireccionAdquiriente.value = planta;
		window.opener.document.formData.puertaDireccionAdquiriente.value = puerta;
		window.opener.document.formData.bloqueDireccionAdquiriente.value = bloque;
		window.opener.document.formData.kmDireccionAdquiriente.value = km;
		window.opener.document.formData.hmDireccionAdquiriente.value = hm;
		window.opener.document.formData.idHiddenDireccionAdquirienteBaja.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaAdquiriente','idMunicipioAdquiriente','municipioSeleccionadoAdquiriente');
		window.opener.recargarComboPueblos('idProvinciaAdquiriente','municipioSeleccionadoAdquiriente','idPuebloAdquiriente', 'puebloSeleccionadoAdquiriente');
	} else if (pestania=="TitularJustificante") {
		window.opener.document.formData.idProvinciaAdquiriente.value = idProvincia;
		window.opener.document.formData.idMunicipioAdquiriente.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoAdquiriente.value = idMunicipio;
		window.opener.document.formData.idPuebloAdquiriente.value = pueblo;
		window.opener.document.formData.puebloSeleccionadoAdquiriente.value = pueblo;
		window.opener.document.formData.codPostalAdquiriente.value = codPostal;
		window.opener.document.formData.tipoViaAdquiriente.value = idTipoVia;
		window.opener.document.formData.viaAdquiriente.value = nombreVia;
		window.opener.document.formData.numeroAdquiriente.value = numero;
		window.opener.document.formData.letraAdquiriente.value = letra;
		window.opener.document.formData.escaleraAdquiriente.value = escalera;
		window.opener.document.formData.pisoAdquiriente.value = planta;
		window.opener.document.formData.puertaAdquiriente.value = puerta;
		window.opener.document.formData.bloqueAdquiriente.value = bloque;
		window.opener.document.formData.kmAdquiriente.value = km;
		window.opener.document.formData.hmAdquiriente.value = hm;
		window.opener.document.formData.idDireccionAdquiriente.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaAdquiriente','idMunicipioAdquiriente','municipioSeleccionadoAdquiriente');
		window.opener.recargarComboPueblos('idProvinciaAdquiriente','municipioSeleccionadoAdquiriente','idPuebloAdquiriente', 'puebloSeleccionadoAdquiriente');
	} else if (pestania=="TitularMatriculacion") {
		window.opener.document.formData.idProvinciaTitular.value = idProvincia;
		window.opener.document.formData.idMunicipioTitular.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoTitular.value = idMunicipio;
		window.opener.document.formData.idPuebloTitular.value = puebloCorreos;
		window.opener.document.formData.puebloSeleccionadoTitular.value = puebloCorreos;
		window.opener.document.formData.codPostalTitular.value = codPostalCorreos;
		window.opener.document.formData.tipoViaDireccionTitular.value = idTipoVia;
		window.opener.document.formData.nombreViaDireccionTitular.value = nombreVia;
		window.opener.document.formData.numeroDireccionTitular.value = numero;
		window.opener.document.formData.letraDireccionTitular.value = letra;
		window.opener.document.formData.escaleraDireccionTitular.value = escalera;
		window.opener.document.formData.pisoDireccionTitular.value = planta;
		window.opener.document.formData.puertaDireccionTitular.value = puerta;
		window.opener.document.formData.bloqueDireccionTitular.value = bloque;
		window.opener.document.formData.kmDireccionTitular.value = km;
		window.opener.document.formData.hmDireccionTitular.value = hm;
		window.opener.document.formData.idDireccionTitular.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaTitular','idMunicipioTitular','municipioSeleccionadoTitular');
		window.opener.recargarComboLocalidadesDGT('idProvinciaTitular','municipioSeleccionadoTitular','idPuebloTitular', 'puebloSeleccionadoTitular');
	} else if (pestania=="RepresentanteTitularMatriculacion") {
		window.opener.document.formData.idProvinciaRepresentante.value = idProvincia;
		window.opener.document.formData.idMunicipioRepresentante.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoRepresentante.value = idMunicipio;
		window.opener.document.formData.idPuebloRepresentante.value = puebloCorreos;
		window.opener.document.formData.puebloSeleccionadoRepresentante.value = puebloCorreos;
		window.opener.document.formData.codPostalRepresentante.value = codPostalCorreos;
		window.opener.document.formData.tipoViaRepresentanteTitular.value = idTipoVia;
		window.opener.document.formData.nombreViaRepresentanteTitular.value = nombreVia;
		window.opener.document.formData.numeroDireccionRepresentanteTitular.value = numero;
		window.opener.document.formData.letraDireccionRepresentanteTitular.value = letra;
		window.opener.document.formData.escaleraDireccionRepresentanteTitular.value = escalera;
		window.opener.document.formData.pisoDireccionRepresentanteTitular.value = planta;
		window.opener.document.formData.puertaDireccionRepresentanteTitular.value = puerta;
		window.opener.document.formData.bloqueDireccionRepresentanteTitular.value = bloque;
		window.opener.document.formData.kmDireccionRepresentanteTitular.value = km;
		window.opener.document.formData.hmDireccionRepresentanteTitular.value = hm;
		window.opener.document.formData.idDireccionRepresentanteTitular.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaTitular','idMunicipioTitular','municipioSeleccionadoTitular');
		window.opener.recargarComboLocalidadesDGT('idProvinciaTitular','municipioSeleccionadoTitular','idPuebloTitular', 'puebloSeleccionadoTitular');
	} else if (pestania=="ConductorHabitual") {
		window.opener.document.formData.idProvinciaConductorHabitual.value = idProvincia;
		window.opener.document.formData.idMunicipioConductorHabitual.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoConductorHabitual.value = idMunicipio;
		window.opener.document.formData.idPuebloConductorHabitual.value = puebloCorreos;
		window.opener.document.formData.puebloSeleccionadoConductorHabitual.value = puebloCorreos;
		window.opener.document.formData.codPostalConductorHabitual.value = codPostalCorreos;
		window.opener.document.formData.tipoViaDireccionConductorHabitual.value = idTipoVia;
		window.opener.document.formData.nombreViaDireccionConductorHabitual.value = nombreVia;
		window.opener.document.formData.numeroDireccionConductorHabitual.value = numero;
		window.opener.document.formData.letraDireccionConductorHabitual.value = letra;
		window.opener.document.formData.escaleraDireccionConductorHabitual.value = escalera;
		window.opener.document.formData.pisoDireccionConductorHabitual.value = planta;
		window.opener.document.formData.puertaDireccionConductorHabitual.value = puerta;
		window.opener.document.formData.bloqueDireccionConductorHabitual.value = bloque;
		window.opener.document.formData.kmDireccionConductorHabitual.value = km;
		window.opener.document.formData.hmDireccionConductorHabitual.value = hm;
		window.opener.document.formData.idDireccionConductorHabitual.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaConductorHabitual','idMunicipioConductorHabitual','municipioSeleccionadoConductorHabitual');
		window.opener.recargarComboLocalidadesDGT('idProvinciaConductorHabitual','municipioSeleccionadoConductorHabitual','idPuebloConductorHabitual', 'puebloSeleccionadoConductorHabitual');
	} else if (pestania=="Renting") {
		window.opener.document.formData.idProvinciaRenting.value = idProvincia;
		window.opener.document.formData.idMunicipioRenting.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoRenting.value = idMunicipio;
		window.opener.document.formData.idPuebloRenting.value = puebloCorreos;
		window.opener.document.formData.puebloSeleccionadoRenting.value = puebloCorreos;
		window.opener.document.formData.codPostalRenting.value = codPostalCorreos;
		window.opener.document.formData.tipoViaDireccionRenting.value = idTipoVia;
		window.opener.document.formData.nombreViaDireccionRenting.value = nombreVia;
		window.opener.document.formData.numeroDireccionRenting.value = numero;
		window.opener.document.formData.letraDireccionRenting.value = letra;
		window.opener.document.formData.escaleraDireccionRenting.value = escalera;
		window.opener.document.formData.pisoDireccionRenting.value = planta;
		window.opener.document.formData.puertaDireccionRenting.value = puerta;
		window.opener.document.formData.bloqueDireccionRenting.value = bloque;
		window.opener.document.formData.kmDireccionRenting.value = km;
		window.opener.document.formData.hmDireccionRenting.value = hm;
		window.opener.document.formData.idDireccionAdminRenMatr.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaRenting','idMunicipioRenting','municipioSeleccionadoRenting');
		window.opener.recargarComboLocalidadesDGT('idProvinciaRenting','municipioSeleccionadoRenting','idPuebloRenting', 'puebloSeleccionadoRenting');
	} else if (pestania=="Destinatario") {
		window.opener.document.formData.idDireccionDestinatario.value = idDireccion;
		window.opener.document.formData.idProvinciaDestinatario.value = idProvincia;
		window.opener.document.formData.idMunicipioDestinatario.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoDestinatario.value = idMunicipio;
		window.opener.document.formData.codPostalDestinatario.value = codPostal;
		window.opener.document.formData.tipoViaDestinatario.value = idTipoVia;
		window.opener.document.formData.nombreViaDestinatario.value = nombreVia;
		window.opener.document.formData.numeroDestinatario.value = numero;
		window.opener.document.formData.escaleraDestinatario.value = escalera;
		window.opener.document.formData.plantaDestinatario.value = piso;
		window.opener.document.formData.puertaDestinatario.value = puerta;
		window.opener.recargarComboMunicipios('idProvinciaDestinatario','idMunicipioDestinatario','municipioSeleccionadoDestinatario');
	} else if (pestania=="CotitularDuplicado") {
		window.opener.document.formData.idDireccionCotitular.value = idDireccion;
		window.opener.document.formData.idProvinciaCotitular.value = idProvincia;
		window.opener.document.formData.idMunicipioCotitular.value = idMunicipio;
		window.opener.document.formData.municipioSeleccionadoCotitular.value = idMunicipio;
		window.opener.document.formData.idPuebloCotitular.value = pueblo;
		window.opener.document.formData.puebloSeleccionadoCotitular.value = pueblo;
		window.opener.document.formData.cpCotitular.value = codPostal;
		window.opener.document.formData.tipoViaCotitular.value = idTipoVia;
		window.opener.document.formData.nombreViaCotitular.value = nombreVia;
		window.opener.document.formData.numeroDireccionCotitular.value = numero;
		window.opener.document.formData.letraDireccionCotitular.value = letra;
		window.opener.document.formData.escaleraDireccionCotitular.value = escalera;
		window.opener.document.formData.bloqueDireccionCotitular.value = bloque;
		window.opener.document.formData.puertaDireccionCotitular.value = puerta;
		window.opener.document.formData.pisoDireccionCotitular.value = planta;
		window.opener.document.formData.kmDireccionCotitular.value = km;
		window.opener.document.formData.hmDireccionCotitular.value = hm;
		window.opener.document.formData.idHiddenDireccionCotitularDuplicado.value = idDireccion;
		window.opener.recargarComboMunicipios('idProvinciaCotitular','idMunicipioCotitular','municipioSeleccionadoCotitular');
		window.opener.recargarComboPueblos('idProvinciaCotitular','municipioSeleccionadoCotitular','idPuebloCotitular', 'puebloSeleccionadoCotitular');
	}
	window.close();
}