### logger para correo oegam ###
log4j.rootCategory=ALL,ARCHIVO

### Para dirigir los mensajes a un archivo ###
log4j.appender.ARCHIVO=org.apache.log4j.FileAppender
log4j.appender.ARCHIVO.File=/var/datos/logs/loging.log
log4j.appender.ARCHIVO.layout=org.apache.log4j.PatternLayout
##log4j.appender.ARCHIVO.layout.ConversionPattern=%d{ABSOLUTE} %5p %c{1}:%L - %m%n
log4j.appender.ARCHIVO.layout.ConversionPattern=%d{dd/MM HH:mm:ss} [%-5p]%m%n
log4j.appender.ARCHIVO.MaxFileSize=5000KB
log4j.appender.ARCHIVO.MaxBackupIndex=5

log4j.logger.org.oegam.gestorcorreos.services.GestorCorreo=ALL,CORREO
log4j.appender.CORREO=org.apache.log4j.FileAppender
log4j.appender.CORREO.File=/var/datos/logs/correoOegam.log
log4j.appender.CORREO.layout=org.apache.log4j.PatternLayout
log4j.appender.CORREO.layout.ConversionPattern=%d{dd/MM HH:mm:ss} [%-5p]%m%n
log4j.appender.CORREO.MaxFileSize=5000KB
log4j.appender.CORREO.MaxBackupIndex=5

log4j.logger.org.oegam.gestorcorreos.services.GestorCorreoDuplicados=ALL,DUPLICADOS
log4j.appender.DUPLICADOS=org.apache.log4j.FileAppender
log4j.appender.DUPLICADOS.File=/var/datos/logs/correoOegamDuplicados.log
log4j.appender.DUPLICADOS.layout=org.apache.log4j.PatternLayout
log4j.appender.DUPLICADOS.layout.ConversionPattern=%d{dd/MM HH:mm:ss} [%-5p]%m%n
log4j.appender.DUPLICADOS.MaxFileSize=5000KB
log4j.appender.DUPLICADOS.MaxBackupIndex=5

log4j.logger.org.oegam.gestorcorreos.services.GestorCorreoBajas=ALL,BAJAS
log4j.appender.BAJAS=org.apache.log4j.FileAppender
log4j.appender.BAJAS.File=/var/datos/logs/correoOegamBajas.log
log4j.appender.BAJAS.layout=org.apache.log4j.PatternLayout
log4j.appender.BAJAS.layout.ConversionPattern=%d{dd/MM HH:mm:ss} [%-5p]%m%n
log4j.appender.BAJAS.MaxFileSize=5000KB
log4j.appender.BAJAS.MaxBackupIndex=5

log4j.logger.org.oegam.gestorcorreos.services.GestorCorreoNotificacionesEni=ALL,NOTIFICACIONESENI
log4j.appender.NOTIFICACIONESENI=org.apache.log4j.FileAppender
log4j.appender.NOTIFICACIONESENI.File=/var/datos/logs/correoOegamNotificacionesEni.log
log4j.appender.NOTIFICACIONESENI.layout=org.apache.log4j.PatternLayout
log4j.appender.NOTIFICACIONESENI.layout.ConversionPattern=%d{dd/MM HH:mm:ss} [%-5p]%m%n
log4j.appender.NOTIFICACIONESENI.MaxFileSize=5000KB
log4j.appender.NOTIFICACIONESENI.MaxBackupIndex=5