//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 09:29:59 AM CET 
//


package org.gestoresmadrid.oegamConversiones.jaxb.baja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}DNI_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}SEXO_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}APELLIDO1_RAZON_SOCIAL_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}APELLIDO2_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}NOMBRE_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}FECHA_NACIMIENTO_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}PROVINCIA_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}MUNICIPIO_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}PUEBLO_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}CODIGO_POSTAL_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}TIPO_VIA_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}CALLE_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}NUMERO_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}LETRA_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}ESCALERA_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}PISO_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}PUERTA_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}BLOQUE_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}KM_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}HM_DIRECCION_TITULAR" minOccurs="0"/>
 *         &lt;element ref="{}DIRECCION_ACTIVA_TITULAR" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DATOS_TITULAR")
public class DATOSTITULAR {

    @XmlElement(name = "DNI_TITULAR")
    protected String dnititular;
    @XmlElement(name = "SEXO_TITULAR")
    protected String sexotitular;
    @XmlElement(name = "APELLIDO1_RAZON_SOCIAL_TITULAR")
    protected String apellido1RAZONSOCIALTITULAR;
    @XmlElement(name = "APELLIDO2_TITULAR")
    protected String apellido2TITULAR;
    @XmlElement(name = "NOMBRE_TITULAR")
    protected String nombretitular;
    @XmlElement(name = "FECHA_NACIMIENTO_TITULAR")
    protected String fechanacimientotitular;
    @XmlElement(name = "PROVINCIA_TITULAR")
    protected String provinciatitular;
    @XmlElement(name = "MUNICIPIO_TITULAR")
    protected String municipiotitular;
    @XmlElement(name = "PUEBLO_TITULAR")
    protected String pueblotitular;
    @XmlElement(name = "CODIGO_POSTAL_TITULAR")
    protected String codigopostaltitular;
    @XmlElement(name = "TIPO_VIA_TITULAR")
    protected String tipoviatitular;
    @XmlElement(name = "CALLE_DIRECCION_TITULAR")
    protected String calledirecciontitular;
    @XmlElement(name = "NUMERO_DIRECCION_TITULAR")
    protected String numerodirecciontitular;
    @XmlElement(name = "LETRA_DIRECCION_TITULAR")
    protected String letradirecciontitular;
    @XmlElement(name = "ESCALERA_DIRECCION_TITULAR")
    protected String escaleradirecciontitular;
    @XmlElement(name = "PISO_DIRECCION_TITULAR")
    protected String pisodirecciontitular;
    @XmlElement(name = "PUERTA_DIRECCION_TITULAR")
    protected String puertadirecciontitular;
    @XmlElement(name = "BLOQUE_DIRECCION_TITULAR")
    protected String bloquedirecciontitular;
    @XmlElement(name = "KM_DIRECCION_TITULAR")
    protected String kmdirecciontitular;
    @XmlElement(name = "HM_DIRECCION_TITULAR")
    protected String hmdirecciontitular;
    @XmlElement(name = "DIRECCION_ACTIVA_TITULAR")
    protected String direccionactivatitular;

    /**
     * Gets the value of the dnititular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNITITULAR() {
        return dnititular;
    }

    /**
     * Sets the value of the dnititular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNITITULAR(String value) {
        this.dnititular = value;
    }

    /**
     * Gets the value of the sexotitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEXOTITULAR() {
        return sexotitular;
    }

    /**
     * Sets the value of the sexotitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEXOTITULAR(String value) {
        this.sexotitular = value;
    }

    /**
     * Gets the value of the apellido1RAZONSOCIALTITULAR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPELLIDO1RAZONSOCIALTITULAR() {
        return apellido1RAZONSOCIALTITULAR;
    }

    /**
     * Sets the value of the apellido1RAZONSOCIALTITULAR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPELLIDO1RAZONSOCIALTITULAR(String value) {
        this.apellido1RAZONSOCIALTITULAR = value;
    }

    /**
     * Gets the value of the apellido2TITULAR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPELLIDO2TITULAR() {
        return apellido2TITULAR;
    }

    /**
     * Sets the value of the apellido2TITULAR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPELLIDO2TITULAR(String value) {
        this.apellido2TITULAR = value;
    }

    /**
     * Gets the value of the nombretitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMBRETITULAR() {
        return nombretitular;
    }

    /**
     * Sets the value of the nombretitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMBRETITULAR(String value) {
        this.nombretitular = value;
    }

    /**
     * Gets the value of the fechanacimientotitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHANACIMIENTOTITULAR() {
        return fechanacimientotitular;
    }

    /**
     * Sets the value of the fechanacimientotitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHANACIMIENTOTITULAR(String value) {
        this.fechanacimientotitular = value;
    }

    /**
     * Gets the value of the provinciatitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROVINCIATITULAR() {
        return provinciatitular;
    }

    /**
     * Sets the value of the provinciatitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROVINCIATITULAR(String value) {
        this.provinciatitular = value;
    }

    /**
     * Gets the value of the municipiotitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUNICIPIOTITULAR() {
        return municipiotitular;
    }

    /**
     * Sets the value of the municipiotitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUNICIPIOTITULAR(String value) {
        this.municipiotitular = value;
    }

    /**
     * Gets the value of the pueblotitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUEBLOTITULAR() {
        return pueblotitular;
    }

    /**
     * Sets the value of the pueblotitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUEBLOTITULAR(String value) {
        this.pueblotitular = value;
    }

    /**
     * Gets the value of the codigopostaltitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOPOSTALTITULAR() {
        return codigopostaltitular;
    }

    /**
     * Sets the value of the codigopostaltitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOPOSTALTITULAR(String value) {
        this.codigopostaltitular = value;
    }

    /**
     * Gets the value of the tipoviatitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOVIATITULAR() {
        return tipoviatitular;
    }

    /**
     * Sets the value of the tipoviatitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOVIATITULAR(String value) {
        this.tipoviatitular = value;
    }

    /**
     * Gets the value of the calledirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALLEDIRECCIONTITULAR() {
        return calledirecciontitular;
    }

    /**
     * Sets the value of the calledirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALLEDIRECCIONTITULAR(String value) {
        this.calledirecciontitular = value;
    }

    /**
     * Gets the value of the numerodirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMERODIRECCIONTITULAR() {
        return numerodirecciontitular;
    }

    /**
     * Sets the value of the numerodirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMERODIRECCIONTITULAR(String value) {
        this.numerodirecciontitular = value;
    }

    /**
     * Gets the value of the letradirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLETRADIRECCIONTITULAR() {
        return letradirecciontitular;
    }

    /**
     * Sets the value of the letradirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLETRADIRECCIONTITULAR(String value) {
        this.letradirecciontitular = value;
    }

    /**
     * Gets the value of the escaleradirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESCALERADIRECCIONTITULAR() {
        return escaleradirecciontitular;
    }

    /**
     * Sets the value of the escaleradirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESCALERADIRECCIONTITULAR(String value) {
        this.escaleradirecciontitular = value;
    }

    /**
     * Gets the value of the pisodirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPISODIRECCIONTITULAR() {
        return pisodirecciontitular;
    }

    /**
     * Sets the value of the pisodirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPISODIRECCIONTITULAR(String value) {
        this.pisodirecciontitular = value;
    }

    /**
     * Gets the value of the puertadirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUERTADIRECCIONTITULAR() {
        return puertadirecciontitular;
    }

    /**
     * Sets the value of the puertadirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUERTADIRECCIONTITULAR(String value) {
        this.puertadirecciontitular = value;
    }

    /**
     * Gets the value of the bloquedirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBLOQUEDIRECCIONTITULAR() {
        return bloquedirecciontitular;
    }

    /**
     * Sets the value of the bloquedirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBLOQUEDIRECCIONTITULAR(String value) {
        this.bloquedirecciontitular = value;
    }

    /**
     * Gets the value of the kmdirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKMDIRECCIONTITULAR() {
        return kmdirecciontitular;
    }

    /**
     * Sets the value of the kmdirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKMDIRECCIONTITULAR(String value) {
        this.kmdirecciontitular = value;
    }

    /**
     * Gets the value of the hmdirecciontitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMDIRECCIONTITULAR() {
        return hmdirecciontitular;
    }

    /**
     * Sets the value of the hmdirecciontitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMDIRECCIONTITULAR(String value) {
        this.hmdirecciontitular = value;
    }

    /**
     * Gets the value of the direccionactivatitular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIRECCIONACTIVATITULAR() {
        return direccionactivatitular;
    }

    /**
     * Sets the value of the direccionactivatitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIRECCIONACTIVATITULAR(String value) {
        this.direccionactivatitular = value;
    }

}
