//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 10:50:21 AM CEST 
//


package trafico.beans.schemas.generated.electronicMate.es.dgt.vehiculos.tipos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoCambioDomicilio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoCambioDomicilio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cambio_Domicilio" type="{http://www.dgt.es/vehiculos/tipos}tipoSINO"/>
 *         &lt;element name="Datos_Domicilio" type="{http://www.dgt.es/vehiculos/tipos}TipoDatoDireccion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoCambioDomicilio", propOrder = {
    "cambioDomicilio",
    "datosDomicilio"
})
public class TipoCambioDomicilio {

    @XmlElement(name = "Cambio_Domicilio", required = true)
    protected TipoSINO cambioDomicilio;
    @XmlElement(name = "Datos_Domicilio", required = true)
    protected TipoDatoDireccion datosDomicilio;

    /**
     * Gets the value of the cambioDomicilio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoSINO }
     *     
     */
    public TipoSINO getCambioDomicilio() {
        return cambioDomicilio;
    }

    /**
     * Sets the value of the cambioDomicilio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoSINO }
     *     
     */
    public void setCambioDomicilio(TipoSINO value) {
        this.cambioDomicilio = value;
    }

    /**
     * Gets the value of the datosDomicilio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDatoDireccion }
     *     
     */
    public TipoDatoDireccion getDatosDomicilio() {
        return datosDomicilio;
    }

    /**
     * Sets the value of the datosDomicilio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDatoDireccion }
     *     
     */
    public void setDatosDomicilio(TipoDatoDireccion value) {
        this.datosDomicilio = value;
    }

}
