//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 09:57:06 AM CET 
//

package trafico.beans.jaxb.matriculacion;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipoHomologacion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tipoHomologacion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="M1"/>
 *     &lt;enumeration value="M2"/>
 *     &lt;enumeration value="M3"/>
 *     &lt;enumeration value="N1"/>
 *     &lt;enumeration value="N2"/>
 *     &lt;enumeration value="N3"/>
 *     &lt;enumeration value="M1G"/>
 *     &lt;enumeration value="M2G"/>
 *     &lt;enumeration value="M3G"/>
 *     &lt;enumeration value="N1G"/>
 *     &lt;enumeration value="N2G"/>
 *     &lt;enumeration value="N3G"/>
 *     &lt;enumeration value="O1"/>
 *     &lt;enumeration value="O2"/>
 *     &lt;enumeration value="O3"/>
 *     &lt;enumeration value="O4"/>
 *     &lt;enumeration value="L1e"/>
 *     &lt;enumeration value="L2e"/>
 *     &lt;enumeration value="L3e"/>
 *     &lt;enumeration value="L4e"/>
 *     &lt;enumeration value="L5e"/>
 *     &lt;enumeration value="L6e"/>
 *     &lt;enumeration value="L7e"/>
 *     &lt;enumeration value="T1"/>
 *     &lt;enumeration value="T2"/>
 *     &lt;enumeration value="T3"/>
 *     &lt;enumeration value="T4"/>
 *     &lt;enumeration value="quad"/>
 *     &lt;enumeration value="atv"/>
 *     &lt;enumeration value="OTRO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tipoHomologacion")
@XmlEnum
public enum TipoHomologacion {

    @XmlEnumValue("M1")
    M_1("M1"),
    @XmlEnumValue("M2")
    M_2("M2"),
    @XmlEnumValue("M3")
    M_3("M3"),
    @XmlEnumValue("N1")
    N_1("N1"),
    @XmlEnumValue("N2")
    N_2("N2"),
    @XmlEnumValue("N3")
    N_3("N3"),    
    @XmlEnumValue("M1G")
    M_1_G("M1G"),
    @XmlEnumValue("M2G")
    M_2_G("M2G"),
    @XmlEnumValue("M3G")
    M_3_G("M3G"),
    @XmlEnumValue("N1G")
    N_1_G("N1G"),
    @XmlEnumValue("N2G")
    N_2_G("N2G"),
    @XmlEnumValue("N3G")
    N_3_G("N3G"),
    @XmlEnumValue("O1")
    O_1("O1"),
    @XmlEnumValue("O2")
    O_2("O2"),
    @XmlEnumValue("O3")
    O_3("O3"),
    @XmlEnumValue("O4")
    O_4("O4"),
    @XmlEnumValue("L1e")
    L_1_E("L1e"),
    @XmlEnumValue("L2e")
    L_2_E("L2e"),
    @XmlEnumValue("L3e")
    L_3_E("L3e"),
    @XmlEnumValue("L4e")
    L_4_E("L4e"),
    @XmlEnumValue("L5e")
    L_5_E("L5e"),
    @XmlEnumValue("L6e")
    L_6_E("L6e"),
    @XmlEnumValue("L7e")
    L_7_E("L7e"),
    @XmlEnumValue("T1")
    T_1("T1"),
    @XmlEnumValue("T2")
    T_2("T2"),
    @XmlEnumValue("T3")
    T_3("T3"),
    @XmlEnumValue("T4")
    T_4("T4"),
    @XmlEnumValue("quad")
    QUAD("quad"),
    @XmlEnumValue("atv")
    ATV("atv"),
    @XmlEnumValue("otro")
    OTRO("OTRO");
    private final String value;

    TipoHomologacion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoHomologacion fromValue(String v) {
        for (TipoHomologacion c: TipoHomologacion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}