package com.registradoresWS.utilidades;


public class Constantes {
	
	public  final String ACK_VERSION = "ACK_VERSION";
	public  final String TIPO_ENTIDAD = "TIPO_ENTIDAD";
	public  final String CODIGO_ENTIDAD = "CODIGO_ENTIDAD";
	public  final String RUTA_NOTIFICACIONES_ACUSES = "RUTA_NOTIFICACIONES_ACUSES";
	public  final String RUTA_NOTIFICACIONES_CONTENIDO = "RUTA_NOTIFICACIONES_CONTENIDO";
	public  final String RUTA_MENSAJE_RECIBIDO_TEMPORAL = "RUTA_MENSAJE_RECIBIDO_TEMPORAL";
	public  final String RUTA_NOTIFICACIONES_RECIBIDO = "RUTA_NOTIFICACIONES_RECIBIDO";
	public  final String DENEGACION_ASIENTO = "DENEGACION_ASIENTO";
	public  final String DENEGACION_ASIENTO_CONFIRMACION = "DENEGACION_ASIENTO_CONFIRMACION";
	public  final String ACEPTACION_ASIENTO = "ACEPTACION_ASIENTO";
	public  final String ACEPTACION_ASIENTO_CONFIRMACION = "ACEPTACION_ASIENTO_CONFIRMACION";
	public  final String RESOLUCION_TOTAL = "RESOLUCION_TOTAL";
	public  final String RESOLUCION_PARCIAL = "RESOLUCION_PARCIAL";
	public  final String RESOLUCION_DEFECTOS = "RESOLUCION_DEFECTOS";

}
