package trafico.utiles;

import java.lang.reflect.Field;
import java.util.ArrayList;

public class XmlElementos {

	//CABECERA
	public static final String ELEMENTO_CABECERA = "CABECERA";
	public static final String ELEMENTO_NIF = "NIF";
	public static final String ELEMENTO_NOMBRE = "NOMBRE";
	public static final String ELEMENTO_PROFESIONAL = "PROFESIONAL";
	public static final String ELEMENTO_PROVINCIA = "PROVINCIA";	
	
	//MATRICULACION
	public static final String ELEMENTO_MATRICULACION = "MATRICULACION";
	public static final String ELEMENTO_NUMERO_EXPEDIENTE = "NUMERO_EXPEDIENTE";
	public static final String ELEMENTO_NUMERO_DOCUMENTO = "NUMERO_DOCUMENTO";
	public static final String ELEMENTO_NUMERO_PROFESIONAL = "NUMERO_PROFESIONAL";
	public static final String ELEMENTO_FECHA_CREACION = "FECHA_CREACION";
	public static final String ELEMENTO_FECHA_PRESENTACION = "FECHA_PRESENTACION";
	public static final String ELEMENTO_FECHA_DEVOLUCION = "FECHA_DEVOLUCION";
	public static final String ELEMENTO_JEFATURA = "JEFATURA";
	public static final String ELEMENTO_SUCURSAL = "SUCURSAL";
	public static final String ELEMENTO_TIPO_TASA = "TIPO_TASA";
	public static final String ELEMENTO_TASA = "TASA";
	public static final String ELEMENTO_PROCEDENCIA = "PROCEDENCIA";
	public static final String ELEMENTO_OBSERVACIONES = "OBSERVACIONES";
	public static final String ELEMENTO_NUMERO_COTITULARES = "NUMERO_COTITULARES";

	public static final String ELEMENTO_RAZON_SOCIAL_DEST = "RAZON_SOCIAL_DEST";
	public static final String ELEMENTO_DNI_DEST = "DNI_DEST";
	public static final String ELEMENTO_APELLIDO1_DEST = "APELLIDO1_DEST";
	public static final String ELEMENTO_APELLIDO2_DEST = "APELLIDO2_DEST";
	public static final String ELEMENTO_NOMBRE_DEST = "NOMBRE_DEST";
	public static final String ELEMENTO_SIGLAS_DIRECCION_DEST = "SIGLAS_DIRECCION_DEST";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_DEST = "NOMBRE_VIA_DIRECCION_DEST";
	public static final String ELEMENTO_NUMERO_DIRECCION_DEST = "NUMERO_DIRECCION_DEST";
	public static final String ELEMENTO_LETRA_DIRECCION_DEST = "LETRA_DIRECCION_DEST";
	public static final String ELEMENTO_ESCALERA_DIRECCION_DEST = "ESCALERA_DIRECCION_DEST";
	public static final String ELEMENTO_PISO_DIRECCION_DEST = "PISO_DIRECCION_DEST";
	public static final String ELEMENTO_PUERTA_DIRECCION_DEST = "PUERTA_DIRECCION_DEST";
	public static final String ELEMENTO_KM_DIRECCION_DEST = "KM_DIRECCION_DEST";
	public static final String ELEMENTO_BLOQUE_DIRECCION_DEST = "BLOQUE_DIRECCION_DEST";
	public static final String ELEMENTO_MUNICIPIO_DEST = "MUNICIPIO_DEST";
	public static final String ELEMENTO_PUEBLO_DEST = "PUEBLO_DEST";
	public static final String ELEMENTO_PROVINCIA_DEST = "PROVINCIA_DEST";
	public static final String ELEMENTO_CP_DEST = "CP_DEST";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_DEST = "HECTOMETRO_DIRECCION_DEST";
	public static final String ELEMENTO_PAIS_DEST = "PAIS_DEST";
	public static final String ELEMENTO_TELEFONO_DEST = "TELEFONO_DEST";
	public static final String ELEMENTO_CORREO_ELECTRONICO_DEST = "CORREO_ELECTRONICO_DEST";
	
	public static final String ELEMENTO_RAZON_SOCIAL_TITULAR = "RAZON_SOCIAL_TITULAR";
	public static final String ELEMENTO_DNI_TITULAR = "DNI_TITULAR";
	public static final String ELEMENTO_ANAGRAMA_TITULAR = "ANAGRAMA_TITULAR";
	public static final String ELEMENTO_APELLIDO1_TITULAR = "APELLIDO1_TITULAR";
	public static final String ELEMENTO_APELLIDO2_TITULAR = "APELLIDO2_TITULAR";
	public static final String ELEMENTO_NOMBRE_TITULAR = "NOMBRE_TITULAR";
	public static final String ELEMENTO_FECHA_NACIMIENTO_TITULAR = "FECHA_NACIMIENTO_TITULAR";
	public static final String ELEMENTO_AUTONOMO = "AUTONOMO";
	public static final String ELEMENTO_CODIGO_IAE = "CODIGO_IAE";
	public static final String ELEMENTO_CAMBIO_DOMICILIO = "CAMBIO_DOMICILIO";
	public static final String ELEMENTO_SEXO_TITULAR = "SEXO_TITULAR";
	public static final String ELEMENTO_SIGLAS_DIRECCION_TITULAR = "SIGLAS_DIRECCION_TITULAR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_TITULAR = "NOMBRE_VIA_DIRECCION_TITULAR";
	public static final String ELEMENTO_NUMERO_DIRECCION_TITULAR = "NUMERO_DIRECCION_TITULAR";
	public static final String ELEMENTO_LETRA_DIRECCION_TITULAR = "LETRA_DIRECCION_TITULAR";
	public static final String ELEMENTO_ESCALERA_DIRECCION_TITULAR = "ESCALERA_DIRECCION_TITULAR";
	public static final String ELEMENTO_PISO_DIRECCION_TITULAR = "PISO_DIRECCION_TITULAR";
	public static final String ELEMENTO_PUERTA_DIRECCION_TITULAR = "PUERTA_DIRECCION_TITULAR";
	public static final String ELEMENTO_KM_DIRECCION_TITULAR = "KM_DIRECCION_TITULAR";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_TITULAR = "HECTOMETRO_DIRECCION_TITULAR";
	public static final String ELEMENTO_BLOQUE_DIRECCION_TITULAR = "BLOQUE_DIRECCION_TITULAR";
	public static final String ELEMENTO_MUNICIPIO_TITULAR = "MUNICIPIO_TITULAR";
	public static final String ELEMENTO_PUEBLO_TITULAR = "PUEBLO_TITULAR";
	public static final String ELEMENTO_PROVINCIA_TITULAR = "PROVINCIA_TITULAR";
	public static final String ELEMENTO_CP_TITULAR = "CP_TITULAR";
	public static final String ELEMENTO_TELEFONO_TITULAR = "TELEFONO_TITULAR";
	public static final String ELEMENTO_CORREO_ELECTRONICO_TITULAR = "CORREO_ELECTRONICO_TITULAR";
	public static final String ELEMENTO_DNI_REP_TITULAR = "DNI_REP_TITULAR";
	public static final String ELEMENTO_NOMBRE_REP_TITULAR = "NOMBRE_REP_TITULAR";
	public static final String ELEMENTO_CONCEPTO_REP_TITULAR = "CONCEPTO_REP_TITULAR";
	public static final String ELEMENTO_ACREDITACION_REP_TITULAR = "ACREDITACION_REP_TITULAR";

	//TRANSMISION	
	public static final String ELEMENTO_DATOS_VEHICULO = "DATOS_VEHICULO";
	public static final String ELEMENTO_DATOS_LIMITACION = "DATOS_LIMITACION";
	public static final String ELEMENTO_DATOS_ARRENDADOR_COMPRA_VENTA = "DATOS_ARRENDADOR_COMPRA_VENTA";
	public static final String ELEMENTO_DATOS_620 = "DATOS_620";

	public static final String ELEMENTO_FORMATO_GA = "FORMATO_GA";
	public static final String ELEMENTO_TRANSMISION = "TRANSMISION";
	public static final String ELEMENTO_DATOS_GESTORIA = "DATOS_GESTORIA";
	public static final String ELEMENTO_DATOS_ADQUIRIENTE = "DATOS_ADQUIRIENTE";
	public static final String ELEMENTO_DATOS_TRANSMITENTE = "DATOS_TRANSMITENTE";
	public static final String ELEMENTO_DATOS_PRESENTADOR = "DATOS_PRESENTADOR";
	public static final String ELEMENTO_DATOS_PRESENTACION = "DATOS_PRESENTACION";
	
	public static final String ELEMENTO_DNI_ADQUIRIENTE = "DNI_ADQUIRIENTE";
	public static final String ELEMENTO_APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE = "APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE";
	public static final String ELEMENTO_APELLIDO2_ADQUIRIENTE = "APELLIDO2_ADQUIRIENTE";
	public static final String ELEMENTO_NOMBRE_ADQUIRIENTE = "NOMBRE_ADQUIRIENTE";
	public static final String ELEMENTO_FECHA_NACIMIENTO_ADQUIRIENTE = "FECHA_NACIMIENTO_ADQUIRIENTE";
	public static final String ELEMENTO_SEXO_ADQUIRIENTE = "SEXO_ADQUIRIENTE";
	public static final String ELEMENTO_TELEFONO_ADQUIRIENTE = "TELEFONO_ADQUIRIENTE";
	public static final String ELEMENTO_SIGLAS_DIRECCION_ADQUIRIENTE = "SIGLAS_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_ADQUIRIENTE = "NOMBRE_VIA_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_NUMERO_DIRECCION_ADQUIRIENTE = "NUMERO_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_LETRA_DIRECCION_ADQUIRIENTE = "LETRA_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_ESCALERA_DIRECCION_ADQUIRIENTE = "ESCALERA_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_PISO_DIRECCION_ADQUIRIENTE = "PISO_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_PUERTA_DIRECCION_ADQUIRIENTE = "PUERTA_DIRECCION_ADQUIRIENTE";
	public static final String ELEMENTO_PROVINCIA_ADQUIRIENTE = "PROVINCIA_ADQUIRIENTE";
	public static final String ELEMENTO_MUNICIPIO_ADQUIRIENTE = "MUNICIPIO_ADQUIRIENTE";
	public static final String ELEMENTO_PUEBLO_ADQUIRIENTE = "PUEBLO_ADQUIRIENTE";
	public static final String ELEMENTO_CP_ADQUIRIENTE = "CP_ADQUIRIENTE";
	public static final String ELEMENTO_DNI_REPRESENTANTE_ADQUIRIENTE = "DNI_REPRESENTANTE_ADQUIRIENTE";
	public static final String ELEMENTO_NOMBRE_APELLIDOS_REPRESENTANTE_ADQUIRIENTE = "NOMBRE_APELLIDOS_REPRESENTANTE_ADQUIRIENTE";
	public static final String ELEMENTO_CONCEPTO_REPRESENTANTE_ADQUIRIENTE = "CONCEPTO_REPRESENTANTE_ADQUIRIENTE";
	public static final String ELEMENTO_DOCUMENTOS_REPRESENTANTE_ADQUIRIENTE = "DOCUMENTOS_REPRESENTANTE_ADQUIRIENTE";

	public static final String ELEMENTO_DNI_TRANSMITENTE = "DNI_TRANSMITENTE";
	public static final String ELEMENTO_SEXO_TRANSMITENTE = "SEXO_TRANSMITENTE";
	public static final String ELEMENTO_APELLIDO1_RAZON_SOCIAL_TRANSMITENTE = "APELLIDO1_RAZON_SOCIAL_TRANSMITENTE";
	public static final String ELEMENTO_APELLIDO2_TRANSMITENTE = "APELLIDO2_TRANSMITENTE";
	public static final String ELEMENTO_NOMBRE_TRANSMITENTE = "NOMBRE_TRANSMITENTE";
	public static final String ELEMENTO_FECHA_NACIMIENTO_TRANSMITENTE = "FECHA_NACIMIENTO_TRANSMITENTE";
	public static final String ELEMENTO_TELEFONO_TRANSMITENTE = "TELEFONO_TRANSMITENTE";
	public static final String ELEMENTO_SIGLAS_DIRECCION_TRANSMITENTE = "SIGLAS_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_TRANSMITENTE = "NOMBRE_VIA_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_NUMERO_DIRECCION_TRANSMITENTE = "NUMERO_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_LETRA_DIRECCION_TRANSMITENTE = "LETRA_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_ESCALERA_DIRECCION_TRANSMITENTE = "ESCALERA_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_PISO_DIRECCION_TRANSMITENTE = "PISO_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_PUERTA_DIRECCION_TRANSMITENTE = "PUERTA_DIRECCION_TRANSMITENTE";
	public static final String ELEMENTO_PROVINCIA_TRANSMITENTE = "PROVINCIA_TRANSMITENTE";
	public static final String ELEMENTO_MUNICIPIO_TRANSMITENTE = "MUNICIPIO_TRANSMITENTE";
	public static final String ELEMENTO_PUEBLO_TRANSMITENTE = "PUEBLO_TRANSMITENTE";
	public static final String ELEMENTO_CP_TRANSMITENTE = "CP_TRANSMITENTE";
	public static final String ELEMENTO_DNI_REPRESENTANTE_TRANSMITENTE = "DNI_REPRESENTANTE_TRANSMITENTE";
	public static final String ELEMENTO_NOMBRE_APELLIDOS_REPRESENTANTE_TRANSMITENTE = "NOMBRE_APELLIDOS_REPRESENTANTE_TRANSMITENTE";
	public static final String ELEMENTO_DOCUMENTOS_REPRESENTANTE_ARRENDADOR = "DOCUMENTOS_REPRESENTANTE_ARRENDADOR";
	
	public static final String ELEMENTO_SEXO_PRESENTADOR = "SEXO_PRESENTADOR";
	public static final String ELEMENTO_APELLIDO1_RAZON_SOCIAL_PRESENTADOR = "APELLIDO1_RAZON_SOCIAL_PRESENTADOR";
	
	public static final String ELEMENTO_FECHA_CADUCIDAD_ITV = "FECHA_CADUCIDAD_ITV";
	public static final String ELEMENTO_MODO_ADJUDICACION = "MODO_ADJUDICACION";
	public static final String ELEMENTO_TIPO_TRANSFERENCIA = "TIPO_TRANSFERENCIA";
	public static final String ELEMENTO_MOTIVO_ITV = "MOTIVO_ITV";
	public static final String ELEMENTO_CONCEPTO_ITV = "CONCEPTO_ITV";
	public static final String ELEMENTO_ESTACION_ITV = "ESTACION_ITV";
	public static final String ELEMENTO_CALLE_DIRECCION_VEHICULO = "CALLE_DIRECCION_VEHICULO";
	public static final String ELEMENTO_DECLARACION_RESPONSABILIDAD = "DECLARACION_RESPONSABILIDAD";
	
	public static final String ELEMENTO_DNI_ARRENDADOR = "DNI_ARRENDADOR";
	public static final String ELEMENTO_NOMBRE_APELLIDOS_ARRENDADOR = "NOMBRE_APELLIDOS_ARRENDADOR";
	public static final String ELEMENTO_FECHA_NACIMIENTO_ARRENDADOR = "FECHA_NACIMIENTO_ARRENDADOR";
	public static final String ELEMENTO_SEXO_ARRENDADOR = "SEXO_ARRENDADOR";
	public static final String ELEMENTO_SIGLAS_DIRECCION_ARRENDADOR = "SIGLAS_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_ARRENDADOR = "NOMBRE_VIA_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_NUMERO_DIRECCION_ARRENDADOR = "NUMERO_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_LETRA_DIRECCION_ARRENDADOR = "LETRA_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_ESCALERA_DIRECCION_ARRENDADOR = "ESCALERA_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_PISO_DIRECCION_ARRENDADOR = "PISO_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_PUERTA_DIRECCION_ARRENDADOR = "PUERTA_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_PROVINCIA_ARRENDADOR = "PROVINCIA_ARRENDADOR";
	public static final String ELEMENTO_MUNICIPIO_ARRENDADOR = "MUNICIPIO_ARRENDADOR";
	public static final String ELEMENTO_PUEBLO_DIRECCION_ARRENDADOR = "PUEBLO_DIRECCION_ARRENDADOR";
	public static final String ELEMENTO_CP_ARRENDADOR = "CP_ARRENDADOR";
	public static final String ELEMENTO_DNI_REPRESENTANTE_ARRENDADOR = "DNI_REPRESENTANTE_ARRENDADOR";
	public static final String ELEMENTO_NOMBRE_APELLIDOS_REPRESENTANTE_ARRENDADOR = "NOMBRE_APELLIDOS_REPRESENTANTE_ARRENDADOR";
	
	public static final String ELEMENTO_OFICINA_LIQUIDADORA = "OFICINA_LIQUIDADORA";
	public static final String ELEMENTO_FECHA_DEVENGO = "FECHA_DEVENGO";
	public static final String ELEMENTO_MARCA_620 = "MARCA_620";
	public static final String ELEMENTO_MARCA_620_DESC = "MARCA_620_DESC";
	public static final String ELEMENTO_MODELO_620 = "MODELO_620";
	public static final String ELEMENTO_MODELO_620_DESC = "MODELO_620_DESC";
	public static final String ELEMENTO_NUM_CILINDROS = "NUM_CILINDROS";
	public static final String ELEMENTO_CARACTERISTICAS = "CARACTERISTICAS";
	public static final String ELEMENTO_ANIO_FABRICACION = "ANIO_FABRICACION";
	public static final String ELEMENTO_EXENTO = "EXENTO";
	public static final String ELEMENTO_NO_SUJETO = "NO_SUJETO";
	public static final String ELEMENTO_FUNDAMENTO_EXENCION = "FUNDAMENTO_EXENCION";
	public static final String ELEMENTO_FUNDAMENTO_NO_SUJETO = "FUNDAMENTO_NO_SUJETO";
	public static final String ELEMENTO_PORCENTAJE_REDUCCION_ANUAL = "PORCENTAJE_REDUCCION_ANUAL";
	public static final String ELEMENTO_VALOR_DECLARADO = "VALOR_DECLARADO";
	public static final String ELEMENTO_PORCENTAJE_ADQUISICION = "PORCENTAJE_ADQUISICION";
	public static final String ELEMENTO_BASE_IMPONIBLE = "BASE_IMPONIBLE";
	public static final String ELEMENTO_TIPO_GRAVAMEN = "TIPO_GRAVAMEN";
	public static final String ELEMENTO_CUOTA_TRIBUTARIA = "CUOTA_TRIBUTARIA";
	public static final String ELEMENTO_DIRECCION_DISTINTA_ADQUIRIENTE = "DIRECCION_DISTINTA_ADQUIRIENTE";
	
	public static final String ELEMENTO_SIGLAS_DIRECCION_DISTINTA_ADQUIRIENTE = "SIGLAS_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_DISTINTA_ADQUIRIENTE = "NOMBRE_VIA_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_NUMERO_DIRECCION_DISTINTA_ADQUIRIENTE = "NUMERO_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_LETRA_DIRECCION_DISTINTA_ADQUIRIENTE = "LETRA_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_ESCALERA_DIRECCION_DISTINTA_ADQUIRIENTE = "ESCALERA_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_PISO_DIRECCION_DISTINTA_ADQUIRIENTE = "PISO_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_PUERTA_DIRECCION_DISTINTA_ADQUIRIENTE = "PUERTA_DIRECCION_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_PROVINCIA_DISTINTA_ADQUIRIENTE = "PROVINCIA_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_MUNICIPIO_DISTINTA_ADQUIRIENTE = "MUNICIPIO_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_PUEBLO_DISTINTA_ADQUIRIENTE = "PUEBLO_DISTINTA_ADQUIRIENTE";
	public static final String ELEMENTO_CP_DISTINTA_ADQUIRIENTE = "CP_DISTINTA_ADQUIRIENTE";
	
	public static final String ELEMENTO_CODIGO_ELECTRONICO_TRANSFERENCIA = "CODIGO_ELECTRONICO_TRANSFERENCIA";
	public static final String ELEMENTO_CODIGO_TASA = "CODIGO_TASA";
	public static final String ELEMENTO_JEFATURA_PROVINCIAL = "JEFATURA_PROVINCIAL";	
	
	public static final String ELEMENTO_RAZON_SOCIAL_ARR = "RAZON_SOCIAL_ARR";
	public static final String ELEMENTO_DNI_ARR = "DNI_ARR";
	public static final String ELEMENTO_ANAGRAMA_ARR = "ANAGRAMA_ARR";
	public static final String ELEMENTO_APELLIDO1_ARR = "APELLIDO1_ARR";
	public static final String ELEMENTO_APELLIDO2_ARR = "APELLIDO2_ARR";
	public static final String ELEMENTO_NOMBRE_ARR = "NOMBRE_ARR";
	public static final String ELEMENTO_FECHA_NACIMIENTO_ARR = "FECHA_NACIMIENTO_ARR";
	public static final String ELEMENTO_SEXO_ARR = "SEXO_ARR";
	public static final String ELEMENTO_SIGLAS_DIRECCION_ARR = "SIGLAS_DIRECCION_ARR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_ARR = "NOMBRE_VIA_DIRECCION_ARR";
	public static final String ELEMENTO_NUMERO_DIRECCION_ARR = "NUMERO_DIRECCION_ARR";
	public static final String ELEMENTO_LETRA_DIRECCION_ARR = "LETRA_DIRECCION_ARR";
	public static final String ELEMENTO_ESCALERA_DIRECCION_ARR = "ESCALERA_DIRECCION_ARR";
	public static final String ELEMENTO_PISO_DIRECCION_ARR = "PISO_DIRECCION_ARR";
	public static final String ELEMENTO_PUERTA_DIRECCION_ARR = "PUERTA_DIRECCION_ARR";
	public static final String ELEMENTO_KM_DIRECCION_ARR = "KM_DIRECCION_ARR";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_ARR = "HECTOMETRO_DIRECCION_ARR";
	public static final String ELEMENTO_BLOQUE_DIRECCION_ARR = "BLOQUE_DIRECCION_ARR";
	public static final String ELEMENTO_MUNICIPIO_ARR = "MUNICIPIO_ARR";
	public static final String ELEMENTO_PUEBLO_ARR = "PUEBLO_ARR";
	public static final String ELEMENTO_PROVINCIA_ARR = "PROVINCIA_ARR";
	public static final String ELEMENTO_CP_ARR = "CP_ARR";
	public static final String ELEMENTO_FECHA_INICIO_RENTING = "FECHA_INICIO_RENTING";
	public static final String ELEMENTO_FECHA_FIN_RENTING = "FECHA_FIN_RENTING";
	public static final String ELEMENTO_HORA_INICIO_RENTING = "HORA_INICIO_RENTING";
	public static final String ELEMENTO_HORA_FIN_RENTING = "HORA_FIN_RENTING";
	public static final String ELEMENTO_PAIS_ARR = "PAIS_ARR";

	public static final String ELEMENTO_DNI_COND_HABITUAL = "DNI_COND_HABITUAL";
	public static final String ELEMENTO_FECHA_INICIO_COND_HABITUAL = "FECHA_INICIO_COND_HABITUAL";
	public static final String ELEMENTO_FECHA_FIN_COND_HABITUAL = "FECHA_FIN_COND_HABITUAL";
	
	public static final String ELEMENTO_DNI_TUTOR = "DNI_TUTOR";
	public static final String ELEMENTO_FECHA_INICIO_TUTOR = "FECHA_INICIO_TUTOR";
	public static final String ELEMENTO_CODIGO_TRAMITE = "CODIGO_TRAMITE";
	public static final String ELEMENTO_TIPO_TUTELA = "TIPO_TUTELA";
	
	public static final String ELEMENTO_RAZON_SOCIAL_PRESENTADOR = "RAZON_SOCIAL_PRESENTADOR";
	public static final String ELEMENTO_DNI_PRESENTADOR = "DNI_PRESENTADOR";
	public static final String ELEMENTO_APELLIDO1_PRESENTADOR = "APELLIDO1_PRESENTADOR";
	public static final String ELEMENTO_APELLIDO2_PRESENTADOR = "APELLIDO2_PRESENTADOR";
	public static final String ELEMENTO_NOMBRE_PRESENTADOR = "NOMBRE_PRESENTADOR";
	public static final String ELEMENTO_SIGLAS_DIRECCION_PRESENTADOR = "SIGLAS_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_PRESENTADOR = "NOMBRE_VIA_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_NUMERO_DIRECCION_PRESENTADOR = "NUMERO_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_LETRA_DIRECCION_PRESENTADOR = "LETRA_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_ESCALERA_DIRECCION_PRESENTADOR = "ESCALERA_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_PISO_DIRECCION_PRESENTADOR = "PISO_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_PUERTA_DIRECCION_PRESENTADOR = "PUERTA_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_KM_DIRECCION_PRESENTADOR = "KM_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_PRESENTADOR = "KM_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_BLOQUE_DIRECCION_PRESENTADOR = "BLOQUE_DIRECCION_PRESENTADOR";
	public static final String ELEMENTO_MUNICIPIO_PRESENTADOR = "MUNICIPIO_PRESENTADOR";
	public static final String ELEMENTO_PROVINCIA_PRESENTADOR = "PROVINCIA_PRESENTADOR";
	public static final String ELEMENTO_CP_PRESENTADOR = "CP_PRESENTADOR";
	public static final String ELEMENTO_TELEFONO_PRESENTADOR = "TELEFONO_PRESENTADOR";
	public static final String ELEMENTO_CORREO_ELECTRONICO_PRESENTADOR = "CORREO_ELECTRONICO_PRESENTADOR";
	public static final String ELEMENTO_PAIS_PRESENTADOR = "PAIS_PRESENTADOR";
	public static final String ELEMENTO_RAZON_SOCIAL_SEGUNDO_TITULAR = "RAZON_SOCIAL_SEGUNDO_TITULAR";
	public static final String ELEMENTO_DNI_SEGUNDO_TITULAR = "DNI_SEGUNDO_TITULAR";
	public static final String ELEMENTO_APELLIDO1_SEGUNDO_TITULAR = "APELLIDO1_SEGUNDO_TITULAR";
	public static final String ELEMENTO_APELLIDO2_SEGUNDO_TITULAR = "APELLIDO2_SEGUNDO_TITULAR";
	public static final String ELEMENTO_NOMBRE_SEGUNDO_TITULAR = "NOMBRE_SEGUNDO_TITULAR";
	public static final String ELEMENTO_FECHA_NACIMIENTO_SEGUNDO_TITULAR = "FECHA_NACIMIENTO_SEGUNDO_TITULAR";
	public static final String ELEMENTO_SEXO_SEGUNDO_TITULAR = "SEXO_SEGUNDO_TITULAR";
	public static final String ELEMENTO_CAMBIO_SEGUNDO_DOMICILIO = "CAMBIO_SEGUNDO_DOMICILIO";
	public static final String ELEMENTO_SIGLAS_DIRECCION_SEGUNDO_TITULAR = "SIGLAS_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_SEGUNDO_TITULAR = "NOMBRE_VIA_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_NUMERO_DIRECCION_SEGUNDO_TITULAR = "NUMERO_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_LETRA_DIRECCION_SEGUNDO_TITULAR = "LETRA_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_ESCALERA_DIRECCION_SEGUNDO_TITULAR = "ESCALERA_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_PISO_DIRECCION_SEGUNDO_TITULAR = "PISO_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_PUERTA_DIRECCION_SEGUNDO_TITULAR = "PUERTA_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_KM_DIRECCION_SEGUNDO_TITULAR = "KM_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_SEGUNDO_TITULAR = "HECTOMETRO_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_BLOQUE_DIRECCION_SEGUNDO_TITULAR = "BLOQUE_DIRECCION_SEGUNDO_TITULAR";
	public static final String ELEMENTO_MUNICIPIO_SEGUNDO_TITULAR = "MUNICIPIO_SEGUNDO_TITULAR";
	public static final String ELEMENTO_PUEBLO_SEGUNDO_TITULAR = "PUEBLO_SEGUNDO_TITULAR";
	public static final String ELEMENTO_PROVINCIA_SEGUNDO_TITULAR = "PROVINCIA_SEGUNDO_TITULAR";
	public static final String ELEMENTO_CP_SEGUNDO_TITULAR = "CP_SEGUNDO_TITULAR";
	public static final String ELEMENTO_RAZON_SOCIAL_TERCER_TITULAR = "RAZON_SOCIAL_TERCER_TITULAR";
	public static final String ELEMENTO_DNI_TERCER_TITULAR = "DNI_TERCER_TITULAR";
	public static final String ELEMENTO_APELLIDO1_TERCER_TITULAR = "APELLIDO1_TERCER_TITULAR";
	public static final String ELEMENTO_APELLIDO2_TERCER_TITULAR = "APELLIDO2_TERCER_TITULAR";
	public static final String ELEMENTO_NOMBRE_TERCER_TITULAR = "NOMBRE_TERCER_TITULAR";
	public static final String ELEMENTO_FECHA_NACIMIENTO_TERCER_TITULAR = "FECHA_NACIMIENTO_TERCER_TITULAR";
	public static final String ELEMENTO_SEXO_TERCER_TITULAR = "SEXO_TERCER_TITULAR";
	public static final String ELEMENTO_SIGLAS_DIRECCION_TERCER_TITULAR = "SIGLAS_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_TERCER_TITULAR = "NOMBRE_VIA_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_NUMERO_DIRECCION_TERCER_TITULAR = "NUMERO_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_LETRA_DIRECCION_TERCER_TITULAR = "LETRA_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_ESCALERA_DIRECCION_TERCER_TITULAR = "ESCALERA_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_PISO_DIRECCION_TERCER_TITULAR = "PISO_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_PUERTA_DIRECCION_TERCER_TITULAR = "PUERTA_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_KM_DIRECCION_TERCER_TITULAR = "KM_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_TERCER_TITULAR = "HECTOMETRO_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_BLOQUE_DIRECCION_TERCER_TITULAR = "BLOQUE_DIRECCION_TERCER_TITULAR";
	public static final String ELEMENTO_MUNICIPIO_TERCER_TITULAR = "MUNICIPIO_TERCER_TITULAR";
	public static final String ELEMENTO_PUEBLO_TERCER_TITULAR = "PUEBLO_TERCER_TITULAR";
	public static final String ELEMENTO_PROVINCIA_TERCER_TITULAR = "PROVINCIA_TERCER_TITULAR";
	public static final String ELEMENTO_CP_TERCER_TITULAR = "CP_TERCER_TITULAR";
	public static final String ELEMENTO_DNI_VENDEDOR = "DNI_VENDEDOR";
	public static final String ELEMENTO_APELLIDO1_VENDEDOR = "APELLIDO1_VENDEDOR";
	public static final String ELEMENTO_APELLIDO2_VENDEDOR = "APELLIDO2_VENDEDOR";
	public static final String ELEMENTO_NOMBRE_VENDEDOR = "NOMBRE_VENDEDOR";
	public static final String ELEMENTO_FECHA_NACIMIENTO_VENDEDOR = "FECHA_NACIMIENTO_VENDEDOR";
	public static final String ELEMENTO_SEXO_VENDEDOR = "SEXO_VENDEDOR";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_VENDEDOR = "NOMBRE_VIA_DIRECCION_VENDEDOR";
	public static final String ELEMENTO_MUNICIPIO_VENDEDOR = "MUNICIPIO_VENDEDOR";
	public static final String ELEMENTO_PUEBLO_VENDEDOR = "PUEBLO_VENDEDOR";
	public static final String ELEMENTO_PROVINCIA_VENDEDOR = "PROVINCIA_VENDEDOR";
	public static final String ELEMENTO_CP_VENDEDOR = "CP_VENDEDOR";
	public static final String ELEMENTO_RAZON_SOCIAL_IMPORTADOR = "RAZON_SOCIAL_IMPORTADOR";
	public static final String ELEMENTO_DNI_IMPORTADOR = "DNI_IMPORTADOR";
	public static final String ELEMENTO_APELLIDO1_IMPORTADOR = "APELLIDO1_IMPORTADOR";
	public static final String ELEMENTO_APELLIDO2_IMPORTADOR = "APELLIDO2_IMPORTADOR";
	public static final String ELEMENTO_NOMBRE_IMPORTADOR = "NOMBRE_IMPORTADOR";
	public static final String ELEMENTO_MATRICULA = "MATRICULA";
	public static final String ELEMENTO_FECHA_MATRICULACION = "FECHA_MATRICULACION";
	public static final String ELEMENTO_FECHA_PRIMERA_MATRICULACION = "FECHA_PRIMERA_MATRICULACION";
	public static final String ELEMENTO_FECHA_MATRICULA_TURISTICA = "FECHA_MATRICULA_TURISTICA";
	public static final String ELEMENTO_MATRICULA_DIPLOMATICA = "MATRICULA_DIPLOMATICA";
	public static final String ELEMENTO_MATRICULA_AYUNTAMIENTO = "MATRICULA_AYUNTAMIENTO";
	public static final String ELEMENTO_SIGLAS_DIRECCION_VEHICULO = "SIGLAS_DIRECCION_VEHICULO";
	public static final String ELEMENTO_DOMICILIO_VEHICULO = "DOMICILIO_VEHICULO";
	public static final String ELEMENTO_NUMERO_DIRECCION_VEHICULO = "NUMERO_DIRECCION_VEHICULO";
	public static final String ELEMENTO_LETRA_DIRECCION_VEHICULO = "LETRA_DIRECCION_VEHICULO";
	public static final String ELEMENTO_ESCALERA_DIRECCION_VEHICULO = "ESCALERA_DIRECCION_VEHICULO";
	public static final String ELEMENTO_PISO_DIRECCION_VEHICULO = "PISO_DIRECCION_VEHICULO";
	public static final String ELEMENTO_PUERTA_DIRECCION_VEHICULO = "PUERTA_DIRECCION_VEHICUL";
	public static final String ELEMENTO_KM_DIRECCION_VEHICULO = "KM_DIRECCION_VEHICULO";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_VEHICULO = "HECTOMETRO_DIRECCION_VEHICULO";
	public static final String ELEMENTO_BLOQUE_DIRECCION_VEHICULO = "BLOQUE_DIRECCION_VEHICULO";
	public static final String ELEMENTO_MUNICIPIO_VEHICULO = "MUNICIPIO_VEHICULO";
	public static final String ELEMENTO_PUEBLO_VEHICULO = "PUEBLO_VEHICULO";
	public static final String ELEMENTO_PROVINCIA_VEHICULO = "PROVINCIA_VEHICULO";
	public static final String ELEMENTO_CP_VEHICULO = "CP_VEHICULO";
	public static final String ELEMENTO_PAIS_VEHICULO = "PAIS_VEHICULO";
	public static final String ELEMENTO_CODIGO_ITV = "CODIGO_ITV";
	public static final String ELEMENTO_FECHA_ITV = "FECHA_ITV";
	public static final String ELEMENTO_TIPO_ITV = "TIPO_ITV";
	public static final String ELEMENTO_VARIANTE_ITV = "VARIANTE_ITV";
	public static final String ELEMENTO_VERSION_ITV = "VERSION_ITV";
	public static final String ELEMENTO_NUMERO_HOMOLOGACION_ITV = "NUMERO_HOMOLOGACION_ITV";
	public static final String ELEMENTO_MARCA = "MARCA";
	public static final String ELEMENTO_MODELO = "MODELO";
	public static final String ELEMENTO_NUMERO_BASTIDOR = "NUMERO_BASTIDOR";
	public static final String ELEMENTO_COLOR = "COLOR";
	public static final String ELEMENTO_CARBURANTE = "CARBURANTE";
	public static final String ELEMENTO_POTENCIA_FISCAL = "POTENCIA_FISCAL";
	public static final String ELEMENTO_POTENCIA_NETA = "POTENCIA_NETA";
	public static final String ELEMENTO_CILINDRADA = "CILINDRADA";
	public static final String ELEMENTO_PLAZAS = "PLAZAS";
	public static final String ELEMENTO_PLAZAS_PIE = "PLAZAS_PIE";
	public static final String ELEMENTO_TARA = "TARA";
	public static final String ELEMENTO_MASA = "MASA";
	public static final String ELEMENTO_MASA_SERVICIO = "MASA_SERVICIO";
	public static final String ELEMENTO_MASA_MAXIMA_ADMISIBLE = "MASA_MAXIMA_ADMISIBLE";
	public static final String ELEMENTO_RELACION_POTENCIA_PESO = "RELACION_POTENCIA_PESO";
	public static final String ELEMENTO_EXCESO_PESO = "EXCESO_PESO";
	public static final String ELEMENTO_TIPO_VEHICULO = "TIPO_VEHICULO";
	public static final String ELEMENTO_SERVICIO_DESTINO = "SERVICIO_DESTINO";
	public static final String ELEMENTO_PROCEDENCIA_VEHICULO = "PROCEDENCIA_VEHICULO";
	public static final String ELEMENTO_CLASIFICACION_VEHICULO = "CLASIFICACION_VEHICULO";
	public static final String ELEMENTO_CLASIFICACION = "CLASIFICACION";
	public static final String ELEMENTO_NUEVO = "NUEVO";
	public static final String ELEMENTO_USADO = "USADO";
	public static final String ELEMENTO_LUGAR_ADQUISICION = "LUGAR_ADQUISICION";
	public static final String ELEMENTO_LUGAR_MATRICULACION = "LUGAR_MATRICULACION";
	public static final String ELEMENTO_CLASIFICACION_DIRECTIVA_CEE = "CLASIFICACION_DIRECTIVA_CEE";
	public static final String ELEMENTO_EMISION_CO2 = "EMISION_CO2";
	public static final String ELEMENTO_EPIGRAFE = "EPIGRAFE";
	public static final String ELEMENTO_KM = "KM";
	public static final String ELEMENTO_NUMERO_RUEDAS = "NUMERO_RUEDAS";
	public static final String ELEMENTO_CUENTA_HORAS = "CUENTA_HORAS";
	public static final String ELEMENTO_NUMERO_SERIE_ITV = "NUMERO_SERIE_ITV";
	public static final String ELEMENTO_TIPO_NUMERO_SERIE_ITV = "TIPO_NUMERO_SERIE_ITV";
	public static final String ELEMENTO_OBSERVACIONES_VEHICULO = "OBSERVACIONES_VEHICULO";
	public static final String ELEMENTO_RENTING = "RENTING";
	public static final String ELEMENTO_EEFF = "EEFF";
	public static final String ELEMENTO_NIVE = "NIVE";
	public static final String ELEMENTO_TIPO_LIMITACION = "TIPO_LIMITACION";
	public static final String ELEMENTO_FECHA_LIMITACION = "FECHA_LIMITACION";
	public static final String ELEMENTO_NUMERO_REGISTRO_LIMITACION = "NUMERO_REGISTRO_LIMITACION";
	public static final String ELEMENTO_FINANCIERA_LIMITACION = "FINANCIERA_LIMITACION";

	public static final String ELEMENTO_TIPO_CARGA = "TIPO_CARGA";
	public static final String ELEMENTO_FECHA_CARGA = "FECHA_CARGA";
	public static final String ELEMENTO_NUMERO_REGISTRO_CARGA = "NUMERO_REGISTRO_CARGA";
	public static final String ELEMENTO_FINANCIERA_CARGA = "FINANCIERA_CARGA";

	public static final String ELEMENTO_PAGO_EFECTIVO = "PAGO_EFECTIVO";
	public static final String ELEMENTO_PAGO_POR_CUENTA = "PAGO_POR_CUENTA";
	public static final String ELEMENTO_NUMERO_CUENTA = "NUMERO_CUENTA";
	public static final String ELEMENTO_FECHA_PRESENTACION_IMPUESTO = "FECHA_PRESENTACION_IMPUESTO";
	public static final String ELEMENTO_CODIGO_ELECTRONICO_AEAT = "CODIGO_ELECTRONICO_AEAT";
	public static final String ELEMENTO_CODIGO_DELEGACION = "CODIGO_DELEGACION";
	public static final String ELEMENTO_MOTIVO_EXENCION_05 = "MOTIVO_EXENCION_05";
	public static final String ELEMENTO_MOTIVO_EXENCION_06 = "MOTIVO_EXENCION_06";
	public static final String ELEMENTO_EXENTO_576 = "EXENTO_576";
	public static final String ELEMENTO_REDUCIDO_576 = "REDUCIDO_576";
	public static final String ELEMENTO_MOTIVO_EXENCION_576 = "MOTIVO_EXENCION_576";
	public static final String ELEMENTO_BASE_IMPONIBLE_576 = "BASE_IMPONIBLE_576";
	public static final String ELEMENTO_BASE_IMPONBLE_REDUCIDA_576 = "BASE_IMPONBLE_REDUCIDA_576";
	public static final String ELEMENTO_TIPO_GRAVAMEN_576 = "TIPO_GRAVAMEN_576";
	public static final String ELEMENTO_DEDUCCION_LINEAL_576 = "DEDUCCION_LINEAL_576";
	public static final String ELEMENTO_CUOTA_576 = "CUOTA_576";
	public static final String ELEMENTO_CUOTA_INGRESAR_576 = "CUOTA_INGRESAR_576";
	public static final String ELEMENTO_A_DEDUCIR_576 = "A_DEDUCIR_576";
	public static final String ELEMENTO_IMPORTE_TOTAL_576 = "IMPORTE_TOTAL_576";
	public static final String ELEMENTO_DECLARACION_COMPLEMENTARIA_576 = "DECLARACION_COMPLEMENTARIA_576";
	public static final String ELEMENTO_MATRICULA_PREVER_576 = "MATRICULA_PREVER_576";
	public static final String ELEMENTO_TIPO_PREVER_576 = "TIPO_PREVER_576";
	public static final String ELEMENTO_MARCA_PREVER_576 = "MARCA_PREVER_576";
	public static final String ELEMENTO_MODELO_PREVER_576 = "MODELO_PREVER_576";
	public static final String ELEMENTO_NUMERO_BASTIDOR_PREVER_576 = "NUMERO_BASTIDOR_PREVER_576";
	public static final String ELEMENTO_CLASIFICACION_PREVER_576 = "CLASIFICACION_PREVER_576";
	public static final String ELEMENTO_CAUSA_HECHO_IMPONIBLE = "CAUSA_HECHO_IMPONIBLE";
	public static final String ELEMENTO_CODIGO_NRC = "CODIGO_NRC";
	public static final String ELEMENTO_IMPORTE_NRC = "IMPORTE_NRC";
	public static final String ELEMENTO_FECHA_OPERACION_NRC = "FECHA_OPERACION_NRC";
	public static final String ELEMENTO_CODIGO_ERROR_NRC = "CODIGO_ERROR_NRC";
	public static final String ELEMENTO_ORGANISMO_IMVTM = "ORGANISMO_IMVTM";
	public static final String ELEMENTO_MUNICIPIO_IMVTM = "MUNICIPIO_IMVTM";
	public static final String ELEMENTO_PROVINCIA_IMVTM = "PROVINCIA_IMVTM";
	public static final String ELEMENTO_FECHA_PROCESO_IMVTM = "FECHA_PROCESO_IMVTM";
	public static final String ELEMENTO_FECHA_ALTA_AUTOLIQUIDACION_IMVTM = "FECHA_ALTA_AUTOLIQUIDACION_IMVTM";
	public static final String ELEMENTO_ID_AUTOLIQUIDACION_IMVTM = "ID_AUTOLIQUIDACION_IMVTM";
	public static final String ELEMENTO_CODIGO_BENEFICIOS_FISCALES_IMVTM = "CODIGO_BENEFICIOS_FISCALES_IMVTM";
	public static final String ELEMENTO_PORCENTAJE_BENEFICIO_FISCAL_IMVTM = "PORCENTAJE_BENEFICIO_FISCAL_IMVTM";
	public static final String ELEMENTO_TARIFA_IMVTM = "TARIFA_IMVTM";
	public static final String ELEMENTO_CUOTA_ANUAL_IMVTM = "CUOTA_ANUAL_IMVTM";
	public static final String ELEMENTO_CUOTA_PERIODO_IMVTM = "CUOTA_PERIODO_IMVTM";
	public static final String ELEMENTO_CUOTA_A_PAGAR_IMVTM = "CUOTA_A_PAGAR_IMVTM";
	public static final String ELEMENTO_NUMERO_CONTROL_PAGO_IMVTM = "NUMERO_CONTROL_PAGO_IMVTM";
	public static final String ELEMENTO_EMISORA_RAFAGA_COBRATORIA_IMVTM = "EMISORA_RAFAGA_COBRATORIA_IMVTM";
	public static final String ELEMENTO_REF_RAFAGA_COBRATORIA_IMVTM = "REF_RAFAGA_COBRATORIA_IMVTM";
	public static final String ELEMENTO_ID_RAFAGA_COBRATORIA_IMVTM = "ID_RAFAGA_COBRATORIA_IMVTM";
	public static final String ELEMENTO_IMPORTE_RAFAGA_COBRATORIA_IMVTM = "IMPORTE_RAFAGA_COBRATORIA_IMVTM";
	public static final String ELEMENTO_NUMERO_CUENTA_IMVTM = "NUMERO_CUENTA_IMVTM";
	public static final String ELEMENTO_ERROR_IMVTM = "ERROR_IMVTM";
	public static final String ELEMENTO_FORMA_PAGO = "FORMA_PAGO";
	public static final String ELEMENTO_CUENTA = "CUENTA";
	public static final String ELEMENTO_DNI_TITULAR_CUENTA = "DNI_TITULAR_CUENTA";
	public static final String ELEMENTO_NOMBRE_TITULAR_CUENTA = "NOMBRE_TITULAR_CUENTA";
	public static final String ELEMENTO_NUMERO_TARJETA = "NUMERO_TARJETA";
	public static final String ELEMENTO_NOMBRE_TITULAR_TARJETA = "NOMBRE_TITULAR_TARJETA";
	public static final String ELEMENTO_FECHA_CADUCIDAD_TARJETA = "FECHA_CADUCIDAD_TARJETA";
	public static final String ELEMENTO_RAZON_SOCIAL_PRESENTADORIMVTM = "RAZON_SOCIAL_PRESENTADORIMVTM";
	public static final String ELEMENTO_DNI_PRESENTADORIMVTM = "DNI_PRESENTADORIMVTM";
	public static final String ELEMENTO_APELLIDO1_PRESENTADORIMVTM = "APELLIDO1_PRESENTADORIMVTM";
	public static final String ELEMENTO_APELLIDO2_PRESENTADORIMVTM = "APELLIDO2_PRESENTADORIMVTM";
	public static final String ELEMENTO_NOMBRE_PRESENTADORIMVTM = "NOMBRE_PRESENTADORIMVTM";
	public static final String ELEMENTO_FECHA_NACIMIENTO_PRESENTADORIMVTM = "FECHA_NACIMIENTO_PRESENTADORIMVTM";
	public static final String ELEMENTO_SEXO_PRESENTADORIMVTM = "SEXO_PRESENTADORIMVTM";
	public static final String ELEMENTO_SIGLAS_DIRECCION_PRESENTADORIMVTM = "SIGLAS_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_NOMBRE_VIA_DIRECCION_PRESENTADORIMVTM = "NOMBRE_VIA_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_NUMERO_DIRECCION_PRESENTADORIMVTM = "NUMERO_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_LETRA_DIRECCION_PRESENTADORIMVTM = "LETRA_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_ESCALERA_DIRECCION_PRESENTADORIMVTM = "ESCALERA_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_PISO_DIRECCION_PRESENTADORIMVTM = "PISO_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_PUERTA_DIRECCION_PRESENTADORIMVTM = "PUERTA_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_KM_DIRECCION_PRESENTADORIMVTM = "KM_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_HECTOMETRO_DIRECCION_PRESENTADORIMVTM = "HECTOMETRO_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_BLOQUE_DIRECCION_PRESENTADORIMVTM = "BLOQUE_DIRECCION_PRESENTADORIMVTM";
	public static final String ELEMENTO_MUNICIPIO_PRESENTADORIMVTM = "MUNICIPIO_PRESENTADORIMVTM";
	public static final String ELEMENTO_PUEBLO_PRESENTADORIMVTM = "PUEBLO_PRESENTADORIMVTM";
	public static final String ELEMENTO_PROVINCIA_PRESENTADORIMVTM = "PROVINCIA_PRESENTADORIMVTM";
	public static final String ELEMENTO_CP_PRESENTADORIMVTM = "CP_PRESENTADORIMVTM";
	public static final String ELEMENTO_PAIS_PRESENTADORIMVTM = "PAIS_PRESENTADORIMVTM";
	public static final String ELEMENTO_TELEFONO_PRESENTADORIMVTM = "TELEFONO_PRESENTADORIMVTM";	
	
	//620 Para la importación del fichero XML de CET
	
	public static final String AUTOLIQUIDACION_CET = "CET";
	public static final String AUTOLIQUIDACION = "autoliquidacion";
	public static final String AUTOLIQUIDACION_CODIGO = "codigo";
	public static final String AUTOLIQUIDACION_MATRICULA = "matricula";
	public static final String AUTOLIQUIDACION_DOCUMENTO = "documento_GATA";
	
	public static ArrayList<String> listaCampos;
	
	public static String devuelveErrorElementoYLinea(String linea, int numlinea) {		
		String elemento = null;
		String value = null;
		//Mantis 25415
		String cadenaValorDecimalValorReal = "is not a valid value for 'decimal'";
		if(linea.contains(cadenaValorDecimalValorReal)){
			return "Error en la etiqueta del xml " +
					" en la línea: " + numlinea + " debido a un formato erróneo. Compruebe formato prestablecido.";
		}
		
		if (listaCampos == null) {
			listaCampos = new ArrayList<String>();
			for (Field campo : XmlElementos.class.getFields()) {
				if (campo.getName().indexOf("ELEMENTO") > -1) {
					try {
						listaCampos.add(campo.get(null).toString());
					} catch (Exception ex) {
						//Nada porque sólo queremos cargar la tabla de nombres de campos
					}
				}
			}
		}
		
		if(linea.contains("Invalid content was found starting with element '")){
			int first = linea.indexOf("'");
			String campo = linea.substring(first+1, linea.indexOf("'", first+1));
			return "Error en la etiqueta del xml " + campo +
			" en la línea: " + numlinea;
		}
		
		String[] palabras = linea.split(" ");
		boolean encValue = false;
		for (String palabra : palabras) {
			if (palabra.indexOf("'") > -1 && palabra.length()>1) {
				palabra = palabra.substring(1, palabra.length() - 1);
				if (encValue) {
					encValue = false;
					value = palabra;
				}
			}
			
			if ("value".equals(palabra) || "Value".equals(palabra)) {
				encValue = true;
			}
			
			if(palabra.startsWith("\"") && palabra.endsWith("\"")){
				String palabra2 = palabra.substring(1, palabra.length()-1);
				if (listaCampos.contains(palabra2)) {
					elemento = palabra2;
				}
			}
			
			//Encontramos un campo con problemas
			if (listaCampos.contains(palabra)) {
				elemento = palabra;
			}
		}
		
		if (elemento != null) {
			String error = "Error de Formato en el campo " + elemento + " en la línea: " + numlinea;
			if (value != null && !value.isEmpty()) {
				error += ". Valor del campo: " + value;
			}
			return error;
		}
		return null; // "Error de Formato en la línea: " + numlinea;
	}
	
	public XmlElementos() {
		
	}	
}