//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 08:07:42 AM CEST 
//


package trafico.beans.jaxb.matw.dgt.tipos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoDatoConductor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoDatoConductor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Documento_Identidad" type="{http://www.dgt.es/vehiculos/tipos}TipoDocumentoIdentificacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDatoConductor", propOrder = {
    "documentoIdentidad"
})
public class TipoDatoConductor {

    @XmlElement(name = "Documento_Identidad", required = true)
    protected TipoDocumentoIdentificacion documentoIdentidad;

    /**
     * Gets the value of the documentoIdentidad property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDocumentoIdentificacion }
     *     
     */
    public TipoDocumentoIdentificacion getDocumentoIdentidad() {
        return documentoIdentidad;
    }

    /**
     * Sets the value of the documentoIdentidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDocumentoIdentificacion }
     *     
     */
    public void setDocumentoIdentidad(TipoDocumentoIdentificacion value) {
        this.documentoIdentidad = value;
    }

}
