//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.11 at 10:50:51 AM CEST 
//


package trafico.beans.transmision.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IngresoTypeO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IngresoTypeO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Entidad" type="{}boolObligatorioType"/>
 *         &lt;element name="Efectivo" type="{}boolObligatorioType"/>
 *         &lt;element name="Cuenta" type="{}boolObligatorioType"/>
 *         &lt;element name="Importe" type="{}importe17_2Type"/>
 *         &lt;element name="CCC_Entidad" type="{}cifras4Type"/>
 *         &lt;element name="CCC_Oficina" type="{}cifras4Type"/>
 *         &lt;element name="CCC_DC" type="{}cifras2Type"/>
 *         &lt;element name="CCC_Cuenta" type="{}cifras10Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IngresoTypeO", propOrder = {
    "entidad",
    "efectivo",
    "cuenta",
    "importe",
    "cccEntidad",
    "cccOficina",
    "cccdc",
    "cccCuenta"
})
public class IngresoTypeO {

    @XmlElement(name = "Entidad", required = true)
    protected String entidad;
    @XmlElement(name = "Efectivo", required = true)
    protected String efectivo;
    @XmlElement(name = "Cuenta", required = true)
    protected String cuenta;
    @XmlElement(name = "Importe", required = true)
    protected String importe;
    @XmlElement(name = "CCC_Entidad", required = true)
    protected String cccEntidad;
    @XmlElement(name = "CCC_Oficina", required = true)
    protected String cccOficina;
    @XmlElement(name = "CCC_DC", required = true)
    protected String cccdc;
    @XmlElement(name = "CCC_Cuenta", required = true)
    protected String cccCuenta;

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the efectivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEfectivo() {
        return efectivo;
    }

    /**
     * Sets the value of the efectivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEfectivo(String value) {
        this.efectivo = value;
    }

    /**
     * Gets the value of the cuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuenta() {
        return cuenta;
    }

    /**
     * Sets the value of the cuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuenta(String value) {
        this.cuenta = value;
    }

    /**
     * Gets the value of the importe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporte() {
        return importe;
    }

    /**
     * Sets the value of the importe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporte(String value) {
        this.importe = value;
    }

    /**
     * Gets the value of the cccEntidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCCEntidad() {
        return cccEntidad;
    }

    /**
     * Sets the value of the cccEntidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCCEntidad(String value) {
        this.cccEntidad = value;
    }

    /**
     * Gets the value of the cccOficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCCOficina() {
        return cccOficina;
    }

    /**
     * Sets the value of the cccOficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCCOficina(String value) {
        this.cccOficina = value;
    }

    /**
     * Gets the value of the cccdc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCCDC() {
        return cccdc;
    }

    /**
     * Sets the value of the cccdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCCDC(String value) {
        this.cccdc = value;
    }

    /**
     * Gets the value of the cccCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCCCuenta() {
        return cccCuenta;
    }

    /**
     * Sets the value of the cccCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCCCuenta(String value) {
        this.cccCuenta = value;
    }

}
