//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 04:30:48 PM CET 
//


package trafico.beans.transmision.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for provinciaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="provinciaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value=""/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="07"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="09"/>
 *     &lt;enumeration value="10"/>
 *     &lt;enumeration value="11"/>
 *     &lt;enumeration value="12"/>
 *     &lt;enumeration value="13"/>
 *     &lt;enumeration value="14"/>
 *     &lt;enumeration value="15"/>
 *     &lt;enumeration value="16"/>
 *     &lt;enumeration value="17"/>
 *     &lt;enumeration value="18"/>
 *     &lt;enumeration value="19"/>
 *     &lt;enumeration value="20"/>
 *     &lt;enumeration value="21"/>
 *     &lt;enumeration value="22"/>
 *     &lt;enumeration value="23"/>
 *     &lt;enumeration value="24"/>
 *     &lt;enumeration value="25"/>
 *     &lt;enumeration value="26"/>
 *     &lt;enumeration value="27"/>
 *     &lt;enumeration value="29"/>
 *     &lt;enumeration value="30"/>
 *     &lt;enumeration value="31"/>
 *     &lt;enumeration value="32"/>
 *     &lt;enumeration value="33"/>
 *     &lt;enumeration value="34"/>
 *     &lt;enumeration value="35"/>
 *     &lt;enumeration value="36"/>
 *     &lt;enumeration value="37"/>
 *     &lt;enumeration value="38"/>
 *     &lt;enumeration value="39"/>
 *     &lt;enumeration value="40"/>
 *     &lt;enumeration value="41"/>
 *     &lt;enumeration value="42"/>
 *     &lt;enumeration value="43"/>
 *     &lt;enumeration value="44"/>
 *     &lt;enumeration value="45"/>
 *     &lt;enumeration value="46"/>
 *     &lt;enumeration value="47"/>
 *     &lt;enumeration value="48"/>
 *     &lt;enumeration value="49"/>
 *     &lt;enumeration value="50"/>
 *     &lt;enumeration value="51"/>
 *     &lt;enumeration value="52"/>
 *     &lt;enumeration value="88"/>
 *     &lt;enumeration value="28"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "provinciaType")
@XmlEnum
public enum ProvinciaType {

    @XmlEnumValue("")
    VALUE_1(""),
    @XmlEnumValue("01")
    VALUE_2("01"),
    @XmlEnumValue("02")
    VALUE_3("02"),
    @XmlEnumValue("03")
    VALUE_4("03"),
    @XmlEnumValue("04")
    VALUE_5("04"),
    @XmlEnumValue("05")
    VALUE_6("05"),
    @XmlEnumValue("06")
    VALUE_7("06"),
    @XmlEnumValue("07")
    VALUE_8("07"),
    @XmlEnumValue("08")
    VALUE_9("08"),
    @XmlEnumValue("09")
    VALUE_10("09"),
    @XmlEnumValue("10")
    VALUE_11("10"),
    @XmlEnumValue("11")
    VALUE_12("11"),
    @XmlEnumValue("12")
    VALUE_13("12"),
    @XmlEnumValue("13")
    VALUE_14("13"),
    @XmlEnumValue("14")
    VALUE_15("14"),
    @XmlEnumValue("15")
    VALUE_16("15"),
    @XmlEnumValue("16")
    VALUE_17("16"),
    @XmlEnumValue("17")
    VALUE_18("17"),
    @XmlEnumValue("18")
    VALUE_19("18"),
    @XmlEnumValue("19")
    VALUE_20("19"),
    @XmlEnumValue("20")
    VALUE_21("20"),
    @XmlEnumValue("21")
    VALUE_22("21"),
    @XmlEnumValue("22")
    VALUE_23("22"),
    @XmlEnumValue("23")
    VALUE_24("23"),
    @XmlEnumValue("24")
    VALUE_25("24"),
    @XmlEnumValue("25")
    VALUE_26("25"),
    @XmlEnumValue("26")
    VALUE_27("26"),
    @XmlEnumValue("27")
    VALUE_28("27"),
    @XmlEnumValue("29")
    VALUE_29("29"),
    @XmlEnumValue("30")
    VALUE_30("30"),
    @XmlEnumValue("31")
    VALUE_31("31"),
    @XmlEnumValue("32")
    VALUE_32("32"),
    @XmlEnumValue("33")
    VALUE_33("33"),
    @XmlEnumValue("34")
    VALUE_34("34"),
    @XmlEnumValue("35")
    VALUE_35("35"),
    @XmlEnumValue("36")
    VALUE_36("36"),
    @XmlEnumValue("37")
    VALUE_37("37"),
    @XmlEnumValue("38")
    VALUE_38("38"),
    @XmlEnumValue("39")
    VALUE_39("39"),
    @XmlEnumValue("40")
    VALUE_40("40"),
    @XmlEnumValue("41")
    VALUE_41("41"),
    @XmlEnumValue("42")
    VALUE_42("42"),
    @XmlEnumValue("43")
    VALUE_43("43"),
    @XmlEnumValue("44")
    VALUE_44("44"),
    @XmlEnumValue("45")
    VALUE_45("45"),
    @XmlEnumValue("46")
    VALUE_46("46"),
    @XmlEnumValue("47")
    VALUE_47("47"),
    @XmlEnumValue("48")
    VALUE_48("48"),
    @XmlEnumValue("49")
    VALUE_49("49"),
    @XmlEnumValue("50")
    VALUE_50("50"),
    @XmlEnumValue("51")
    VALUE_51("51"),
    @XmlEnumValue("52")
    VALUE_52("52"),
    @XmlEnumValue("88")
    VALUE_53("88"),
    @XmlEnumValue("28")
    VALUE_54("28");
    private final String value;

    ProvinciaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProvinciaType fromValue(String v) {
        for (ProvinciaType c: ProvinciaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
