//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 12:16:45 PM CET 
//


package trafico.beans.jaxb.solicitud;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}MATRICULA" minOccurs="0"/>
 *         &lt;element ref="{}NUMERO_BASTIDOR" minOccurs="0"/>
 *         &lt;element ref="{}TIPO_TASA" minOccurs="0"/>
 *         &lt;element ref="{}CODIGO_TASA" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DATOS_VEHICULO")
public class DATOSVEHICULO {

    @XmlElement(name = "MATRICULA")
    protected String matricula;
    @XmlElement(name = "NUMERO_BASTIDOR")
    protected String numerobastidor;
    @XmlElement(name = "TIPO_TASA")
    protected String tipotasa;
    @XmlElement(name = "CODIGO_TASA")
    protected String codigotasa;
    @XmlElement(name = "MOTIVO")
    protected String motivo;

    /**
     * Gets the value of the matricula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATRICULA() {
        return matricula;
    }

    public String getMOTIVO() {
		return motivo;
	}

	public void setMOTIVO(String motivo) {
		this.motivo = motivo;
	}

	/**
     * Sets the value of the matricula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATRICULA(String value) {
        this.matricula = value;
    }

    /**
     * Gets the value of the numerobastidor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMEROBASTIDOR() {
        return numerobastidor;
    }

    /**
     * Sets the value of the numerobastidor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMEROBASTIDOR(String value) {
        this.numerobastidor = value;
    }

    /**
     * Gets the value of the tipotasa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOTASA() {
        return tipotasa;
    }

    /**
     * Sets the value of the tipotasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOTASA(String value) {
        this.tipotasa = value;
    }

    /**
     * Gets the value of the codigotasa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOTASA() {
        return codigotasa;
    }

    /**
     * Sets the value of the codigotasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOTASA(String value) {
        this.codigotasa = value;
    }

}
