//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 11:23:32 AM CET 
//


package trafico.beans.jaxb.solicitud;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DATOS_SOLICITUD" minOccurs="0"/>
 *         &lt;element ref="{}DATOS_SOLICITANTE" minOccurs="0"/>
 *         &lt;element ref="{}DATOS_VEHICULO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datossolicitud",
    "datossolicitante",
    "datosvehiculo"
})
@XmlRootElement(name = "SOLICITUD")
public class SOLICITUD {

    @XmlElement(name = "DATOS_SOLICITUD")
    protected DATOSSOLICITUD datossolicitud;
    @XmlElement(name = "DATOS_SOLICITANTE")
    protected DATOSSOLICITANTE datossolicitante;
    @XmlElement(name = "DATOS_VEHICULO")
    protected List<DATOSVEHICULO> datosvehiculo;

    /**
     * Gets the value of the datossolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link DATOSSOLICITUD }
     *     
     */
    public DATOSSOLICITUD getDATOSSOLICITUD() {
        return datossolicitud;
    }

    /**
     * Sets the value of the datossolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATOSSOLICITUD }
     *     
     */
    public void setDATOSSOLICITUD(DATOSSOLICITUD value) {
        this.datossolicitud = value;
    }

    /**
     * Gets the value of the datossolicitante property.
     * 
     * @return
     *     possible object is
     *     {@link DATOSSOLICITANTE }
     *     
     */
    public DATOSSOLICITANTE getDATOSSOLICITANTE() {
        return datossolicitante;
    }

    /**
     * Sets the value of the datossolicitante property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATOSSOLICITANTE }
     *     
     */
    public void setDATOSSOLICITANTE(DATOSSOLICITANTE value) {
        this.datossolicitante = value;
    }

    /**
     * Gets the value of the datosvehiculo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datosvehiculo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATOSVEHICULO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DATOSVEHICULO }
     * 
     * 
     */
    public List<DATOSVEHICULO> getDATOSVEHICULO() {
        if (datosvehiculo == null) {
            datosvehiculo = new ArrayList<DATOSVEHICULO>();
        }
        return this.datosvehiculo;
    }
    
    public List<DATOSVEHICULO> getDatosVehiculo() {
		return datosvehiculo;
	}

	public void setDATOSVEHICULO(List<DATOSVEHICULO> datosvehiculo) {
		this.datosvehiculo = datosvehiculo;
	}

}
