//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 10:57:32 AM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.view.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Domicilio_INEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Domicilio_INEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pais">
 *           &lt;simpleType>
 *             &lt;restriction base="{}Tipificacion_PaisType">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Estado_Region_Provincia_Extranjera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cod_Provincia" type="{}Tipificacion_ProvinciaType"/>
 *         &lt;element name="Cod_Municipio" type="{}Tipificacion_MunicipioType"/>
 *         &lt;element name="Entidad_Local_Menor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cod_Tipo_Via" type="{}Tipificacion_Tipo_ViaType"/>
 *         &lt;element name="Nombre_Via" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Punto_Kilometrico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Numero" type="{}NumericoType"/>
 *         &lt;element name="Numero_Bis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Portal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Bloque" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Escalera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Planta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Puerta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Codigo_Postal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Lugar_Ubicacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Domicilio_INEType", propOrder = {
    "pais",
    "estadoRegionProvinciaExtranjera",
    "codProvincia",
    "codMunicipio",
    "entidadLocalMenor",
    "codTipoVia",
    "nombreVia",
    "puntoKilometrico",
    "numero",
    "numeroBis",
    "portal",
    "bloque",
    "escalera",
    "planta",
    "puerta",
    "codigoPostal",
    "lugarUbicacion"
})
public class DomicilioINEType {

    @XmlElement(name = "Pais", required = true)
    protected String pais;
    @XmlElement(name = "Estado_Region_Provincia_Extranjera", required = true)
    protected String estadoRegionProvinciaExtranjera;
    @XmlElement(name = "Cod_Provincia", required = true)
    protected String codProvincia;
    @XmlElement(name = "Cod_Municipio", required = true)
    protected String codMunicipio;
    @XmlElement(name = "Entidad_Local_Menor", required = true)
    protected String entidadLocalMenor;
    @XmlElement(name = "Cod_Tipo_Via", required = true)
    protected String codTipoVia;
    @XmlElement(name = "Nombre_Via", required = true)
    protected String nombreVia;
    @XmlElement(name = "Punto_Kilometrico", required = true)
    protected String puntoKilometrico;
    @XmlElement(name = "Numero", required = true)
    protected String numero;
    @XmlElement(name = "Numero_Bis", required = true)
    protected String numeroBis;
    @XmlElement(name = "Portal", required = true)
    protected String portal;
    @XmlElement(name = "Bloque", required = true)
    protected String bloque;
    @XmlElement(name = "Escalera", required = true)
    protected String escalera;
    @XmlElement(name = "Planta", required = true)
    protected String planta;
    @XmlElement(name = "Puerta", required = true)
    protected String puerta;
    @XmlElement(name = "Codigo_Postal", required = true)
    protected String codigoPostal;
    @XmlElement(name = "Lugar_Ubicacion")
    protected String lugarUbicacion;

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the estadoRegionProvinciaExtranjera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoRegionProvinciaExtranjera() {
        return estadoRegionProvinciaExtranjera;
    }

    /**
     * Sets the value of the estadoRegionProvinciaExtranjera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoRegionProvinciaExtranjera(String value) {
        this.estadoRegionProvinciaExtranjera = value;
    }

    /**
     * Gets the value of the codProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProvincia() {
        return codProvincia;
    }

    /**
     * Sets the value of the codProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProvincia(String value) {
        this.codProvincia = value;
    }

    /**
     * Gets the value of the codMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMunicipio() {
        return codMunicipio;
    }

    /**
     * Sets the value of the codMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMunicipio(String value) {
        this.codMunicipio = value;
    }

    /**
     * Gets the value of the entidadLocalMenor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidadLocalMenor() {
        return entidadLocalMenor;
    }

    /**
     * Sets the value of the entidadLocalMenor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidadLocalMenor(String value) {
        this.entidadLocalMenor = value;
    }

    /**
     * Gets the value of the codTipoVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodTipoVia() {
        return codTipoVia;
    }

    /**
     * Sets the value of the codTipoVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodTipoVia(String value) {
        this.codTipoVia = value;
    }

    /**
     * Gets the value of the nombreVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreVia() {
        return nombreVia;
    }

    /**
     * Sets the value of the nombreVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreVia(String value) {
        this.nombreVia = value;
    }

    /**
     * Gets the value of the puntoKilometrico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuntoKilometrico() {
        return puntoKilometrico;
    }

    /**
     * Sets the value of the puntoKilometrico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuntoKilometrico(String value) {
        this.puntoKilometrico = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the numeroBis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroBis() {
        return numeroBis;
    }

    /**
     * Sets the value of the numeroBis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroBis(String value) {
        this.numeroBis = value;
    }

    /**
     * Gets the value of the portal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortal() {
        return portal;
    }

    /**
     * Sets the value of the portal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortal(String value) {
        this.portal = value;
    }

    /**
     * Gets the value of the bloque property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloque() {
        return bloque;
    }

    /**
     * Sets the value of the bloque property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloque(String value) {
        this.bloque = value;
    }

    /**
     * Gets the value of the escalera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEscalera() {
        return escalera;
    }

    /**
     * Sets the value of the escalera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEscalera(String value) {
        this.escalera = value;
    }

    /**
     * Gets the value of the planta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanta() {
        return planta;
    }

    /**
     * Sets the value of the planta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanta(String value) {
        this.planta = value;
    }

    /**
     * Gets the value of the puerta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuerta() {
        return puerta;
    }

    /**
     * Sets the value of the puerta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuerta(String value) {
        this.puerta = value;
    }

    /**
     * Gets the value of the codigoPostal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoPostal() {
        return codigoPostal;
    }

    /**
     * Sets the value of the codigoPostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoPostal(String value) {
        this.codigoPostal = value;
    }

    /**
     * Gets the value of the lugarUbicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLugarUbicacion() {
        return lugarUbicacion;
    }

    /**
     * Sets the value of the lugarUbicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLugarUbicacion(String value) {
        this.lugarUbicacion = value;
    }

}
