//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 10:57:32 AM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.view.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Identificacion_Contrato_InscritoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identificacion_Contrato_InscritoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Entidad_Titular_Suscriptora" type="{}Entidad_Titular_SuscriptoraType"/>
 *         &lt;element name="Entidad_Sucesora" type="{}Entidad_SucesoraType" minOccurs="0"/>
 *         &lt;element name="Numero_Impreso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Datos_Inscripcion" type="{}Datos_InscripcionType" minOccurs="0"/>
 *         &lt;element name="Comprador_Arrendatario" type="{}Comprador_ArrendatarioType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identificacion_Contrato_InscritoType", propOrder = {
    "entidadTitularSuscriptora",
    "entidadSucesora",
    "numeroImpreso",
    "datosInscripcion",
    "compradorArrendatario"
})
public class IdentificacionContratoInscritoType {

    @XmlElement(name = "Entidad_Titular_Suscriptora", required = true)
    protected EntidadTitularSuscriptoraType entidadTitularSuscriptora;
    @XmlElement(name = "Entidad_Sucesora")
    protected EntidadSucesoraType entidadSucesora;
    @XmlElement(name = "Numero_Impreso")
    protected String numeroImpreso;
    @XmlElement(name = "Datos_Inscripcion")
    protected DatosInscripcionType datosInscripcion;
    @XmlElement(name = "Comprador_Arrendatario")
    protected List<CompradorArrendatarioType> compradorArrendatario;

    /**
     * Gets the value of the entidadTitularSuscriptora property.
     * 
     * @return
     *     possible object is
     *     {@link EntidadTitularSuscriptoraType }
     *     
     */
    public EntidadTitularSuscriptoraType getEntidadTitularSuscriptora() {
        return entidadTitularSuscriptora;
    }

    /**
     * Sets the value of the entidadTitularSuscriptora property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntidadTitularSuscriptoraType }
     *     
     */
    public void setEntidadTitularSuscriptora(EntidadTitularSuscriptoraType value) {
        this.entidadTitularSuscriptora = value;
    }

    /**
     * Gets the value of the entidadSucesora property.
     * 
     * @return
     *     possible object is
     *     {@link EntidadSucesoraType }
     *     
     */
    public EntidadSucesoraType getEntidadSucesora() {
        return entidadSucesora;
    }

    /**
     * Sets the value of the entidadSucesora property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntidadSucesoraType }
     *     
     */
    public void setEntidadSucesora(EntidadSucesoraType value) {
        this.entidadSucesora = value;
    }

    /**
     * Gets the value of the numeroImpreso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroImpreso() {
        return numeroImpreso;
    }

    /**
     * Sets the value of the numeroImpreso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroImpreso(String value) {
        this.numeroImpreso = value;
    }

    /**
     * Gets the value of the datosInscripcion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosInscripcionType }
     *     
     */
    public DatosInscripcionType getDatosInscripcion() {
        return datosInscripcion;
    }

    /**
     * Sets the value of the datosInscripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosInscripcionType }
     *     
     */
    public void setDatosInscripcion(DatosInscripcionType value) {
        this.datosInscripcion = value;
    }

    /**
     * Gets the value of the compradorArrendatario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compradorArrendatario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompradorArrendatario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompradorArrendatarioType }
     * 
     * 
     */
    public List<CompradorArrendatarioType> getCompradorArrendatario() {
        if (compradorArrendatario == null) {
            compradorArrendatario = new ArrayList<CompradorArrendatarioType>();
        }
        return this.compradorArrendatario;
    }

}
