//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 10:57:32 AM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.view.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InscripcionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InscripcionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Des_Bien_Mueble" type="{}Des_Bien_MuebleType"/>
 *         &lt;element name="Numero_Bien" type="{}NumericoType"/>
 *         &lt;element name="Folio_Bien" type="{}NumericoType"/>
 *         &lt;element name="Fecha_Inscripcion" type="{}FechaType"/>
 *         &lt;element name="Avisos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Aviso" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InscripcionType", propOrder = {
    "desBienMueble",
    "numeroBien",
    "folioBien",
    "fechaInscripcion",
    "avisos"
})
public class InscripcionType {

    @XmlElement(name = "Des_Bien_Mueble", required = true)
    protected DesBienMuebleType desBienMueble;
    @XmlElement(name = "Numero_Bien", required = true)
    protected String numeroBien;
    @XmlElement(name = "Folio_Bien", required = true)
    protected String folioBien;
    @XmlElement(name = "Fecha_Inscripcion", required = true)
    protected String fechaInscripcion;
    @XmlElement(name = "Avisos")
    protected InscripcionType.Avisos avisos;

    /**
     * Gets the value of the desBienMueble property.
     * 
     * @return
     *     possible object is
     *     {@link DesBienMuebleType }
     *     
     */
    public DesBienMuebleType getDesBienMueble() {
        return desBienMueble;
    }

    /**
     * Sets the value of the desBienMueble property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesBienMuebleType }
     *     
     */
    public void setDesBienMueble(DesBienMuebleType value) {
        this.desBienMueble = value;
    }

    /**
     * Gets the value of the numeroBien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroBien() {
        return numeroBien;
    }

    /**
     * Sets the value of the numeroBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroBien(String value) {
        this.numeroBien = value;
    }

    /**
     * Gets the value of the folioBien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioBien() {
        return folioBien;
    }

    /**
     * Sets the value of the folioBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioBien(String value) {
        this.folioBien = value;
    }

    /**
     * Gets the value of the fechaInscripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaInscripcion() {
        return fechaInscripcion;
    }

    /**
     * Sets the value of the fechaInscripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInscripcion(String value) {
        this.fechaInscripcion = value;
    }

    /**
     * Gets the value of the avisos property.
     * 
     * @return
     *     possible object is
     *     {@link InscripcionType.Avisos }
     *     
     */
    public InscripcionType.Avisos getAvisos() {
        return avisos;
    }

    /**
     * Sets the value of the avisos property.
     * 
     * @param value
     *     allowed object is
     *     {@link InscripcionType.Avisos }
     *     
     */
    public void setAvisos(InscripcionType.Avisos value) {
        this.avisos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Aviso" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aviso"
    })
    public static class Avisos {

        @XmlElement(name = "Aviso")
        protected List<String> aviso;

        /**
         * Gets the value of the aviso property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aviso property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAviso().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAviso() {
            if (aviso == null) {
                aviso = new ArrayList<String>();
            }
            return this.aviso;
        }

    }

}
