//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 10:57:32 AM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.view.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PactoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PactoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tipo_Pacto" type="{}Tipificacion_Tipo_PactoType"/>
 *         &lt;element name="Pactado_SN" type="{}Tipificacion_Si_NoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PactoType", propOrder = {
    "tipoPacto",
    "pactadoSN"
})
public class PactoType {

    @XmlElement(name = "Tipo_Pacto", required = true)
    protected String tipoPacto;
    @XmlElement(name = "Pactado_SN", required = true)
    protected String pactadoSN;

    /**
     * Gets the value of the tipoPacto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPacto() {
        return tipoPacto;
    }

    /**
     * Sets the value of the tipoPacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPacto(String value) {
        this.tipoPacto = value;
    }

    /**
     * Gets the value of the pactadoSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPactadoSN() {
        return pactadoSN;
    }

    /**
     * Sets the value of the pactadoSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPactadoSN(String value) {
        this.pactadoSN = value;
    }

}
