//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:05:31 AM CEST 
//


package org.gestoresmadrid.oegam2comun.atex5.xml.vehiculo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for limitacionesDisposicion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="limitacionesDisposicion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="limitacionDisposicion" type="{}limitacionDisposicion" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "limitacionesDisposicion", propOrder = {
    "limitacionDisposicion"
})
public class LimitacionesDisposicion {

    protected LimitacionDisposicion limitacionDisposicion;

    /**
     * Gets the value of the limitacionDisposicion property.
     * 
     * @return
     *     possible object is
     *     {@link LimitacionDisposicion }
     *     
     */
    public LimitacionDisposicion getLimitacionDisposicion() {
        return limitacionDisposicion;
    }

    /**
     * Sets the value of the limitacionDisposicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitacionDisposicion }
     *     
     */
    public void setLimitacionDisposicion(LimitacionDisposicion value) {
        this.limitacionDisposicion = value;
    }

}
