//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:05:31 AM CEST 
//


package org.gestoresmadrid.oegam2comun.atex5.xml.vehiculo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for masas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="masas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="masaMaxTecnica" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="masaMaxima" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="masaServicio" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pesoMaximo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tara" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "masas", propOrder = {
    "masaMaxTecnica",
    "masaMaxima",
    "masaServicio",
    "pesoMaximo",
    "tara"
})
public class Masas {

    protected Integer masaMaxTecnica;
    protected Integer masaMaxima;
    protected Integer masaServicio;
    protected Integer pesoMaximo;
    protected Integer tara;

    /**
     * Gets the value of the masaMaxTecnica property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMasaMaxTecnica() {
        return masaMaxTecnica;
    }

    /**
     * Sets the value of the masaMaxTecnica property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMasaMaxTecnica(Integer value) {
        this.masaMaxTecnica = value;
    }

    /**
     * Gets the value of the masaMaxima property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMasaMaxima() {
        return masaMaxima;
    }

    /**
     * Sets the value of the masaMaxima property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMasaMaxima(Integer value) {
        this.masaMaxima = value;
    }

    /**
     * Gets the value of the masaServicio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMasaServicio() {
        return masaServicio;
    }

    /**
     * Sets the value of the masaServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMasaServicio(Integer value) {
        this.masaServicio = value;
    }

    /**
     * Gets the value of the pesoMaximo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPesoMaximo() {
        return pesoMaximo;
    }

    /**
     * Sets the value of the pesoMaximo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPesoMaximo(Integer value) {
        this.pesoMaximo = value;
    }

    /**
     * Gets the value of the tara property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTara() {
        return tara;
    }

    /**
     * Sets the value of the tara property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTara(Integer value) {
        this.tara = value;
    }

}
