//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 11:05:31 AM CEST 
//


package org.gestoresmadrid.oegam2comun.atex5.xml.vehiculo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for precinto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="precinto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accionJudicial" type="{}accionJudicial" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "precinto", propOrder = {
    "accionJudicial"
})
public class Precinto {

    protected AccionJudicial accionJudicial;

    /**
     * Gets the value of the accionJudicial property.
     * 
     * @return
     *     possible object is
     *     {@link AccionJudicial }
     *     
     */
    public AccionJudicial getAccionJudicial() {
        return accionJudicial;
    }

    /**
     * Sets the value of the accionJudicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccionJudicial }
     *     
     */
    public void setAccionJudicial(AccionJudicial value) {
        this.accionJudicial = value;
    }

}
