//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 01:31:28 PM CET 
//


package org.gestoresmadrid.oegamConversiones.jaxb.duplicado;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enumTipoPersona.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumTipoPersona">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FISICA"/>
 *     &lt;enumeration value="JURIDICA"/>
 *     &lt;enumeration value="JURIDICA_PUBLICA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enumTipoPersona")
@XmlEnum
public enum EnumTipoPersona {

    FISICA,
    JURIDICA,
    JURIDICA_PUBLICA;

    public String value() {
        return name();
    }

    public static EnumTipoPersona fromValue(String v) {
        return valueOf(v);
    }

}
