//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 12:34:00 PM CEST 
//

package es.iam.sbae.sbintopexterna.jaxb.tipos.latest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.iam.sbae.sbintopexterna.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Errores_QNAME = new QName("http://ws.iam.munimadrid.es", "errores");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.iam.sbae.sbintopexterna.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModificacionProyectoAutoliquidacionIVTMResponse }
     * 
     */
    public ModificacionProyectoAutoliquidacionIVTMResponse createModificacionProyectoAutoliquidacionIVTMResponse() {
        return new ModificacionProyectoAutoliquidacionIVTMResponse();
    }

    /**
     * Create an instance of {@link ModificacionProyectoAutoliquidacionIVTMResponseType }
     * 
     */
    public ModificacionProyectoAutoliquidacionIVTMResponseType createModificacionProyectoAutoliquidacionIVTMResponseType() {
        return new ModificacionProyectoAutoliquidacionIVTMResponseType();
    }

    /**
     * Create an instance of {@link AltaProyectoAutoliquidacionIVTM }
     * 
     */
    public AltaProyectoAutoliquidacionIVTM createAltaProyectoAutoliquidacionIVTM() {
        return new AltaProyectoAutoliquidacionIVTM();
    }

    /**
     * Create an instance of {@link AltaProyectoAutoliquidacionIVTMRequestType }
     * 
     */
    public AltaProyectoAutoliquidacionIVTMRequestType createAltaProyectoAutoliquidacionIVTMRequestType() {
        return new AltaProyectoAutoliquidacionIVTMRequestType();
    }

    /**
     * Create an instance of {@link ConsultaDeudasIVTM }
     * 
     */
    public ConsultaDeudasIVTM createConsultaDeudasIVTM() {
        return new ConsultaDeudasIVTM();
    }

    /**
     * Create an instance of {@link ConsultaDeudasIVTMRequestType }
     * 
     */
    public ConsultaDeudasIVTMRequestType createConsultaDeudasIVTMRequestType() {
        return new ConsultaDeudasIVTMRequestType();
    }

    /**
     * Create an instance of {@link AsociacionMatriculaResponse }
     * 
     */
    public AsociacionMatriculaResponse createAsociacionMatriculaResponse() {
        return new AsociacionMatriculaResponse();
    }

    /**
     * Create an instance of {@link AsociacionMatriculaResponseType }
     * 
     */
    public AsociacionMatriculaResponseType createAsociacionMatriculaResponseType() {
        return new AsociacionMatriculaResponseType();
    }

    /**
     * Create an instance of {@link AltaProyectoAutoliquidacionIVTMResponse }
     * 
     */
    public AltaProyectoAutoliquidacionIVTMResponse createAltaProyectoAutoliquidacionIVTMResponse() {
        return new AltaProyectoAutoliquidacionIVTMResponse();
    }

    /**
     * Create an instance of {@link AltaProyectoAutoliquidacionIVTMResponseType }
     * 
     */
    public AltaProyectoAutoliquidacionIVTMResponseType createAltaProyectoAutoliquidacionIVTMResponseType() {
        return new AltaProyectoAutoliquidacionIVTMResponseType();
    }

    /**
     * Create an instance of {@link ModificacionProyectoAutoliquidacionIVTM }
     * 
     */
    public ModificacionProyectoAutoliquidacionIVTM createModificacionProyectoAutoliquidacionIVTM() {
        return new ModificacionProyectoAutoliquidacionIVTM();
    }

    /**
     * Create an instance of {@link ModificacionProyectoAutoliquidacionIVTMRequestType }
     * 
     */
    public ModificacionProyectoAutoliquidacionIVTMRequestType createModificacionProyectoAutoliquidacionIVTMRequestType() {
        return new ModificacionProyectoAutoliquidacionIVTMRequestType();
    }

    /**
     * Create an instance of {@link AsociacionMatricula }
     * 
     */
    public AsociacionMatricula createAsociacionMatricula() {
        return new AsociacionMatricula();
    }

    /**
     * Create an instance of {@link AsociacionMatriculaRequestType }
     * 
     */
    public AsociacionMatriculaRequestType createAsociacionMatriculaRequestType() {
        return new AsociacionMatriculaRequestType();
    }

    /**
     * Create an instance of {@link ConsultaDeudasIVTMResponse }
     * 
     */
    public ConsultaDeudasIVTMResponse createConsultaDeudasIVTMResponse() {
        return new ConsultaDeudasIVTMResponse();
    }

    /**
     * Create an instance of {@link ConsultaDeudasIVTMResponseType }
     * 
     */
    public ConsultaDeudasIVTMResponseType createConsultaDeudasIVTMResponseType() {
        return new ConsultaDeudasIVTMResponseType();
    }

    /**
     * Create an instance of {@link ErroresType }
     * 
     */
    public ErroresType createErroresType() {
        return new ErroresType();
    }

    /**
     * Create an instance of {@link SujetoType }
     * 
     */
    public SujetoType createSujetoType() {
        return new SujetoType();
    }

    /**
     * Create an instance of {@link ValidacionasociacionTipo }
     * 
     */
    public ValidacionasociacionTipo createValidacionasociacionTipo() {
        return new ValidacionasociacionTipo();
    }

    /**
     * Create an instance of {@link VehiculoType }
     * 
     */
    public VehiculoType createVehiculoType() {
        return new VehiculoType();
    }

    /**
     * Create an instance of {@link AsociacionTipo }
     * 
     */
    public AsociacionTipo createAsociacionTipo() {
        return new AsociacionTipo();
    }

    /**
     * Create an instance of {@link DomicilioTipo }
     * 
     */
    public DomicilioTipo createDomicilioTipo() {
        return new DomicilioTipo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErroresType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.iam.munimadrid.es", name = "errores")
    public JAXBElement<ErroresType> createErrores(ErroresType value) {
        return new JAXBElement<ErroresType>(_Errores_QNAME, ErroresType.class, null, value);
    }
    

}
