//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Calificacion_Documento_Con_DefectoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Calificacion_Documento_Con_DefectoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Fecha_Calificacion" type="{}FechaType" minOccurs="0"/>
 *         &lt;element name="Defectos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Defecto" type="{}DefectoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Calificacion_Documento_Con_DefectoType", propOrder = {
    "fechaCalificacion",
    "defectos"
})
public class CalificacionDocumentoConDefectoType {

    @XmlElement(name = "Fecha_Calificacion")
    protected String fechaCalificacion;
    @XmlElement(name = "Defectos")
    protected CalificacionDocumentoConDefectoType.Defectos defectos;

    /**
     * Gets the value of the fechaCalificacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaCalificacion() {
        return fechaCalificacion;
    }

    /**
     * Sets the value of the fechaCalificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaCalificacion(String value) {
        this.fechaCalificacion = value;
    }

    /**
     * Gets the value of the defectos property.
     * 
     * @return
     *     possible object is
     *     {@link CalificacionDocumentoConDefectoType.Defectos }
     *     
     */
    public CalificacionDocumentoConDefectoType.Defectos getDefectos() {
        return defectos;
    }

    /**
     * Sets the value of the defectos property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalificacionDocumentoConDefectoType.Defectos }
     *     
     */
    public void setDefectos(CalificacionDocumentoConDefectoType.Defectos value) {
        this.defectos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Defecto" type="{}DefectoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "defecto"
    })
    public static class Defectos {

        @XmlElement(name = "Defecto")
        protected List<DefectoType> defecto;

        /**
         * Gets the value of the defecto property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the defecto property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDefecto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DefectoType }
         * 
         * 
         */
        public List<DefectoType> getDefecto() {
            if (defecto == null) {
                defecto = new ArrayList<DefectoType>();
            }
            return this.defecto;
        }

    }

}
