//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Clasificacion_BuqueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Clasificacion_BuqueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tipo_Embarcacion" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SubTipo_Embarcacion" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Clasificacion_BuqueType", propOrder = {
    "tipoEmbarcacion",
    "subTipoEmbarcacion"
})
public class ClasificacionBuqueType {

    @XmlElement(name = "Tipo_Embarcacion")
    protected Object tipoEmbarcacion;
    @XmlElement(name = "SubTipo_Embarcacion")
    protected Object subTipoEmbarcacion;

    /**
     * Gets the value of the tipoEmbarcacion property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTipoEmbarcacion() {
        return tipoEmbarcacion;
    }

    /**
     * Sets the value of the tipoEmbarcacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTipoEmbarcacion(Object value) {
        this.tipoEmbarcacion = value;
    }

    /**
     * Gets the value of the subTipoEmbarcacion property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSubTipoEmbarcacion() {
        return subTipoEmbarcacion;
    }

    /**
     * Sets the value of the subTipoEmbarcacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSubTipoEmbarcacion(Object value) {
        this.subTipoEmbarcacion = value;
    }

}
