//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Identificacion_Bien_CancelacionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identificacion_Bien_CancelacionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Clase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Marca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Modelo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Matricula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Bastidor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Numero_Fabricacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="Maquinaria" type="{}MaquinariaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Establecimiento" type="{}EstablecimientoMercantilType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Buque" type="{}BuqueType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Aeronave" type="{}AeronaveType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Propiedad_Industrial" type="{}Propiedad_IndustrialType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Propiedad_Intelectual" type="{}Propiedad_IntelectualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Otros_Bienes" type="{}Otros_BienesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identificacion_Bien_CancelacionType", propOrder = {
    "clase",
    "marca",
    "modelo",
    "matricula",
    "bastidor",
    "numeroFabricacion",
    "maquinaria",
    "establecimiento",
    "buque",
    "aeronave",
    "propiedadIndustrial",
    "propiedadIntelectual",
    "otrosBienes"
})
public class IdentificacionBienCancelacionType {

    @XmlElement(name = "Clase")
    protected String clase;
    @XmlElement(name = "Marca")
    protected String marca;
    @XmlElement(name = "Modelo")
    protected String modelo;
    @XmlElement(name = "Matricula")
    protected String matricula;
    @XmlElement(name = "Bastidor")
    protected String bastidor;
    @XmlElement(name = "Numero_Fabricacion")
    protected String numeroFabricacion;
    @XmlElement(name = "Maquinaria")
    protected List<MaquinariaType> maquinaria;
    @XmlElement(name = "Establecimiento")
    protected List<EstablecimientoMercantilType> establecimiento;
    @XmlElement(name = "Buque")
    protected List<BuqueType> buque;
    @XmlElement(name = "Aeronave")
    protected List<AeronaveType> aeronave;
    @XmlElement(name = "Propiedad_Industrial")
    protected List<PropiedadIndustrialType> propiedadIndustrial;
    @XmlElement(name = "Propiedad_Intelectual")
    protected List<PropiedadIntelectualType> propiedadIntelectual;
    @XmlElement(name = "Otros_Bienes")
    protected List<OtrosBienesType> otrosBienes;

    /**
     * Gets the value of the clase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClase() {
        return clase;
    }

    /**
     * Sets the value of the clase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClase(String value) {
        this.clase = value;
    }

    /**
     * Gets the value of the marca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarca() {
        return marca;
    }

    /**
     * Sets the value of the marca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarca(String value) {
        this.marca = value;
    }

    /**
     * Gets the value of the modelo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelo() {
        return modelo;
    }

    /**
     * Sets the value of the modelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelo(String value) {
        this.modelo = value;
    }

    /**
     * Gets the value of the matricula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatricula() {
        return matricula;
    }

    /**
     * Sets the value of the matricula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatricula(String value) {
        this.matricula = value;
    }

    /**
     * Gets the value of the bastidor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBastidor() {
        return bastidor;
    }

    /**
     * Sets the value of the bastidor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBastidor(String value) {
        this.bastidor = value;
    }

    /**
     * Gets the value of the numeroFabricacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFabricacion() {
        return numeroFabricacion;
    }

    /**
     * Sets the value of the numeroFabricacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFabricacion(String value) {
        this.numeroFabricacion = value;
    }

    /**
     * Gets the value of the maquinaria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the maquinaria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaquinaria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaquinariaType }
     * 
     * 
     */
    public List<MaquinariaType> getMaquinaria() {
        if (maquinaria == null) {
            maquinaria = new ArrayList<MaquinariaType>();
        }
        return this.maquinaria;
    }

    /**
     * Gets the value of the establecimiento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the establecimiento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstablecimiento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstablecimientoMercantilType }
     * 
     * 
     */
    public List<EstablecimientoMercantilType> getEstablecimiento() {
        if (establecimiento == null) {
            establecimiento = new ArrayList<EstablecimientoMercantilType>();
        }
        return this.establecimiento;
    }

    /**
     * Gets the value of the buque property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buque property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuque().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuqueType }
     * 
     * 
     */
    public List<BuqueType> getBuque() {
        if (buque == null) {
            buque = new ArrayList<BuqueType>();
        }
        return this.buque;
    }

    /**
     * Gets the value of the aeronave property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aeronave property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAeronave().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AeronaveType }
     * 
     * 
     */
    public List<AeronaveType> getAeronave() {
        if (aeronave == null) {
            aeronave = new ArrayList<AeronaveType>();
        }
        return this.aeronave;
    }

    /**
     * Gets the value of the propiedadIndustrial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propiedadIndustrial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropiedadIndustrial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropiedadIndustrialType }
     * 
     * 
     */
    public List<PropiedadIndustrialType> getPropiedadIndustrial() {
        if (propiedadIndustrial == null) {
            propiedadIndustrial = new ArrayList<PropiedadIndustrialType>();
        }
        return this.propiedadIndustrial;
    }

    /**
     * Gets the value of the propiedadIntelectual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propiedadIntelectual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropiedadIntelectual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropiedadIntelectualType }
     * 
     * 
     */
    public List<PropiedadIntelectualType> getPropiedadIntelectual() {
        if (propiedadIntelectual == null) {
            propiedadIntelectual = new ArrayList<PropiedadIntelectualType>();
        }
        return this.propiedadIntelectual;
    }

    /**
     * Gets the value of the otrosBienes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otrosBienes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtrosBienes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtrosBienesType }
     * 
     * 
     */
    public List<OtrosBienesType> getOtrosBienes() {
        if (otrosBienes == null) {
            otrosBienes = new ArrayList<OtrosBienesType>();
        }
        return this.otrosBienes;
    }

}
