//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Identificacion_DocumentoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identificacion_DocumentoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Numero_Documento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Clase_Acto_Documento" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Tipo_EF" type="{}Tipificacion_Entidad_FinanciacionType" minOccurs="0"/>
 *         &lt;element name="ID_Lote" type="{}NumericoType" minOccurs="0"/>
 *         &lt;element name="ID_Documento" type="{}NumericoType" minOccurs="0"/>
 *         &lt;element name="Tipo_Presentacion" type="{}NumericoType" minOccurs="0"/>
 *         &lt;element name="Numero_Entrada" type="{}NumericoType" minOccurs="0"/>
 *         &lt;element name="Identificacion_Registral" type="{}Identificacion_RegistralType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identificacion_DocumentoType", propOrder = {
    "numeroDocumento",
    "claseActoDocumento",
    "tipoEF",
    "idLote",
    "idDocumento",
    "tipoPresentacion",
    "numeroEntrada",
    "identificacionRegistral"
})
public class IdentificacionDocumentoType {

    @XmlElement(name = "Numero_Documento")
    protected String numeroDocumento;
    @XmlElement(name = "Clase_Acto_Documento")
    protected List<String> claseActoDocumento;
    @XmlElement(name = "Tipo_EF")
    protected String tipoEF;
    @XmlElement(name = "ID_Lote")
    protected String idLote;
    @XmlElement(name = "ID_Documento")
    protected String idDocumento;
    @XmlElement(name = "Tipo_Presentacion")
    protected String tipoPresentacion;
    @XmlElement(name = "Numero_Entrada")
    protected String numeroEntrada;
    @XmlElement(name = "Identificacion_Registral")
    protected IdentificacionRegistralType identificacionRegistral;

    /**
     * Gets the value of the numeroDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDocumento() {
        return numeroDocumento;
    }

    /**
     * Sets the value of the numeroDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroDocumento(String value) {
        this.numeroDocumento = value;
    }

    /**
     * Gets the value of the claseActoDocumento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the claseActoDocumento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClaseActoDocumento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClaseActoDocumento() {
        if (claseActoDocumento == null) {
            claseActoDocumento = new ArrayList<String>();
        }
        return this.claseActoDocumento;
    }

    /**
     * Gets the value of the tipoEF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoEF() {
        return tipoEF;
    }

    /**
     * Sets the value of the tipoEF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoEF(String value) {
        this.tipoEF = value;
    }

    /**
     * Gets the value of the idLote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDLote() {
        return idLote;
    }

    /**
     * Sets the value of the idLote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDLote(String value) {
        this.idLote = value;
    }

    /**
     * Gets the value of the idDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDDocumento() {
        return idDocumento;
    }

    /**
     * Sets the value of the idDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDDocumento(String value) {
        this.idDocumento = value;
    }

    /**
     * Gets the value of the tipoPresentacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPresentacion() {
        return tipoPresentacion;
    }

    /**
     * Sets the value of the tipoPresentacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPresentacion(String value) {
        this.tipoPresentacion = value;
    }

    /**
     * Gets the value of the numeroEntrada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroEntrada() {
        return numeroEntrada;
    }

    /**
     * Sets the value of the numeroEntrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroEntrada(String value) {
        this.numeroEntrada = value;
    }

    /**
     * Gets the value of the identificacionRegistral property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificacionRegistralType }
     *     
     */
    public IdentificacionRegistralType getIdentificacionRegistral() {
        return identificacionRegistral;
    }

    /**
     * Sets the value of the identificacionRegistral property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificacionRegistralType }
     *     
     */
    public void setIdentificacionRegistral(IdentificacionRegistralType value) {
        this.identificacionRegistral = value;
    }

}
