//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Junta2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Junta2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reunion_Junta" type="{}Reunion_JuntaType" minOccurs="0"/>
 *         &lt;element name="Contenido_Convocatoria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Convocatoria" type="{}ConvocatoriaType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Junta2Type", propOrder = {
    "reunionJunta",
    "contenidoConvocatoria",
    "convocatoria"
})
public class Junta2Type {

    @XmlElement(name = "Reunion_Junta")
    protected ReunionJuntaType reunionJunta;
    @XmlElement(name = "Contenido_Convocatoria")
    protected String contenidoConvocatoria;
    @XmlElement(name = "Convocatoria")
    protected ConvocatoriaType convocatoria;

    /**
     * Gets the value of the reunionJunta property.
     * 
     * @return
     *     possible object is
     *     {@link ReunionJuntaType }
     *     
     */
    public ReunionJuntaType getReunionJunta() {
        return reunionJunta;
    }

    /**
     * Sets the value of the reunionJunta property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReunionJuntaType }
     *     
     */
    public void setReunionJunta(ReunionJuntaType value) {
        this.reunionJunta = value;
    }

    /**
     * Gets the value of the contenidoConvocatoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContenidoConvocatoria() {
        return contenidoConvocatoria;
    }

    /**
     * Sets the value of the contenidoConvocatoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContenidoConvocatoria(String value) {
        this.contenidoConvocatoria = value;
    }

    /**
     * Gets the value of the convocatoria property.
     * 
     * @return
     *     possible object is
     *     {@link ConvocatoriaType }
     *     
     */
    public ConvocatoriaType getConvocatoria() {
        return convocatoria;
    }

    /**
     * Sets the value of the convocatoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConvocatoriaType }
     *     
     */
    public void setConvocatoria(ConvocatoriaType value) {
        this.convocatoria = value;
    }

}
