//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Plazo_FIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plazo_FIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Fecha_Vencimiento" type="{}FechaType" minOccurs="0"/>
 *         &lt;element name="Importe_Amortizacion" type="{}ImporteType" minOccurs="0"/>
 *         &lt;element name="Importe_Capital_Pendiente" type="{}ImporteType" minOccurs="0"/>
 *         &lt;element name="Importe_Carga_Financiera" type="{}ImporteType" minOccurs="0"/>
 *         &lt;element name="Importe_Total_Cuota" type="{}ImporteType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plazo_FIType", propOrder = {
    "fechaVencimiento",
    "importeAmortizacion",
    "importeCapitalPendiente",
    "importeCargaFinanciera",
    "importeTotalCuota"
})
public class PlazoFIType {

    @XmlElement(name = "Fecha_Vencimiento")
    protected String fechaVencimiento;
    @XmlElement(name = "Importe_Amortizacion")
    protected String importeAmortizacion;
    @XmlElement(name = "Importe_Capital_Pendiente")
    protected String importeCapitalPendiente;
    @XmlElement(name = "Importe_Carga_Financiera")
    protected String importeCargaFinanciera;
    @XmlElement(name = "Importe_Total_Cuota")
    protected String importeTotalCuota;

    /**
     * Gets the value of the fechaVencimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * Sets the value of the fechaVencimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaVencimiento(String value) {
        this.fechaVencimiento = value;
    }

    /**
     * Gets the value of the importeAmortizacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteAmortizacion() {
        return importeAmortizacion;
    }

    /**
     * Sets the value of the importeAmortizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteAmortizacion(String value) {
        this.importeAmortizacion = value;
    }

    /**
     * Gets the value of the importeCapitalPendiente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteCapitalPendiente() {
        return importeCapitalPendiente;
    }

    /**
     * Sets the value of the importeCapitalPendiente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteCapitalPendiente(String value) {
        this.importeCapitalPendiente = value;
    }

    /**
     * Gets the value of the importeCargaFinanciera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteCargaFinanciera() {
        return importeCargaFinanciera;
    }

    /**
     * Sets the value of the importeCargaFinanciera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteCargaFinanciera(String value) {
        this.importeCargaFinanciera = value;
    }

    /**
     * Gets the value of the importeTotalCuota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteTotalCuota() {
        return importeTotalCuota;
    }

    /**
     * Sets the value of the importeTotalCuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteTotalCuota(String value) {
        this.importeTotalCuota = value;
    }

}
