//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:11:02 PM CEST 
//


package org.gestoresmadrid.oegam2comun.registradores.importExport.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tipo_Inscripcion_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tipo_Inscripcion_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Primera_entrada" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SI"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Identificacion_Notarial">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Codigo_Notaria" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Codigo_Notario" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Anyo_Protocolo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Numero_Protocolo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Identificacion_Numero_entrada">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Numero" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Anyo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tipo_Inscripcion_Type", propOrder = {
    "primeraEntrada",
    "identificacionNotarial",
    "identificacionNumeroEntrada"
})
public class TipoInscripcionType {

    @XmlElement(name = "Primera_entrada")
    protected String primeraEntrada;
    @XmlElement(name = "Identificacion_Notarial")
    protected TipoInscripcionType.IdentificacionNotarial identificacionNotarial;
    @XmlElement(name = "Identificacion_Numero_entrada")
    protected TipoInscripcionType.IdentificacionNumeroEntrada identificacionNumeroEntrada;

    /**
     * Gets the value of the primeraEntrada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimeraEntrada() {
        return primeraEntrada;
    }

    /**
     * Sets the value of the primeraEntrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimeraEntrada(String value) {
        this.primeraEntrada = value;
    }

    /**
     * Gets the value of the identificacionNotarial property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInscripcionType.IdentificacionNotarial }
     *     
     */
    public TipoInscripcionType.IdentificacionNotarial getIdentificacionNotarial() {
        return identificacionNotarial;
    }

    /**
     * Sets the value of the identificacionNotarial property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInscripcionType.IdentificacionNotarial }
     *     
     */
    public void setIdentificacionNotarial(TipoInscripcionType.IdentificacionNotarial value) {
        this.identificacionNotarial = value;
    }

    /**
     * Gets the value of the identificacionNumeroEntrada property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInscripcionType.IdentificacionNumeroEntrada }
     *     
     */
    public TipoInscripcionType.IdentificacionNumeroEntrada getIdentificacionNumeroEntrada() {
        return identificacionNumeroEntrada;
    }

    /**
     * Sets the value of the identificacionNumeroEntrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInscripcionType.IdentificacionNumeroEntrada }
     *     
     */
    public void setIdentificacionNumeroEntrada(TipoInscripcionType.IdentificacionNumeroEntrada value) {
        this.identificacionNumeroEntrada = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Codigo_Notaria" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Codigo_Notario" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Anyo_Protocolo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Numero_Protocolo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class IdentificacionNotarial {

        @XmlElement(name = "Codigo_Notaria")
        protected BigInteger codigoNotaria;
        @XmlElement(name = "Codigo_Notario")
        protected BigInteger codigoNotario;
        @XmlElement(name = "Anyo_Protocolo")
        protected BigInteger anyoProtocolo;
        @XmlElement(name = "Numero_Protocolo")
        protected BigInteger numeroProtocolo;

        /**
         * Gets the value of the codigoNotaria property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCodigoNotaria() {
            return codigoNotaria;
        }

        /**
         * Sets the value of the codigoNotaria property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCodigoNotaria(BigInteger value) {
            this.codigoNotaria = value;
        }

        /**
         * Gets the value of the codigoNotario property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCodigoNotario() {
            return codigoNotario;
        }

        /**
         * Sets the value of the codigoNotario property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCodigoNotario(BigInteger value) {
            this.codigoNotario = value;
        }

        /**
         * Gets the value of the anyoProtocolo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAnyoProtocolo() {
            return anyoProtocolo;
        }

        /**
         * Sets the value of the anyoProtocolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAnyoProtocolo(BigInteger value) {
            this.anyoProtocolo = value;
        }

        /**
         * Gets the value of the numeroProtocolo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumeroProtocolo() {
            return numeroProtocolo;
        }

        /**
         * Sets the value of the numeroProtocolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumeroProtocolo(BigInteger value) {
            this.numeroProtocolo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Numero" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Anyo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class IdentificacionNumeroEntrada {

        @XmlElement(name = "Numero")
        protected BigInteger numero;
        @XmlElement(name = "Anyo")
        protected BigInteger anyo;

        /**
         * Gets the value of the numero property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumero() {
            return numero;
        }

        /**
         * Sets the value of the numero property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumero(BigInteger value) {
            this.numero = value;
        }

        /**
         * Gets the value of the anyo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAnyo() {
            return anyo;
        }

        /**
         * Sets the value of the anyo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAnyo(BigInteger value) {
            this.anyo = value;
        }

    }

}
