//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 03:00:04 PM CET 
//


package trafico.beans.jaxb.transNoTelematica;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}TIPO_LIMITACION"/>
 *         &lt;element ref="{}FECHA_LIMITACION"/>
 *         &lt;element ref="{}NUMERO_REGISTRO_LIMITACION"/>
 *         &lt;element ref="{}FINANCIERA_LIMITACION"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DATOS_LIMITACION")
public class DATOSLIMITACION {

    @XmlElement(name = "TIPO_LIMITACION", required = true)
    protected String tipolimitacion;
    @XmlElement(name = "FECHA_LIMITACION", required = true)
    protected String fechalimitacion;
    @XmlElement(name = "NUMERO_REGISTRO_LIMITACION", required = true)
    protected String numeroregistrolimitacion;
    @XmlElement(name = "FINANCIERA_LIMITACION", required = true)
    protected String financieralimitacion;

    /**
     * Gets the value of the tipolimitacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOLIMITACION() {
        return tipolimitacion;
    }

    /**
     * Sets the value of the tipolimitacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOLIMITACION(String value) {
        this.tipolimitacion = value;
    }

    /**
     * Gets the value of the fechalimitacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHALIMITACION() {
        return fechalimitacion;
    }

    /**
     * Sets the value of the fechalimitacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHALIMITACION(String value) {
        this.fechalimitacion = value;
    }

    /**
     * Gets the value of the numeroregistrolimitacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMEROREGISTROLIMITACION() {
        return numeroregistrolimitacion;
    }

    /**
     * Sets the value of the numeroregistrolimitacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMEROREGISTROLIMITACION(String value) {
        this.numeroregistrolimitacion = value;
    }

    /**
     * Gets the value of the financieralimitacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINANCIERALIMITACION() {
        return financieralimitacion;
    }

    /**
     * Sets the value of the financieralimitacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINANCIERALIMITACION(String value) {
        this.financieralimitacion = value;
    }

}
