//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.15 at 03:00:04 PM CET 
//


package trafico.beans.jaxb.transNoTelematica;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="FIRMA_GESTOR" type="{}tipoHash"/>
 *         &lt;element name="FIRMA_COLEGIO" type="{}tipoHash"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "FIRMA")
public class FIRMA {

    @XmlElement(name = "FIRMA_GESTOR", required = true)
    protected byte[] firmagestor;
    @XmlElement(name = "FIRMA_COLEGIO", required = true)
    protected byte[] firmacolegio;

    /**
     * Gets the value of the firmagestor property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFIRMAGESTOR() {
        return firmagestor;
    }

    /**
     * Sets the value of the firmagestor property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFIRMAGESTOR(byte[] value) {
        this.firmagestor = ((byte[]) value);
    }

    /**
     * Gets the value of the firmacolegio property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFIRMACOLEGIO() {
        return firmacolegio;
    }

    /**
     * Sets the value of the firmacolegio property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFIRMACOLEGIO(byte[] value) {
        this.firmacolegio = ((byte[]) value);
    }

}
