//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 05:23:00 PM CEST 
//


package org.gestoresmadrid.oegam2comun.sega.ctit.view.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Datos_Genericos"/>
 *         &lt;element ref="{}Datos_Especificos"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosGenericos",
    "datosEspecificos"
})
@XmlRootElement(name = "Datos_Firmados")
public class DatosFirmados {

    @XmlElement(name = "Datos_Genericos", required = true)
    protected DatosGenericos datosGenericos;
    @XmlElement(name = "Datos_Especificos", required = true)
    protected DatosEspecificos datosEspecificos;

    /**
     * Gets the value of the datosGenericos property.
     * 
     * @return
     *     possible object is
     *     {@link DatosGenericos }
     *     
     */
    public DatosGenericos getDatosGenericos() {
        return datosGenericos;
    }

    /**
     * Sets the value of the datosGenericos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosGenericos }
     *     
     */
    public void setDatosGenericos(DatosGenericos value) {
        this.datosGenericos = value;
    }

    /**
     * Gets the value of the datosEspecificos property.
     * 
     * @return
     *     possible object is
     *     {@link DatosEspecificos }
     *     
     */
    public DatosEspecificos getDatosEspecificos() {
        return datosEspecificos;
    }

    /**
     * Sets the value of the datosEspecificos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosEspecificos }
     *     
     */
    public void setDatosEspecificos(DatosEspecificos value) {
        this.datosEspecificos = value;
    }

}
