//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 04:23:12 PM CET 
//


package org.gestoresmadrid.oegam2comun.trafico.eeff.view.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.thoughtworks.xstream.annotations.XStreamAlias;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Remitente" type="{}Remitente"/>
 *         &lt;element name="Interesados">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Interesado" type="{}Datos_Interesado"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Asunto" type="{}Asunto"/>
 *         &lt;element name="Destino" type="{}Destino"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "remitente",
    "interesados",
    "asunto",
    "destino"
})
@XmlRootElement(name = "Datos_Genericos")
@XStreamAlias("Datos_Genericos")
public class DatosGenericos {

    @XmlElement(name = "Remitente", required = true)
    @XStreamAlias("Remitente")
    protected Remitente remitente;
    @XmlElement(name = "Interesados", required = true)
    @XStreamAlias("Interesados")
    protected DatosGenericos.Interesados interesados;
    @XmlElement(name = "Asunto", required = true)
    @XStreamAlias("Asunto")
    protected Asunto asunto;
    @XmlElement(name = "Destino", required = true)
    @XStreamAlias("Destino")
    protected Destino destino;

    /**
     * Gets the value of the remitente property.
     * 
     * @return
     *     possible object is
     *     {@link Remitente }
     *     
     */
    public Remitente getRemitente() {
        return remitente;
    }

    /**
     * Sets the value of the remitente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Remitente }
     *     
     */
    public void setRemitente(Remitente value) {
        this.remitente = value;
    }

    /**
     * Gets the value of the interesados property.
     * 
     * @return
     *     possible object is
     *     {@link DatosGenericos.Interesados }
     *     
     */
    public DatosGenericos.Interesados getInteresados() {
        return interesados;
    }

    /**
     * Sets the value of the interesados property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosGenericos.Interesados }
     *     
     */
    public void setInteresados(DatosGenericos.Interesados value) {
        this.interesados = value;
    }

    /**
     * Gets the value of the asunto property.
     * 
     * @return
     *     possible object is
     *     {@link Asunto }
     *     
     */
    public Asunto getAsunto() {
        return asunto;
    }

    /**
     * Sets the value of the asunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asunto }
     *     
     */
    public void setAsunto(Asunto value) {
        this.asunto = value;
    }

    /**
     * Gets the value of the destino property.
     * 
     * @return
     *     possible object is
     *     {@link Destino }
     *     
     */
    public Destino getDestino() {
        return destino;
    }

    /**
     * Sets the value of the destino property.
     * 
     * @param value
     *     allowed object is
     *     {@link Destino }
     *     
     */
    public void setDestino(Destino value) {
        this.destino = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Interesado" type="{}Datos_Interesado"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interesado"
    })
    @XStreamAlias("Interesados")
    public static class Interesados {

        @XmlElement(name = "Interesado", required = true)
        @XStreamAlias("Interesado")
        protected DatosInteresado interesado;

        /**
         * Gets the value of the interesado property.
         * 
         * @return
         *     possible object is
         *     {@link DatosInteresado }
         *     
         */
        public DatosInteresado getInteresado() {
            return interesado;
        }

        /**
         * Sets the value of the interesado property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatosInteresado }
         *     
         */
        public void setInteresado(DatosInteresado value) {
            this.interesado = value;
        }

    }

}
