//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 05:16:12 PM CEST 
//


package org.gestoresmadrid.oegam2comun.sega.eitv.view.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datos_Firmados">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AGENT_DOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AGENCY_DOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="VIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TEXTO_LEGAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Firma_Gestor" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosFirmados",
    "firmaGestor"
})
@XmlRootElement(name = "ConsultaTarjeta")
public class ConsultaTarjeta {

    @XmlElement(name = "Datos_Firmados", required = true)
    protected ConsultaTarjeta.DatosFirmados datosFirmados;
    @XmlElement(name = "Firma_Gestor", required = true)
    protected byte[] firmaGestor;

    /**
     * Gets the value of the datosFirmados property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultaTarjeta.DatosFirmados }
     *     
     */
    public DatosFirmados getDatosFirmados() {
        return datosFirmados;
    }

    /**
     * Sets the value of the datosFirmados property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultaTarjeta.DatosFirmados }
     *     
     */
    public void setDatosFirmados(DatosFirmados value) {
        this.datosFirmados = value;
    }

    /**
     * Gets the value of the firmaGestor property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFirmaGestor() {
        return firmaGestor;
    }

    /**
     * Sets the value of the firmaGestor property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFirmaGestor(byte[] value) {
        this.firmaGestor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AGENT_DOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AGENCY_DOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="VIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TEXTO_LEGAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agentdoi",
        "agencydoi",
        "vin",
        "nive",
        "textolegal"
    })
    public static class DatosFirmados {

        @XmlElement(name = "AGENT_DOI", required = true)
        protected String agentdoi;
        @XmlElement(name = "AGENCY_DOI", required = true)
        protected String agencydoi;
        @XmlElement(name = "VIN", required = true)
        protected String vin;
        @XmlElement(name = "NIVE", required = true)
        protected String nive;
        @XmlElement(name = "TEXTO_LEGAL", required = true)
        protected String textolegal;

        /**
         * Gets the value of the agentdoi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAGENTDOI() {
            return agentdoi;
        }

        /**
         * Sets the value of the agentdoi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAGENTDOI(String value) {
            this.agentdoi = value;
        }

        /**
         * Gets the value of the agencydoi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAGENCYDOI() {
            return agencydoi;
        }

        /**
         * Sets the value of the agencydoi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAGENCYDOI(String value) {
            this.agencydoi = value;
        }

        /**
         * Gets the value of the vin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVIN() {
            return vin;
        }

        /**
         * Sets the value of the vin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVIN(String value) {
            this.vin = value;
        }

        /**
         * Gets the value of the nive property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNIVE() {
            return nive;
        }

        /**
         * Sets the value of the nive property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNIVE(String value) {
            this.nive = value;
        }

        /**
         * Gets the value of the textolegal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTEXTOLEGAL() {
            return textolegal;
        }

        /**
         * Sets the value of the textolegal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTEXTOLEGAL(String value) {
            this.textolegal = value;
        }

    }

}
