package org.gestoresmadrid.core.model.enumerados;

/**
 * Enumerado de tipos de vehículo (Debe coincidir con los datos de la tabla TIPO_VEHICULO del modelo de datos)
 * @author Santiago Cuenca Lizcano
 *
 */
public enum TipoVehiculoEnum {

	/* Enumeraciones */
	CAMION("00", "CAMION"),
	CAMION_PLATAFORMA("01", "CAMION PLATAFORMA"),
	CAMION_CAJA_ABIERTA("02", "CAMION CAJA ABIERTA"),
	CAMION_FURGON("03", "CAMION FURGON"),
	CAMION_BOTELLERO("04", "CAMION BOTELLERO"),
	CAMION_CISTERNA("05", "CAMION CISTERNA"),
	CAMION_JAULA("06", "CAMION JAULA"),
	CAMION_FRIGORIFICO("07", "CAMION FRIGORIFICO"),
	CAMION_TALLER("08", "CAMION TALLER"),
	CAMION_PORTAVEHICULOS("0A", "CAMION PORTAVEHICULOS"),
	CAMION_MIXTO("0B", "CAMION MIXTO"),
	CAMION_PORTACONTENEDORES("0C", "CAMION PORTACONTENEDORES"),
	CAMION_BASURERO("0D", "CAMION BASURERO"),
	CAMION_ISOTERMO("0E", "CAMION ISOTERMO"),
	CAMION_SILO("0F", "CAMION SILO"),
	VEHICULO_MIXTO_ADAPTABLE("0G", "VEHICULO MIXTO ADAPTABLE"),
	CAMION_ARTICULADO_VOLQUETE("1D", "CAMION ARTICULADO VOLQUETE"),
	CAMION_ARTICULADO_GRUA("1E", "CAMION ARTICULADO GRUA"),
	CAMION_ARTICULADO_CONTRA_INCENDIOS("1F", "CAMION ARTICULADO CONTRA INCENDIOS"),
	FURGONETA("20", "FURGONETA"),
	AMBULANCIA("22", "AMBULANCIA"),
	COCHE_FUNEBRE("23", "COCHE FUNEBRE"),
	TODO_TERRENO("25", "TODO TERRENO"),
	AUTOBUS("30", "AUTOBUS"),
	AUTOBUS_ARTICULADO("31", "AUTOBUS ARTICULADO"),
	AUTOBUS_MIXTO("32", "AUTOBUS MIXTO"),
	BIBLIOBUS("33", "BIBLIOBUS"),
	AUTOBUS_TALLER("35", "AUTOBUS TALLER"),
	AUTOBUS_SANITARIO("36", "AUTOBUS SANITARIO"),
	TURISMO("40", "TURISMO"),
	MOTOCICLETA_DE_2_RUEDAS_SIN_SIDECAR("50", "MOTOCICLETA DE 2 RUEDAS SIN SIDECAR"),
	MOTOCICLETA_CON_SIDECAR("51", "MOTOCICLETA CON SIDECAR"),
	MOTOCARRO("52", "MOTOCARRO"),
	AUTOMOVIL_DE_3_RUEDAS("53", "AUTOMOVIL DE 3 RUEDAS"),
	CUATRICICLO("54", "CUATRICICLO"),
	COCHE_DE_INVALIDO("60", "COCHE DE INVALIDO"),
	VEHICULO_ESPECIAL("70", "VEHICULO ESPECIAL"),
	PALA_CARGADORA("71", "PALA CARGADORA"),
	PALA_EXCAVADORA("72", "PALA EXCAVADORA"),
	CARRETILLA_ELEVADORA("73", "CARRETILLA ELEVADORA"),
	MOTONIVELADORA("74", "MOTONIVELADORA"),
	COMPACTADORA("75", "COMPACTADORA"),
	QUITANIEVES("79", "QUITANIEVES"),
	APISONADORA("76", "APISONADORA"),
	GIROGRAVILLADORA("77", "GIROGRAVILLADORA"),
	MACHACADORA("78", "MACHACADORA"),
	VIVIENDA("7A", "VIVIENDA"),
	BARREDORA("7B", "BARREDORA"),
	HORMIGONERA("7C", "HORMIGONERA"),
	VEHICULO_BASCULANTE("7D", "VEHICULO BASCULANTE"),
	GRUA("7E", "GRUA"),
	SERVICIO_CONTRA_INCENDIOS("7F", "SERVICIO CONTRA INCENDIOS"),
	ASPIRADORA_DE_FANGOS("7G", "ASPIRADORA DE FANGOS"),
	MOTOCULTOR("7H", "MOTOCULTOR"),
	MAQUINARIA_AGRICOLA_AUTOMOTRIZ("7I", "MAQUINARIA AGRICOLA AUTOMOTRIZ"),
	PALA_CARGADORA_RETROEXCAVADORA("7J", "PALA CARGADORA-RETROEXCAVADORA"),
	TREN_HASTA_160_PLAZAS("7K", "TREN HASTA 160 PLAZAS"),
	TRACTOR("80", "TRACTOR"),
	TRACTOCAMION("81", "TRACTOCAMION"),
	TRACTOCARRO("82", "TRACTOCARRO"),
	CICLOMOTOR_DE_2_RUEDAS("90", "CICLOMOTOR DE 2 RUEDAS"),
	CICLOMOTOR_DE_3_RUEDAS("91", "CICLOMOTOR DE 3 RUEDAS"),
	CUADRICICLO_LIGERO("92", "CUADRICICLO LIGERO"),
	REMOLQUE("R0", "REMOLQUE"),
	REMOLQUE_PLATAFORMA("R1", "REMOLQUE PLATAFORMA"),
	REMOLQUE_CAJA("R2", "REMOLQUE CAJA"),
	REMOLQUE_FURGON("R3", "REMOLQUE FURGON"),
	REMOLQUE_BOTELLERO("R4", "REMOLQUE BOTELLERO"),
	REMOLQUE_CISTERNA("R5", "REMOLQUE CISTERNA"),
	REMOLQUE_JAULA("R6", "REMOLQUE JAULA"),
	REMOLQUE_FRIGORIFICO("R7", "REMOLQUE FRIGORIFICO"),
	REMOLQUE_TALLER("R8", "REMOLQUE TALLER"),
	REMOLQUE_VIVIENDA_O_CARAVANA("RA", "REMOLQUE VIVIENDA O CARAVANA"),
	REMOLQUE_HORMIGONERA("RC", "REMOLQUE HORMIGONERA"),
	REMOLQUE_VOLQUETE_DE_CANTERA("RD", "REMOLQUE VOLQUETE DE CANTERA"),
	REMOLQUE_DE_GRUA("RE", "REMOLQUE DE GRUA"),
	REMOLQUE_CONTRA_INCENDIOS("RF", "REMOLQUE CONTRA INCENDIOS"),
	MAQUINARIA_AGRICOLA_ARRASTRADA_DE_2_EJES("RH", "MAQUINARIA AGRICOLA ARRASTRADA DE 2 EJES"),
	SEMIRREMOLQUE("S0", "SEMIRREMOLQUE"),
	SEMIRREMOLQUE_PLATAFORMA("S1", "SEMIRREMOLQUE PLATAFORMA"),
	SEMIRREMOLQUE_CAJA("S2", "SEMIRREMOLQUE CAJA"),
	SEMIRREMOLQUE_FURGON("S3", "SEMIRREMOLQUE FURGON"),
	SEMIRREMOLQUE_BOTELLERO("S4", "SEMIRREMOLQUE BOTELLERO"),
	SEMIRREMOLQUE_CISTERNA("S5", "SEMIRREMOLQUE CISTERNA"),
	SEMIRREMOLQUE_JAULA("S6", "SEMIRREMOLQUE JAULA"),
	SEMIRREMOLQUE_FRIGORIFICO("S7", "SEMIRREMOLQUE FRIGORIFICO"),
	SEMIRREMOLQUE_TALLER("S8", "SEMIRREMOLQUE TALLER"),
	SEMIRREMOLQUE_VIVIENDA_O_CARAVANA("SA", "SEMIRREMOLQUE VIVIENDA O CARAVANA"),
	SEMIRREMOLQUE_HORMIGONERA("SC", "SEMIRREMOLQUE HORMIGONERA"),
	SEMIRREMOLQUE_VOLQUETE_DE_CANTERA("SD", "SEMIRREMOLQUE VOLQUETE DE CANTERA"),
	SEMIRREMOLQUE_DE_GRUA("SE", "SEMIRREMOLQUE DE GRUA"),
	SEMIRREMOLQUE_CONTRA_INCENDIOS("SF", "SEMIRREMOLQUE CONTRA INCENDIOS"),
	MAQUINARIA_AGRICOLA_ARRASTRADA_DE_1_EJE("SH", "MAQUINARIA AGRICOLA ARRASTRADA DE 1 EJE");

	// Atributos
	private String valorEnum;
	private String nombreEnum;

	// Constructor
	private TipoVehiculoEnum(String valorEnum, String nombreEnum){
		this.valorEnum = valorEnum;
		this.nombreEnum = nombreEnum;
	}

	// Getters y setters
	public String getValorEnum() {
		return valorEnum;
	}
	public void setValor(String valorEnum) {
		this.valorEnum = valorEnum;
	}
	public String getNombreEnum() {
		return nombreEnum;
	}
	public void setNombre(String nombreEnum) {
		this.nombreEnum = nombreEnum;
	}

	public static TipoVehiculoEnum convertir(String valorEnum) {
		for (TipoVehiculoEnum element : TipoVehiculoEnum.values()) {
			if (element.valorEnum.equals(valorEnum)) {
				return element;
			}
		}
		return null;
	}

	public static String convertirTexto(String valorEnum) {
		for (TipoVehiculoEnum element : TipoVehiculoEnum.values()) {
			if (element.valorEnum.equals(valorEnum)) {
				return element.nombreEnum;
			}
		}
		return null;
	}

}