//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 11:43:08 AM CEST 
//


package org.gestoresmadrid.oegam2comun.trafico.solInfoApp.view.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gestoresmadrid.oegam2comun.trafico.solInfoApp.view.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Nombre_QNAME = new QName("", "nombre");
    private final static QName _Nif_QNAME = new QName("", "nif");
    private final static QName _Profesional_QNAME = new QName("", "profesional");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gestoresmadrid.oegam2comun.trafico.solInfoApp.view.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatosGestoria }
     * 
     */
    public DatosGestoria createDatosGestoria() {
        return new DatosGestoria();
    }

    /**
     * Create an instance of {@link SolicitudesInformacion }
     * 
     */
    public SolicitudesInformacion createSolicitudesInformacion() {
        return new SolicitudesInformacion();
    }

    /**
     * Create an instance of {@link Cabecera }
     * 
     */
    public Cabecera createCabecera() {
        return new Cabecera();
    }

    /**
     * Create an instance of {@link FormatoOegam2SolInfo }
     * 
     */
    public FormatoOegam2SolInfo createFormatoOegam2SolInfo() {
        return new FormatoOegam2SolInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nombre")
    public JAXBElement<String> createNombre(String value) {
        return new JAXBElement<String>(_Nombre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nif")
    public JAXBElement<String> createNif(String value) {
        return new JAXBElement<String>(_Nif_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "profesional")
    public JAXBElement<String> createProfesional(String value) {
        return new JAXBElement<String>(_Profesional_QNAME, String.class, null, value);
    }

}
