//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:31 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AtributosRegistro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AtributosRegistro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_eclu" type="{http://licencias/mensajes}minstring"/>
 *         &lt;element name="id_solicitud" type="{http://licencias/mensajes}minstring"/>
 *         &lt;element name="num_cc" type="{http://licencias/mensajes}minstring"/>
 *         &lt;element name="id_proceso" type="{http://licencias/mensajes}string3type"/>
 *         &lt;element name="id_etapa" type="{http://licencias/mensajes}string4type"/>
 *         &lt;any namespace='http://www.w3.org/2000/09/xmldsig#' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtributosRegistro", namespace = "http://licencias/peticionGenerica", propOrder = {
    "idEclu",
    "idSolicitud",
    "numCc",
    "idProceso",
    "idEtapa",
    "any"
})
public class AtributosRegistro {

    @XmlElement(name = "id_eclu", required = true, nillable = true)
    protected String idEclu;
    @XmlElement(name = "id_solicitud", required = true, nillable = true)
    protected String idSolicitud;
    @XmlElement(name = "num_cc", required = true, nillable = true)
    protected String numCc;
    @XmlElement(name = "id_proceso", required = true)
    protected String idProceso;
    @XmlElement(name = "id_etapa", required = true)
    protected String idEtapa;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the idEclu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdEclu() {
        return idEclu;
    }

    /**
     * Sets the value of the idEclu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdEclu(String value) {
        this.idEclu = value;
    }

    /**
     * Gets the value of the idSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSolicitud() {
        return idSolicitud;
    }

    /**
     * Sets the value of the idSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSolicitud(String value) {
        this.idSolicitud = value;
    }

    /**
     * Gets the value of the numCc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCc() {
        return numCc;
    }

    /**
     * Sets the value of the numCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCc(String value) {
        this.numCc = value;
    }

    /**
     * Gets the value of the idProceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdProceso() {
        return idProceso;
    }

    /**
     * Sets the value of the idProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdProceso(String value) {
        this.idProceso = value;
    }

    /**
     * Gets the value of the idEtapa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdEtapa() {
        return idEtapa;
    }

    /**
     * Sets the value of the idEtapa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdEtapa(String value) {
        this.idEtapa = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
