//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:49 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datos_plantas_baja complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datos_plantas_baja">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipo_planta" type="{http://licencias/mensajes}string4type"/>
 *         &lt;element name="sup_construida" type="{http://licencias/mensajes}decimal103type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datos_plantas_baja", propOrder = {
    "tipoPlanta",
    "supConstruida"
})
public class DatosPlantasBaja {

    @XmlElement(name = "tipo_planta", required = true)
    protected String tipoPlanta;
    @XmlElement(name = "sup_construida", required = true)
    protected BigDecimal supConstruida;

    /**
     * Gets the value of the tipoPlanta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPlanta() {
        return tipoPlanta;
    }

    /**
     * Sets the value of the tipoPlanta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPlanta(String value) {
        this.tipoPlanta = value;
    }

    /**
     * Gets the value of the supConstruida property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSupConstruida() {
        return supConstruida;
    }

    /**
     * Sets the value of the supConstruida property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSupConstruida(BigDecimal value) {
        this.supConstruida = value;
    }

}
