//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:49 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datos_plantas_alta_lic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datos_plantas_alta_lic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipo_planta" type="{http://licencias/mensajes}string4type"/>
 *         &lt;element name="num_planta" type="{http://licencias/mensajes}string4type"/>
 *         &lt;element name="altura_libre" type="{http://licencias/mensajes}decimal42type"/>
 *         &lt;element name="altura_piso" type="{http://licencias/mensajes}decimal42type"/>
 *         &lt;element name="uso_planta" type="{http://licencias/mensajes}string5type"/>
 *         &lt;element name="num_unidades" type="{http://licencias/mensajes}int4type"/>
 *         &lt;element name="sup_construida" type="{http://licencias/mensajes}decimal103type"/>
 *         &lt;element name="sup_computable" type="{http://licencias/mensajes}decimal103type"/>
 *         &lt;element name="superficie_no_computable" type="{http://licencias/mensajes}superficie_no_computable_planta" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datos_plantas_alta_lic", propOrder = {
    "tipoPlanta",
    "numPlanta",
    "alturaLibre",
    "alturaPiso",
    "usoPlanta",
    "numUnidades",
    "supConstruida",
    "supComputable",
    "superficieNoComputable"
})
public class DatosPlantasAltaLic {

    @XmlElement(name = "tipo_planta", required = true)
    protected String tipoPlanta;
    @XmlElement(name = "num_planta", required = true)
    protected String numPlanta;
    @XmlElement(name = "altura_libre", required = true)
    protected BigDecimal alturaLibre;
    @XmlElement(name = "altura_piso", required = true)
    protected BigDecimal alturaPiso;
    @XmlElement(name = "uso_planta", required = true)
    protected String usoPlanta;
    @XmlElement(name = "num_unidades", required = true)
    protected BigInteger numUnidades;
    @XmlElement(name = "sup_construida", required = true)
    protected BigDecimal supConstruida;
    @XmlElement(name = "sup_computable", required = true)
    protected BigDecimal supComputable;
    @XmlElement(name = "superficie_no_computable")
    protected List<SuperficieNoComputablePlanta> superficieNoComputable;

    /**
     * Gets the value of the tipoPlanta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPlanta() {
        return tipoPlanta;
    }

    /**
     * Sets the value of the tipoPlanta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPlanta(String value) {
        this.tipoPlanta = value;
    }

    /**
     * Gets the value of the numPlanta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumPlanta() {
        return numPlanta;
    }

    /**
     * Sets the value of the numPlanta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumPlanta(String value) {
        this.numPlanta = value;
    }

    /**
     * Gets the value of the alturaLibre property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlturaLibre() {
        return alturaLibre;
    }

    /**
     * Sets the value of the alturaLibre property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlturaLibre(BigDecimal value) {
        this.alturaLibre = value;
    }

    /**
     * Gets the value of the alturaPiso property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlturaPiso() {
        return alturaPiso;
    }

    /**
     * Sets the value of the alturaPiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlturaPiso(BigDecimal value) {
        this.alturaPiso = value;
    }

    /**
     * Gets the value of the usoPlanta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsoPlanta() {
        return usoPlanta;
    }

    /**
     * Sets the value of the usoPlanta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsoPlanta(String value) {
        this.usoPlanta = value;
    }

    /**
     * Gets the value of the numUnidades property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumUnidades() {
        return numUnidades;
    }

    /**
     * Sets the value of the numUnidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumUnidades(BigInteger value) {
        this.numUnidades = value;
    }

    /**
     * Gets the value of the supConstruida property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSupConstruida() {
        return supConstruida;
    }

    /**
     * Sets the value of the supConstruida property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSupConstruida(BigDecimal value) {
        this.supConstruida = value;
    }

    /**
     * Gets the value of the supComputable property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSupComputable() {
        return supComputable;
    }

    /**
     * Sets the value of the supComputable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSupComputable(BigDecimal value) {
        this.supComputable = value;
    }

    /**
     * Gets the value of the superficieNoComputable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the superficieNoComputable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuperficieNoComputable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuperficieNoComputablePlanta }
     * 
     * 
     */
    public List<SuperficieNoComputablePlanta> getSuperficieNoComputable() {
        if (superficieNoComputable == null) {
            superficieNoComputable = new ArrayList<SuperficieNoComputablePlanta>();
        }
        return this.superficieNoComputable;
    }

}
