//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:49 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for equipos_inst_relevantes_ordinario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="equipos_inst_relevantes_ordinario">
 *   &lt;complexContent>
 *     &lt;extension base="{http://licencias/mensajes}equipos_inst_relevantes">
 *       &lt;sequence>
 *         &lt;element name="potencia_total" type="{http://licencias/mensajes}decimal103type" minOccurs="0"/>
 *         &lt;element name="potencia_centro_transformador" type="{http://licencias/mensajes}decimal103type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "equipos_inst_relevantes_ordinario", propOrder = {
    "potenciaTotal",
    "potenciaCentroTransformador"
})
public class EquiposInstRelevantesOrdinario
    extends EquiposInstRelevantes
{

    @XmlElement(name = "potencia_total")
    protected BigDecimal potenciaTotal;
    @XmlElement(name = "potencia_centro_transformador")
    protected BigDecimal potenciaCentroTransformador;

    /**
     * Gets the value of the potenciaTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPotenciaTotal() {
        return potenciaTotal;
    }

    /**
     * Sets the value of the potenciaTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPotenciaTotal(BigDecimal value) {
        this.potenciaTotal = value;
    }

    /**
     * Gets the value of the potenciaCentroTransformador property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPotenciaCentroTransformador() {
        return potenciaCentroTransformador;
    }

    /**
     * Sets the value of the potenciaCentroTransformador property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPotenciaCentroTransformador(BigDecimal value) {
        this.potenciaCentroTransformador = value;
    }

}
