//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:49 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for info_edificio_alta_lic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="info_edificio_alta_lic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="direccion_edificio" type="{http://licencias/mensajes}direccion_lic"/>
 *         &lt;element name="num_portales" type="{http://licencias/mensajes}int3type" minOccurs="0"/>
 *         &lt;element name="portal" type="{http://licencias/mensajes}datos_portal_alta" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "info_edificio_alta_lic", propOrder = {
    "direccionEdificio",
    "numPortales",
    "portal"
})
public class InfoEdificioAltaLic {

    @XmlElement(name = "direccion_edificio", required = true)
    protected DireccionLic direccionEdificio;
    @XmlElement(name = "num_portales")
    protected BigInteger numPortales;
    protected List<DatosPortalAlta> portal;

    /**
     * Gets the value of the direccionEdificio property.
     * 
     * @return
     *     possible object is
     *     {@link DireccionLic }
     *     
     */
    public DireccionLic getDireccionEdificio() {
        return direccionEdificio;
    }

    /**
     * Sets the value of the direccionEdificio property.
     * 
     * @param value
     *     allowed object is
     *     {@link DireccionLic }
     *     
     */
    public void setDireccionEdificio(DireccionLic value) {
        this.direccionEdificio = value;
    }

    /**
     * Gets the value of the numPortales property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumPortales() {
        return numPortales;
    }

    /**
     * Sets the value of the numPortales property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumPortales(BigInteger value) {
        this.numPortales = value;
    }

    /**
     * Gets the value of the portal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatosPortalAlta }
     * 
     * 
     */
    public List<DatosPortalAlta> getPortal() {
        if (portal == null) {
            portal = new ArrayList<DatosPortalAlta>();
        }
        return this.portal;
    }

}
