//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:49 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resumen_edificacion_valor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resumen_edificacion_valor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="num_unidades" type="{http://licencias/mensajes}int5type"/>
 *         &lt;element name="sup_construida" type="{http://licencias/mensajes}decimal103type"/>
 *         &lt;element name="sup_computable" type="{http://licencias/mensajes}decimal103type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resumen_edificacion_valor", propOrder = {
    "numUnidades",
    "supConstruida",
    "supComputable"
})
public class ResumenEdificacionValor {

    @XmlElement(name = "num_unidades", required = true)
    protected BigInteger numUnidades;
    @XmlElement(name = "sup_construida", required = true)
    protected BigDecimal supConstruida;
    @XmlElement(name = "sup_computable", required = true)
    protected BigDecimal supComputable;

    /**
     * Gets the value of the numUnidades property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumUnidades() {
        return numUnidades;
    }

    /**
     * Sets the value of the numUnidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumUnidades(BigInteger value) {
        this.numUnidades = value;
    }

    /**
     * Gets the value of the supConstruida property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSupConstruida() {
        return supConstruida;
    }

    /**
     * Sets the value of the supConstruida property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSupConstruida(BigDecimal value) {
        this.supConstruida = value;
    }

    /**
     * Gets the value of the supComputable property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSupComputable() {
        return supComputable;
    }

    /**
     * Sets the value of the supComputable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSupComputable(BigDecimal value) {
        this.supComputable = value;
    }

}
