//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.20 at 04:26:49 PM CEST 
//


package org.gestoresmadrid.oegam2comun.licenciasCam.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipos_aparcamiento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipos_aparcamiento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dotacional" type="{http://licencias/mensajes}int5type" minOccurs="0"/>
 *         &lt;element name="libre_disposicion" type="{http://licencias/mensajes}int5type" minOccurs="0"/>
 *         &lt;element name="total" type="{http://licencias/mensajes}int5type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipos_aparcamiento", propOrder = {
    "dotacional",
    "libreDisposicion",
    "total"
})
public class TiposAparcamiento {

    protected BigInteger dotacional;
    @XmlElement(name = "libre_disposicion")
    protected BigInteger libreDisposicion;
    protected BigInteger total;

    /**
     * Gets the value of the dotacional property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDotacional() {
        return dotacional;
    }

    /**
     * Sets the value of the dotacional property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDotacional(BigInteger value) {
        this.dotacional = value;
    }

    /**
     * Gets the value of the libreDisposicion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLibreDisposicion() {
        return libreDisposicion;
    }

    /**
     * Sets the value of the libreDisposicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLibreDisposicion(BigInteger value) {
        this.libreDisposicion = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotal(BigInteger value) {
        this.total = value;
    }

}
